"""
Biome-specific idle behaviors for the duck.
50 unique behaviors per biome that the duck performs autonomously
when visiting different areas.

Each behavior is a (message, duration, feature_tag) tuple.
The feature_tag tells the AI which zone of the playfield the duck
should walk to before performing the action, so animations line up
with the visual scenery.

Feature tags:
  "water"      - near water (pond, river, ocean, fountain, pool)
  "vegetation" - near trees, plants, reeds, flowers, mushrooms
  "ground"     - open ground, clearings, paths (center area)
  "edge"       - shores, banks, cliff edges, perimeter
  "rocks"      - rocky areas, boulders, pebbles, cave features
  "structure"  - man-made features (dock, bench, shed, ruins, boardwalk)
"""

import random
from typing import Dict, List, Tuple, Optional

# Each biome has 50 unique action behaviors.
# Format: (message, duration_seconds, feature_tag)

BIOME_BEHAVIORS: Dict[str, List[Tuple[str, float, str]]] = {
    # =========================================================================
    # POND — Home base, water, reeds, lily pads, fish, frogs
    # =========================================================================
    "pond": [
        ("*dips beak in the water and blows bubbles*", 10.0, "water"),
        ("*floats serenely across the pond*", 15.0, "water"),
        ("*dives under and pops back up with a mouthful of pondweed*", 8.0, "water"),
        ("*watches a fish dart beneath the surface*", 7.0, "water"),
        ("*nudges a lily pad with beak*", 6.0, "water"),
        ("*sits on a lily pad... it sinks a little*", 9.0, "water"),
        ("*splashes water onto back with wings*", 8.0, "water"),
        ("*paddles in lazy circles*", 12.0, "water"),
        ("*preens feathers while floating*", 14.0, "water"),
        ("*stares at own reflection in the water*", 10.0, "water"),
        ("*snaps at a dragonfly hovering overhead*", 5.0, "ground"),
        ("*tucks beak under wing for a float-nap*", 20.0, "water"),
        ("*pushes through reeds making rustling sounds*", 8.0, "vegetation"),
        ("*dips head underwater and wiggles tail in the air*", 6.0, "water"),
        ("*watches tadpoles swim by*", 9.0, "water"),
        ("*rides a gentle ripple across the pond*", 10.0, "water"),
        ("*investigates a frog sitting on a rock*", 7.0, "edge"),
        ("*shakes water off feathers dramatically*", 5.0, "edge"),
        ("*pecks at something shiny under the water*", 8.0, "water"),
        ("*floats backward accidentally*", 6.0, "water"),
        ("*chatters at a passing moorhen*", 7.0, "water"),
        ("*digs beak into the muddy bank*", 8.0, "edge"),
        ("*stands on one leg at the water's edge*", 12.0, "edge"),
        ("*watches the clouds reflected in the pond*", 11.0, "water"),
        ("*makes tiny waves by wiggling feet underwater*", 9.0, "water"),
        ("*discovers a snail on a reed and stares at it*", 10.0, "vegetation"),
        ("*tries to catch a water skater... misses*", 6.0, "water"),
        ("*finds a comfortable spot between two reeds*", 14.0, "vegetation"),
        ("*practices diving technique*", 8.0, "water"),
        ("*splashes excitedly for no apparent reason*", 7.0, "water"),
        ("*wades in the shallows, pecking at pebbles*", 10.0, "edge"),
        ("*listens to the frogs croaking*", 9.0, "edge"),
        ("*stretches wings out wide by the water*", 8.0, "edge"),
        ("*collects a pretty pebble from the pond bed*", 7.0, "water"),
        ("*nibbles on some duckweed*", 10.0, "water"),
        ("*watches a heron in the distance warily*", 12.0, "edge"),
        ("*does a little spin on the water*", 5.0, "water"),
        ("*sunbathes on the warm bank*", 18.0, "edge"),
        ("*flicks water droplets off tail feathers*", 6.0, "edge"),
        ("*peeks over a tussock of grass curiously*", 7.0, "vegetation"),
        ("*chases another duck's ripple trail*", 8.0, "water"),
        ("*finds a cozy mud puddle nearby*", 10.0, "edge"),
        ("*bobs head rhythmically while floating*", 9.0, "water"),
        ("*quacks softly at the setting sun reflected in the pond*", 8.0, "water"),
        ("*notices a turtle and follows it slowly*", 12.0, "water"),
        ("*rearranges reeds into a more comfortable arrangement*", 10.0, "vegetation"),
        ("*plunges head in water and comes up with a tiny fish!*", 6.0, "water"),
        ("*fluffs up feathers and settles into the bank*", 14.0, "edge"),
        ("*listens to water lapping against the rocks*", 11.0, "edge"),
        ("*practices quacking at different volumes*", 8.0, "ground"),
    ],

    # =========================================================================
    # FOREST — Trees, twigs, leaves, berries, mushrooms, birds
    # =========================================================================
    "forest": [
        ("*waddles through crunchy fallen leaves*", 10.0, "ground"),
        ("*pecks at a mushroom growing on a log*", 8.0, "ground"),
        ("*looks up at the towering trees in awe*", 9.0, "vegetation"),
        ("*finds a stick and drags it around*", 12.0, "ground"),
        ("*startles at a squirrel running past*", 5.0, "vegetation"),
        ("*hides behind a tree trunk and peeks out*", 8.0, "vegetation"),
        ("*sniffs at some wild berries*", 7.0, "vegetation"),
        ("*gets tangled in a low-hanging vine*", 6.0, "vegetation"),
        ("*listens to birdsong and tilts head*", 10.0, "ground"),
        ("*waddles through a patch of ferns*", 8.0, "vegetation"),
        ("*investigates a hollow log*", 9.0, "ground"),
        ("*watches a spider spinning a web*", 11.0, "vegetation"),
        ("*tries to climb a root and slides back*", 6.0, "vegetation"),
        ("*finds a feather from another bird*", 7.0, "ground"),
        ("*sits in a sunbeam breaking through the canopy*", 15.0, "ground"),
        ("*kicks at a pinecone*", 5.0, "ground"),
        ("*follows a trail of ants with great interest*", 10.0, "ground"),
        ("*discovers an interesting rock under some moss*", 8.0, "rocks"),
        ("*ruffles feathers as a breeze rustles the trees*", 7.0, "ground"),
        ("*watches leaves fall and tries to catch one*", 9.0, "ground"),
        ("*pecks at tree bark looking for bugs*", 10.0, "vegetation"),
        ("*naps in a pile of soft leaves*", 18.0, "ground"),
        ("*waddles across a fallen log like a bridge*", 8.0, "ground"),
        ("*startles at an owl hooting*", 5.0, "vegetation"),
        ("*finds a patch of clover and nibbles*", 10.0, "ground"),
        ("*watches a woodpecker drumming on a tree*", 9.0, "vegetation"),
        ("*splashes in a tiny forest puddle*", 7.0, "water"),
        ("*explores a gap between tree roots*", 8.0, "vegetation"),
        ("*gets confused by an echo of own quack*", 6.0, "ground"),
        ("*discovers a cluster of wild mushrooms*", 8.0, "ground"),
        ("*follows a deer trail deeper into the woods*", 12.0, "ground"),
        ("*sits among the ferns and blends in... mostly*", 10.0, "vegetation"),
        ("*examines a cobweb glistening with dew*", 9.0, "vegetation"),
        ("*rolls in a patch of soft moss*", 8.0, "ground"),
        ("*listens to the wind whistling through branches*", 11.0, "ground"),
        ("*finds a hollow in a tree and peeks inside*", 7.0, "vegetation"),
        ("*discovers a tiny stream and follows it*", 12.0, "water"),
        ("*picks up an acorn and carries it around*", 9.0, "ground"),
        ("*watches a caterpillar inch along a branch*", 10.0, "vegetation"),
        ("*makes a nest-like pile of leaves and sits in it*", 14.0, "ground"),
        ("*hops over exposed tree roots*", 6.0, "vegetation"),
        ("*spots a rabbit and freezes, watching*", 10.0, "ground"),
        ("*shuffles through a pile of twigs*", 7.0, "ground"),
        ("*finds a clearing and does a happy waddle*", 8.0, "ground"),
        ("*pecks at a bracket fungus on a stump*", 7.0, "vegetation"),
        ("*chases a butterfly through the undergrowth*", 9.0, "vegetation"),
        ("*sits on a tree stump like a tiny throne*", 12.0, "ground"),
        ("*watches dappled sunlight dance on the forest floor*", 11.0, "ground"),
        ("*discovers old bird's nest in a bush*", 8.0, "vegetation"),
        ("*nibbles on some wild sorrel leaves*", 7.0, "vegetation"),
    ],

    # =========================================================================
    # MEADOW — Flowers, grass, seeds, insects, butterflies
    # =========================================================================
    "meadow": [
        ("*rolls in a patch of wildflowers*", 10.0, "vegetation"),
        ("*chases a butterfly across the meadow*", 9.0, "ground"),
        ("*sniffs at a daisy and sneezes*", 5.0, "vegetation"),
        ("*lies flat in the tall grass and disappears*", 14.0, "vegetation"),
        ("*watches bees buzzing between flowers*", 10.0, "vegetation"),
        ("*picks up a dandelion seed puff and blows it*", 6.0, "vegetation"),
        ("*waddles through a field of clover*", 10.0, "ground"),
        ("*finds a patch of warm grass and sunbathes*", 18.0, "ground"),
        ("*chases a grasshopper through the meadow*", 8.0, "ground"),
        ("*gets pollen on beak from sniffing flowers*", 6.0, "vegetation"),
        ("*stretches out flat in the sunshine*", 15.0, "ground"),
        ("*watches clouds and imagines bread shapes*", 12.0, "ground"),
        ("*discovers a ladybug and watches it climb a stem*", 9.0, "vegetation"),
        ("*runs through the tall grass making mini trails*", 10.0, "vegetation"),
        ("*finds a nice spot and flops down*", 14.0, "ground"),
        ("*pecks at seeds scattered in the grass*", 8.0, "ground"),
        ("*watches a kite being flown in the distance*", 10.0, "ground"),
        ("*practices camouflage in a flower patch*", 12.0, "vegetation"),
        ("*chases own shadow across the meadow*", 7.0, "ground"),
        ("*collects tiny wildflower petals*", 9.0, "vegetation"),
        ("*watches a field mouse dart through the grass*", 8.0, "vegetation"),
        ("*does a big stretch in the open space*", 6.0, "ground"),
        ("*flaps wings and makes dandelion seeds fly everywhere*", 7.0, "vegetation"),
        ("*finds a warm flat rock and sits on it*", 14.0, "rocks"),
        ("*listens to crickets chirping*", 10.0, "ground"),
        ("*follows a trail of wildflowers like a path*", 9.0, "vegetation"),
        ("*discovers a hidden rabbit hole*", 7.0, "ground"),
        ("*pecks curiously at a mushroom ring*", 8.0, "ground"),
        ("*stands very still pretending to be a flower*", 10.0, "vegetation"),
        ("*watches a hawk circling high above and crouches*", 8.0, "ground"),
        ("*wades through buttercups up to chest height*", 10.0, "vegetation"),
        ("*spotted a cricket and pounces... misses*", 6.0, "ground"),
        ("*does a victory waddle through the flowers*", 8.0, "vegetation"),
        ("*nibbles on sweet clover*", 9.0, "vegetation"),
        ("*plays peekaboo with a field vole*", 8.0, "vegetation"),
        ("*watches seeds blowing on the breeze*", 10.0, "ground"),
        ("*makes a little bed in the grass and naps*", 16.0, "vegetation"),
        ("*finds a feather caught in a thistle*", 7.0, "vegetation"),
        ("*investigates a strange buzzing in the grass*", 8.0, "ground"),
        ("*discovers poppy flowers and admires the color*", 9.0, "vegetation"),
        ("*races a bumblebee to the next flower... loses*", 7.0, "vegetation"),
        ("*collects grass blades and makes a tiny pile*", 10.0, "ground"),
        ("*watches butterflies dance in the warm air*", 12.0, "ground"),
        ("*finds an ant hill and watches the busy ants*", 11.0, "ground"),
        ("*takes a dust bath in a dry patch*", 8.0, "ground"),
        ("*quacks at a scarecrow in the distance*", 7.0, "structure"),
        ("*gets distracted by absolutely everything*", 10.0, "ground"),
        ("*sits among the wildflowers looking very picturesque*", 12.0, "vegetation"),
        ("*tries to eat a buttercup... decides against it*", 6.0, "vegetation"),
        ("*runs in circles through the meadow for pure joy*", 8.0, "ground"),
    ],

    # =========================================================================
    # RIVERSIDE — Pebbles, shells, clay, driftwood, flowing water
    # =========================================================================
    "riverside": [
        ("*wades in the shallow river current*", 10.0, "water"),
        ("*watches sticks float downstream*", 9.0, "water"),
        ("*pecks at smooth river pebbles*", 7.0, "rocks"),
        ("*sits on a rock in the middle of the stream*", 12.0, "rocks"),
        ("*tries to swim upstream... gets pushed back*", 8.0, "water"),
        ("*digs in the sandy riverbank*", 9.0, "edge"),
        ("*watches crayfish hiding under rocks*", 10.0, "rocks"),
        ("*finds a pretty shell and picks it up*", 7.0, "edge"),
        ("*splashes in the rushing water*", 8.0, "water"),
        ("*discovers a piece of driftwood and stands on it*", 9.0, "edge"),
        ("*watches fish jumping in the current*", 10.0, "water"),
        ("*pecks at clay along the bank*", 8.0, "edge"),
        ("*floats downstream a little then paddles back*", 12.0, "water"),
        ("*finds a quiet eddy and rests in it*", 14.0, "water"),
        ("*collects smooth pebbles from the riverbed*", 9.0, "rocks"),
        ("*watches a kingfisher dive into the water*", 8.0, "water"),
        ("*plays with river foam bubbles*", 7.0, "water"),
        ("*walks along stepping stones carefully*", 10.0, "rocks"),
        ("*dips feet in the cold river and shivers*", 6.0, "edge"),
        ("*investigates what's under a river rock*", 8.0, "rocks"),
        ("*watches dragonflies zip over the water*", 9.0, "water"),
        ("*finds a sandy shallow and makes a little pool*", 10.0, "edge"),
        ("*listens to the river gurgling over rocks*", 11.0, "edge"),
        ("*tries to catch a leaf floating past*", 6.0, "water"),
        ("*wades through pebbles making clacking sounds*", 8.0, "rocks"),
        ("*discovers water-smoothed glass among the stones*", 7.0, "edge"),
        ("*practices diving in a deep pool*", 10.0, "water"),
        ("*sits on the bank watching the river flow*", 14.0, "edge"),
        ("*follows the river current with eyes*", 9.0, "edge"),
        ("*pecks at a water snail on a rock*", 7.0, "rocks"),
        ("*shakes off after wading through rapids*", 5.0, "edge"),
        ("*explores under a small waterfall*", 10.0, "water"),
        ("*collects driftwood pieces into a tiny pile*", 9.0, "edge"),
        ("*watches water striders dance on the surface*", 10.0, "water"),
        ("*digs a channel in the mud connecting two puddles*", 12.0, "edge"),
        ("*basks on a warm river rock*", 15.0, "rocks"),
        ("*chases minnows in the shallows*", 8.0, "water"),
        ("*investigates interesting marks in the wet mud*", 7.0, "edge"),
        ("*splashes through a shallow crossing*", 6.0, "water"),
        ("*finds a bend in the river and explores it*", 10.0, "water"),
        ("*watches the sunset reflected in the river*", 12.0, "water"),
        ("*stacks tiny pebbles into a little tower*", 10.0, "rocks"),
        ("*dips bill into the flowing water and drinks*", 6.0, "water"),
        ("*hops along the mossy riverside rocks*", 8.0, "rocks"),
        ("*discovers an old log Bridge and crosses it nervously*", 10.0, "structure"),
        ("*watches bubbles rise from the river bottom*", 8.0, "water"),
        ("*plays in the spray from a small waterfall*", 9.0, "water"),
        ("*naps on a warm sandbar*", 16.0, "edge"),
        ("*examines fresh animal tracks in the mud*", 8.0, "edge"),
        ("*paddles against the current for exercise*", 10.0, "water"),
    ],

    # =========================================================================
    # GARDEN — Vegetables, flowers, string, fabric, vegetable plots
    # =========================================================================
    "garden": [
        ("*pecks at a tomato growing on a vine*", 8.0, "vegetation"),
        ("*waddles between rows of vegetables*", 10.0, "ground"),
        ("*investigates the garden hose suspiciously*", 7.0, "structure"),
        ("*finds a worm in the freshly turned soil*", 6.0, "ground"),
        ("*sits next to a garden gnome and mimics its pose*", 12.0, "structure"),
        ("*nibbles on lettuce leaves*", 9.0, "vegetation"),
        ("*watches a snail crawl across a cabbage*", 10.0, "vegetation"),
        ("*inspects sunflowers that are taller than cheese*", 8.0, "vegetation"),
        ("*digs in the compost heap*", 9.0, "ground"),
        ("*gets tangled in garden netting*", 7.0, "structure"),
        ("*discovers a strawberry and pecks at it eagerly*", 6.0, "vegetation"),
        ("*sits in the shade of a huge pumpkin*", 12.0, "vegetation"),
        ("*watches a robin pull worms from the lawn*", 9.0, "ground"),
        ("*waddles along the garden path*", 8.0, "ground"),
        ("*naps under a rhubarb leaf umbrella*", 16.0, "vegetation"),
        ("*examines the watering can with great curiosity*", 8.0, "structure"),
        ("*plays with a garden sprinkler*", 10.0, "water"),
        ("*pecks at fallen apples under a tree*", 7.0, "vegetation"),
        ("*hides among the bean poles*", 10.0, "vegetation"),
        ("*discovers a slug and isn't sure what to think*", 8.0, "ground"),
        ("*walks along the top of a garden wall*", 9.0, "edge"),
        ("*splashes in a bird bath in the garden*", 8.0, "water"),
        ("*watches herbs swaying in the breeze*", 9.0, "vegetation"),
        ("*finds string on the ground and pulls it*", 7.0, "ground"),
        ("*investigates a flower pot and tips it over*", 6.0, "structure"),
        ("*sits between rows of carrots looking content*", 12.0, "vegetation"),
        ("*watches a bee enter a bee hotel*", 8.0, "structure"),
        ("*peeks inside the garden shed*", 7.0, "structure"),
        ("*waddles through the herb garden — smells nice!*", 9.0, "vegetation"),
        ("*discovers a patch of mint and nibbles*", 8.0, "vegetation"),
        ("*plays in a pile of freshly pulled weeds*", 7.0, "ground"),
        ("*naps in a wheelbarrow*", 14.0, "structure"),
        ("*chases a cabbage white butterfly*", 8.0, "ground"),
        ("*pecks at seeds in a bird feeder*", 9.0, "structure"),
        ("*explores the greenhouse and steams up*", 10.0, "structure"),
        ("*finds a terracotta pot saucer to splash in*", 8.0, "structure"),
        ("*admires the roses from a safe distance (thorns!)*", 9.0, "vegetation"),
        ("*kicks a small garden stone around*", 7.0, "ground"),
        ("*watches a toad hop across the path*", 8.0, "ground"),
        ("*finds fabric scraps near the compost and plays*", 9.0, "ground"),
        ("*sits on a bag of potting soil*", 10.0, "structure"),
        ("*pecks at a scarecrow's button nose*", 6.0, "structure"),
        ("*waddles through the lavender patch and smells lovely*", 10.0, "vegetation"),
        ("*investigates wind chimes hanging from a post*", 8.0, "structure"),
        ("*discovers a tiny frog hiding in the lettuce*", 7.0, "vegetation"),
        ("*lounges in a warm patch between the raised beds*", 14.0, "ground"),
        ("*watches rain collect in a bucket*", 9.0, "structure"),
        ("*finds a caterpillar on a leaf and watches it munch*", 10.0, "vegetation"),
        ("*pecks at gravel on the garden path*", 7.0, "ground"),
        ("*stands proudly in the vegetable patch like a scarecrow*", 10.0, "ground"),
    ],

    # =========================================================================
    # MOUNTAINS — Rocks, crystals, moss, pine, altitude, eagles
    # =========================================================================
    "mountains": [
        ("*scrambles up a rocky slope*", 10.0, "rocks"),
        ("*stands on a ledge and surveys the view below*", 12.0, "edge"),
        ("*pecks at lichen growing on a boulder*", 8.0, "rocks"),
        ("*shivers in the mountain breeze*", 6.0, "ground"),
        ("*discovers a shiny crystal in a rock crack*", 8.0, "rocks"),
        ("*slides down a smooth rock surface — wheee!*", 7.0, "rocks"),
        ("*huddles behind a rock for shelter from the wind*", 10.0, "rocks"),
        ("*watches an eagle soar overhead nervously*", 9.0, "ground"),
        ("*investigates a tiny mountain stream*", 8.0, "water"),
        ("*finds moss growing between rocks and feels it*", 7.0, "rocks"),
        ("*quacks and hears the echo bounce off cliffs*", 8.0, "edge"),
        ("*climbs higher and looks back proudly*", 10.0, "edge"),
        ("*discovers a mountain goat trail and follows it*", 12.0, "ground"),
        ("*rests in a sheltered rocky outcrop*", 14.0, "rocks"),
        ("*pecks at pine nuts under a twisted pine tree*", 9.0, "vegetation"),
        ("*watches clouds drift below the mountain peak*", 11.0, "edge"),
        ("*finds a geode and taps it curiously*", 8.0, "rocks"),
        ("*naps in a warm sunny spot between rocks*", 16.0, "rocks"),
        ("*explores a small mountain cave entrance*", 10.0, "rocks"),
        ("*collects interesting pebbles from the trail*", 9.0, "ground"),
        ("*watches a marmot pop up from its burrow*", 8.0, "ground"),
        ("*sits on a flat rock and enjoys the vista*", 14.0, "rocks"),
        ("*gets buffeted by a sudden gust of wind*", 5.0, "edge"),
        ("*finds a snow patch and touches it with beak*", 7.0, "ground"),
        ("*walks along a narrow ridge carefully*", 10.0, "edge"),
        ("*discovers wild mountain herbs and sniffs them*", 8.0, "vegetation"),
        ("*watches a waterfall cascade down the mountain*", 12.0, "water"),
        ("*picks at berries growing on a mountain bush*", 9.0, "vegetation"),
        ("*stacks stones into a tiny cairn*", 10.0, "rocks"),
        ("*yodels... wait, ducks can't yodel... QUACK!*", 6.0, "ground"),
        ("*watches the mist swirl through the peaks*", 11.0, "edge"),
        ("*scrambles over loose scree and stumbles*", 7.0, "rocks"),
        ("*finds a protected grove of alpine flowers*", 9.0, "vegetation"),
        ("*balances on a pointy rock like a mountain climber*", 8.0, "rocks"),
        ("*watches snow melt trickle down the mountainside*", 10.0, "water"),
        ("*explores a rocky overhang for shelter*", 9.0, "rocks"),
        ("*pecks at quartz crystals poking from stone*", 8.0, "rocks"),
        ("*does a proud pose at the summit*", 7.0, "edge"),
        ("*watches the sunrise paint the mountain orange*", 12.0, "edge"),
        ("*finds a pine cone and rolls it downhill*", 7.0, "vegetation"),
        ("*discovers fossils in the exposed rock face*", 10.0, "rocks"),
        ("*waddles through a patch of mountain wildflowers*", 9.0, "vegetation"),
        ("*listens to the wind howling through a gap*", 8.0, "edge"),
        ("*spots a mountain stream and splashes in*", 8.0, "water"),
        ("*takes shelter under a overhanging rock*", 12.0, "rocks"),
        ("*examines interesting layers in a cliff face*", 9.0, "rocks"),
        ("*watches ravens playing in the thermals*", 10.0, "ground"),
        ("*collects pine needles for... reasons*", 7.0, "vegetation"),
        ("*sits on the highest rock and feels majestic*", 12.0, "rocks"),
        ("*investigates a mysterious mountain cave echo*", 10.0, "rocks"),
    ],

    # =========================================================================
    # BEACH — Sand, shells, seaweed, glass, waves, crabs, seagulls
    # =========================================================================
    "beach": [
        ("*waddles along the shoreline*", 10.0, "edge"),
        ("*digs in the wet sand with beak*", 8.0, "edge"),
        ("*watches waves crash and backs away nervously*", 7.0, "water"),
        ("*finds a perfect seashell*", 6.0, "edge"),
        ("*splashes in a rock pool*", 9.0, "rocks"),
        ("*chases a crab sideways... the crab is faster*", 8.0, "edge"),
        ("*sits on the sand and watches the tide*", 12.0, "edge"),
        ("*collects sea glass from the tideline*", 9.0, "edge"),
        ("*pecks at a strand of seaweed*", 7.0, "edge"),
        ("*makes footprints in the wet sand*", 8.0, "edge"),
        ("*watches a hermit crab change shells*", 10.0, "rocks"),
        ("*stands at the water's edge as waves wash over feet*", 9.0, "edge"),
        ("*builds a tiny sand castle... it collapses*", 10.0, "ground"),
        ("*discovers a starfish in a rock pool*", 8.0, "rocks"),
        ("*runs away from a wave then runs back*", 7.0, "edge"),
        ("*sunbathes on warm sand*", 18.0, "ground"),
        ("*finds a piece of driftwood shaped like a boat*", 8.0, "edge"),
        ("*watches seagulls fighting over chips*", 9.0, "ground"),
        ("*digs a hole in the sand and sits in it*", 10.0, "ground"),
        ("*examines a jellyfish washed up on shore carefully*", 8.0, "edge"),
        ("*races the waves along the beach*", 9.0, "edge"),
        ("*finds a tide pool full of tiny fish*", 10.0, "rocks"),
        ("*collects shells along the waterline*", 9.0, "edge"),
        ("*watches a boat on the horizon*", 11.0, "water"),
        ("*tries to eat some seaweed... salty!*", 6.0, "edge"),
        ("*waddles through the dunes*", 8.0, "ground"),
        ("*plays with a beach ball left behind*", 9.0, "ground"),
        ("*watches a sandpiper run along the shore*", 8.0, "edge"),
        ("*discovers a message in a bottle!*", 7.0, "edge"),
        ("*buries feet in warm sand*", 10.0, "ground"),
        ("*explores a barnacle-covered rock*", 8.0, "rocks"),
        ("*naps in the shade of a sand dune*", 16.0, "ground"),
        ("*watches the sunset over the ocean*", 12.0, "water"),
        ("*pecks at a coconut washed ashore*", 7.0, "edge"),
        ("*splashes joyfully in the shallows*", 9.0, "water"),
        ("*finds a sand dollar and carries it carefully*", 8.0, "edge"),
        ("*listens to the sound of waves crashing*", 11.0, "edge"),
        ("*investigates seaweed-covered rocks*", 8.0, "rocks"),
        ("*does a happy dance on the hot sand*", 6.0, "ground"),
        ("*watches pelicans dive into the sea*", 10.0, "water"),
        ("*writes name in the sand with beak*", 9.0, "ground"),
        ("*builds a little pebble line along the shore*", 10.0, "edge"),
        ("*discovers a tiny crab hiding under seaweed*", 7.0, "edge"),
        ("*paddles in a warm shallow pool*", 10.0, "water"),
        ("*gets spooked by a wave and runs up the beach*", 5.0, "edge"),
        ("*examines interesting patterns in the sand*", 8.0, "ground"),
        ("*watches a lighthouse in the distance*", 10.0, "water"),
        ("*finds a smooth pebble perfect for skipping*", 7.0, "rocks"),
        ("*chases foam left behind by a receding wave*", 7.0, "edge"),
        ("*sits on a rock and lets the breeze ruffle feathers*", 12.0, "rocks"),
    ],

    # =========================================================================
    # SWAMP — Murky water, fireflies, bog plants, mist, mysterious
    # =========================================================================
    "swamp": [
        ("*wades through murky water cautiously*", 10.0, "water"),
        ("*watches fireflies blink in the gloom*", 12.0, "ground"),
        ("*pecks at a mushroom growing on a rotting stump*", 8.0, "vegetation"),
        ("*gets stuck in the mud and wiggles free*", 7.0, "ground"),
        ("*listens to mysterious croaking sounds*", 9.0, "ground"),
        ("*explores between cypress tree roots*", 10.0, "vegetation"),
        ("*watches mist curl around the trees*", 11.0, "vegetation"),
        ("*finds a glowing fungus and stares at it*", 8.0, "vegetation"),
        ("*jumps at own reflection in dark water*", 5.0, "water"),
        ("*investigates a bubbling patch of swamp*", 8.0, "water"),
        ("*discovers an old tree with a face-like pattern*", 9.0, "vegetation"),
        ("*pushes through hanging moss curtains*", 7.0, "vegetation"),
        ("*sits on a floating log and drifts slowly*", 14.0, "water"),
        ("*watches a bullfrog sitting on a lily pad*", 10.0, "water"),
        ("*finds bog berries and inspects them carefully*", 8.0, "vegetation"),
        ("*gets spooked by a heron appearing from the fog*", 6.0, "ground"),
        ("*splashes through shallow muddy water*", 8.0, "water"),
        ("*discovers strange tracks in the mud*", 9.0, "ground"),
        ("*watches water bubbles rise from the swamp bed*", 10.0, "water"),
        ("*navigates between tufts of marsh grass*", 8.0, "vegetation"),
        ("*pecks at a carnivorous plant... carefully*", 7.0, "vegetation"),
        ("*finds a dry hummock and rests on it*", 12.0, "ground"),
        ("*watches a snake slither through the water and freezes*", 8.0, "water"),
        ("*listens to eerie sounds in the distance*", 10.0, "ground"),
        ("*examines a turtle sunning on a log*", 9.0, "water"),
        ("*squelches through the softest mud*", 7.0, "ground"),
        ("*discovers a hidden pool of clear water*", 8.0, "water"),
        ("*watches dragonflies hover over the swamp*", 10.0, "water"),
        ("*naps on a tuft of dry swamp grass*", 14.0, "vegetation"),
        ("*investigates a hollow tree stump full of water*", 8.0, "vegetation"),
        ("*follows wisps of mist through the trees*", 10.0, "vegetation"),
        ("*finds an interesting bone and inspects it*", 7.0, "ground"),
        ("*hops between dry patches to avoid the mud*", 8.0, "ground"),
        ("*watches an alligator-shaped log... is it a log?*", 9.0, "water"),
        ("*collects unusual swamp pebbles*", 8.0, "ground"),
        ("*spots rare orchids growing on a tree*", 9.0, "vegetation"),
        ("*gets briefly lost in the fog then finds the path*", 10.0, "ground"),
        ("*watches pitcher plants collecting flies*", 10.0, "vegetation"),
        ("*discovers a tiny island of moss*", 7.0, "vegetation"),
        ("*listens to the chorus of frogs at dusk*", 12.0, "water"),
        ("*explores an old wooden boardwalk*", 9.0, "structure"),
        ("*finds something shiny in the muck!*", 7.0, "ground"),
        ("*watches an egret fishing in the shallows*", 10.0, "water"),
        ("*carefully crosses a patch of quicksand-like mud*", 8.0, "ground"),
        ("*sits on a root and watches fireflies dance*", 14.0, "vegetation"),
        ("*pecks at cattails by the water's edge*", 7.0, "vegetation"),
        ("*watches a water moccasin from a very safe distance*", 9.0, "water"),
        ("*discovers a crystal-clear spring bubbling up*", 8.0, "water"),
        ("*makes squelching noises in the mud on purpose*", 6.0, "ground"),
        ("*navigates through a curtain of Spanish moss*", 9.0, "vegetation"),
    ],

    # =========================================================================
    # URBAN — City park, bread crumbs, coins, benches, humans
    # =========================================================================
    "urban": [
        ("*waddles across a park bench*", 8.0, "structure"),
        ("*pecks at bread crumbs on the path*", 7.0, "ground"),
        ("*watches humans walking their dogs*", 10.0, "ground"),
        ("*finds a lost coin on the pavement!*", 6.0, "ground"),
        ("*sits by the park fountain*", 12.0, "water"),
        ("*chases a pigeon away from the bread*", 7.0, "ground"),
        ("*investigates a discarded crisp packet*", 8.0, "ground"),
        ("*waddles across a pedestrian crossing*", 9.0, "ground"),
        ("*sits on a park bench like a tiny person*", 12.0, "structure"),
        ("*watches a busker playing music and bobs head*", 10.0, "ground"),
        ("*finds chips on the ground and celebrates*", 7.0, "ground"),
        ("*gets confused by its reflection in a shop window*", 8.0, "structure"),
        ("*watches children on the playground swings*", 10.0, "structure"),
        ("*explores under a park bridge*", 9.0, "structure"),
        ("*splashes in the park fountain*", 10.0, "water"),
        ("*pecks at a dropped ice cream... score!*", 7.0, "ground"),
        ("*watches a street performer and quacks along*", 9.0, "ground"),
        ("*naps on a warm manhole cover*", 14.0, "ground"),
        ("*waddles through the farmer's market*", 10.0, "ground"),
        ("*finds a bottle cap and plays with it*", 7.0, "ground"),
        ("*watches cars go by from the park*", 9.0, "edge"),
        ("*explores a drain grate with great interest*", 8.0, "ground"),
        ("*steals a bit of sandwich from an unattended lunch*", 6.0, "ground"),
        ("*sits in a planter box among the flowers*", 10.0, "vegetation"),
        ("*watches a cyclist zoom past and ruffles feathers*", 6.0, "edge"),
        ("*discovers a puddle and splashes in it*", 8.0, "water"),
        ("*follows a human hoping for food*", 10.0, "ground"),
        ("*inspects a statue in the park*", 9.0, "structure"),
        ("*waddles through the park gate like it owns the place*", 8.0, "ground"),
        ("*pecks at a shiny gum wrapper*", 6.0, "ground"),
        ("*listens to church bells in the distance*", 9.0, "ground"),
        ("*finds a warm heating vent and sits on it*", 14.0, "structure"),
        ("*watches pigeons with mild disdain*", 8.0, "ground"),
        ("*explores around a lamppost*", 7.0, "structure"),
        ("*spots a food truck and waddles toward it hopefully*", 10.0, "edge"),
        ("*sits in a puddle after the sprinklers ran*", 9.0, "water"),
        ("*watches a kite flying over the park*", 10.0, "ground"),
        ("*discovers a playground and tries the slide*", 8.0, "structure"),
        ("*naps under a park bench in the shade*", 16.0, "structure"),
        ("*pecks at moss growing between paving stones*", 7.0, "ground"),
        ("*watches a dog and stays very still*", 8.0, "ground"),
        ("*waddles around the park lake importantly*", 10.0, "water"),
        ("*finds a ribbon caught on a fence*", 7.0, "edge"),
        ("*sits on the park steps and people-watches*", 12.0, "structure"),
        ("*investigates a candy wrapper blowing in the wind*", 6.0, "ground"),
        ("*splashes in sprinkler spray*", 9.0, "water"),
        ("*examines a park sign like it can read*", 8.0, "structure"),
        ("*takes shelter under an awning*", 10.0, "structure"),
        ("*watches a train rumble past in the distance*", 9.0, "edge"),
        ("*sits in a flower bed and looks decorative*", 12.0, "vegetation"),
    ],
}


# =============================================================================
# LOCATION FEATURE ZONES
# =============================================================================
# Maps each location name to its feature zones.
# Each zone is (x_min_frac, y_min_frac, x_max_frac, y_max_frac) as fractions
# of the playfield dimensions (0.0-1.0).
# These zones correspond to where scenery features are visually placed by
# the location_art.py scenery generators.

LOCATION_FEATURE_ZONES: Dict[str, Dict[str, Tuple[float, float, float, float]]] = {
    # ----- POND BIOME -----
    "Home Pond": {
        "water":      (0.25, 0.25, 0.75, 0.65),
        "vegetation": (0.00, 0.50, 0.20, 0.90),
        "edge":       (0.15, 0.70, 0.85, 0.95),
        "ground":     (0.05, 0.00, 0.95, 0.25),
        "structure":  (0.75, 0.00, 0.95, 0.15),
    },
    "Deep End": {
        "water":      (0.10, 0.10, 0.90, 0.80),
        "vegetation": (0.00, 0.60, 0.30, 0.90),
        "edge":       (0.05, 0.75, 0.95, 0.95),
        "ground":     (0.10, 0.70, 0.90, 0.95),
        "rocks":      (0.30, 0.50, 0.70, 0.80),
    },
    # ----- FOREST BIOME -----
    "Forest Edge": {
        "vegetation": (0.00, 0.00, 1.00, 0.33),
        "water":      (0.00, 0.65, 1.00, 0.90),
        "ground":     (0.10, 0.30, 0.90, 0.65),
        "edge":       (0.00, 0.55, 1.00, 0.70),
        "rocks":      (0.05, 0.35, 0.50, 0.55),
    },
    "Ancient Oak": {
        "vegetation": (0.20, 0.00, 0.80, 0.55),
        "ground":     (0.00, 0.55, 1.00, 0.95),
        "rocks":      (0.10, 0.60, 0.40, 0.85),
    },
    "Mushroom Grove": {
        "vegetation": (0.15, 0.10, 0.85, 0.70),
        "ground":     (0.05, 0.70, 0.95, 0.95),
        "rocks":      (0.20, 0.40, 0.50, 0.65),
    },
    # ----- MEADOW BIOME -----
    "Sunny Meadow": {
        "vegetation": (0.10, 0.15, 0.90, 0.70),
        "ground":     (0.05, 0.05, 0.95, 0.95),
        "structure":  (0.60, 0.15, 0.85, 0.45),
        "rocks":      (0.30, 0.50, 0.60, 0.70),
    },
    "Butterfly Garden": {
        "vegetation": (0.10, 0.10, 0.90, 0.80),
        "ground":     (0.15, 0.40, 0.85, 0.90),
        "structure":  (0.10, 0.00, 0.90, 0.20),
    },
    # ----- RIVERSIDE BIOME -----
    "Pebble Beach": {
        "water":      (0.00, 0.65, 1.00, 0.95),
        "rocks":      (0.10, 0.30, 0.90, 0.65),
        "edge":       (0.00, 0.55, 1.00, 0.70),
        "ground":     (0.10, 0.10, 0.90, 0.55),
        "structure":  (0.60, 0.10, 0.90, 0.40),
    },
    "Waterfall": {
        "water":      (0.25, 0.00, 0.75, 0.95),
        "rocks":      (0.00, 0.60, 0.30, 0.90),
        "edge":       (0.00, 0.50, 1.00, 0.65),
        "ground":     (0.70, 0.30, 0.95, 0.70),
    },
    # ----- GARDEN BIOME -----
    "Vegetable Patch": {
        "vegetation": (0.10, 0.10, 0.90, 0.70),
        "ground":     (0.05, 0.05, 0.95, 0.95),
        "structure":  (0.60, 0.60, 0.90, 0.90),
        "water":      (0.10, 0.75, 0.50, 0.90),
        "edge":       (0.00, 0.00, 1.00, 0.10),
    },
    "Tool Shed": {
        "structure":  (0.15, 0.10, 0.85, 0.70),
        "ground":     (0.05, 0.70, 0.95, 0.95),
        "vegetation": (0.00, 0.00, 0.15, 0.40),
    },
    # ----- MOUNTAINS BIOME -----
    "Foothills": {
        "rocks":      (0.10, 0.05, 0.90, 0.50),
        "vegetation": (0.00, 0.30, 0.30, 0.70),
        "ground":     (0.10, 0.40, 0.90, 0.90),
        "edge":       (0.00, 0.00, 1.00, 0.15),
        "water":      (0.20, 0.55, 0.80, 0.75),
    },
    "Crystal Cave": {
        "rocks":      (0.20, 0.10, 0.80, 0.60),
        "water":      (0.15, 0.60, 0.85, 0.85),
        "ground":     (0.05, 0.70, 0.95, 0.95),
        "vegetation": (0.00, 0.65, 0.25, 0.90),
    },
    # ----- BEACH BIOME -----
    "Sandy Shore": {
        "water":      (0.00, 0.70, 1.00, 0.95),
        "ground":     (0.10, 0.20, 0.90, 0.65),
        "edge":       (0.00, 0.55, 1.00, 0.72),
        "rocks":      (0.60, 0.30, 0.85, 0.55),
        "vegetation": (0.05, 0.00, 0.25, 0.50),
    },
    "Shipwreck Cove": {
        "structure":  (0.20, 0.00, 0.80, 0.50),
        "water":      (0.00, 0.70, 1.00, 0.95),
        "ground":     (0.05, 0.45, 0.95, 0.70),
        "edge":       (0.00, 0.60, 1.00, 0.75),
        "rocks":      (0.05, 0.55, 0.40, 0.75),
    },
    # ----- SWAMP BIOME -----
    "Misty Marsh": {
        "water":      (0.20, 0.30, 0.80, 0.70),
        "vegetation": (0.00, 0.10, 0.30, 0.60),
        "ground":     (0.05, 0.05, 0.95, 0.95),
        "structure":  (0.50, 0.70, 0.90, 0.90),
    },
    "Cypress Hollow": {
        "vegetation": (0.10, 0.00, 0.50, 0.55),
        "water":      (0.30, 0.35, 0.80, 0.70),
        "ground":     (0.05, 0.60, 0.95, 0.95),
        "structure":  (0.50, 0.60, 0.85, 0.85),
    },
    "Sunken Ruins": {
        "structure":  (0.15, 0.10, 0.85, 0.60),
        "water":      (0.10, 0.50, 0.90, 0.80),
        "ground":     (0.05, 0.70, 0.95, 0.95),
        "rocks":      (0.20, 0.15, 0.60, 0.50),
    },
    # ----- URBAN BIOME -----
    "Park Fountain": {
        "water":      (0.25, 0.10, 0.75, 0.55),
        "structure":  (0.60, 0.55, 0.90, 0.80),
        "vegetation": (0.10, 0.65, 0.50, 0.85),
        "ground":     (0.05, 0.05, 0.95, 0.95),
        "edge":       (0.00, 0.00, 1.00, 0.10),
    },
    "Rooftop Garden": {
        "vegetation": (0.10, 0.10, 0.90, 0.60),
        "structure":  (0.50, 0.55, 0.90, 0.85),
        "ground":     (0.05, 0.60, 0.50, 0.95),
        "edge":       (0.00, 0.00, 1.00, 0.10),
    },
    "Storm Drain": {
        "structure":  (0.15, 0.00, 0.85, 0.30),
        "water":      (0.10, 0.50, 0.90, 0.80),
        "ground":     (0.05, 0.30, 0.95, 0.95),
    },
}


def get_biome_target(location: str, feature_tag: str,
                     field_width: int, field_height: int) -> Optional[Tuple[int, int]]:
    """Convert a feature tag + location into absolute playfield coordinates.

    Returns (x, y) target position, or None if no zone is defined for
    this feature at this location (duck stays in place).
    """
    zones = LOCATION_FEATURE_ZONES.get(location)
    if not zones:
        return None
    zone = zones.get(feature_tag)
    if not zone:
        return None

    x_min_f, y_min_f, x_max_f, y_max_f = zone
    margin = 3
    x_min = max(margin, int(x_min_f * field_width))
    x_max = max(x_min, min(field_width - margin - 6, int(x_max_f * field_width)))
    y_min = max(margin, int(y_min_f * field_height))
    y_max = max(y_min, min(field_height - margin - 3, int(y_max_f * field_height)))

    return (random.randint(x_min, x_max), random.randint(y_min, y_max))
