"""
Biome-specific idle behaviors for the duck.
50 unique behaviors per biome that the duck performs autonomously
when visiting different areas.
"""

# Each biome has 50 unique action messages the duck can perform.
# These are selected by the behavior AI when the duck is in that biome.
# Format: list of (message, duration_seconds) tuples

BIOME_BEHAVIORS = {
    # =========================================================================
    # POND — Home base, water, reeds, lily pads, fish, frogs
    # =========================================================================
    "pond": [
        ("*dips beak in the water and blows bubbles*", 10.0),
        ("*floats serenely across the pond*", 15.0),
        ("*dives under and pops back up with a mouthful of pondweed*", 8.0),
        ("*watches a fish dart beneath the surface*", 7.0),
        ("*nudges a lily pad with beak*", 6.0),
        ("*sits on a lily pad... it sinks a little*", 9.0),
        ("*splashes water onto back with wings*", 8.0),
        ("*paddles in lazy circles*", 12.0),
        ("*preens feathers while floating*", 14.0),
        ("*stares at own reflection in the water*", 10.0),
        ("*snaps at a dragonfly hovering overhead*", 5.0),
        ("*tucks beak under wing for a float-nap*", 20.0),
        ("*pushes through reeds making rustling sounds*", 8.0),
        ("*dips head underwater and wiggles tail in the air*", 6.0),
        ("*watches tadpoles swim by*", 9.0),
        ("*rides a gentle ripple across the pond*", 10.0),
        ("*investigates a frog sitting on a rock*", 7.0),
        ("*shakes water off feathers dramatically*", 5.0),
        ("*pecks at something shiny under the water*", 8.0),
        ("*floats backward accidentally*", 6.0),
        ("*chatters at a passing moorhen*", 7.0),
        ("*digs beak into the muddy bank*", 8.0),
        ("*stands on one leg at the water's edge*", 12.0),
        ("*watches the clouds reflected in the pond*", 11.0),
        ("*makes tiny waves by wiggling feet underwater*", 9.0),
        ("*discovers a snail on a reed and stares at it*", 10.0),
        ("*tries to catch a water skater... misses*", 6.0),
        ("*finds a comfortable spot between two reeds*", 14.0),
        ("*practices diving technique*", 8.0),
        ("*splashes excitedly for no apparent reason*", 7.0),
        ("*wades in the shallows, pecking at pebbles*", 10.0),
        ("*listens to the frogs croaking*", 9.0),
        ("*stretches wings out wide by the water*", 8.0),
        ("*collects a pretty pebble from the pond bed*", 7.0),
        ("*nibbles on some duckweed*", 10.0),
        ("*watches a heron in the distance warily*", 12.0),
        ("*does a little spin on the water*", 5.0),
        ("*sunbathes on the warm bank*", 18.0),
        ("*flicks water droplets off tail feathers*", 6.0),
        ("*peeks over a tussock of grass curiously*", 7.0),
        ("*chases another duck's ripple trail*", 8.0),
        ("*finds a cozy mud puddle nearby*", 10.0),
        ("*bobs head rhythmically while floating*", 9.0),
        ("*quacks softly at the setting sun reflected in the pond*", 8.0),
        ("*notices a turtle and follows it slowly*", 12.0),
        ("*rearranges reeds into a more comfortable arrangement*", 10.0),
        ("*plunges head in water and comes up with a tiny fish!*", 6.0),
        ("*fluffs up feathers and settles into the bank*", 14.0),
        ("*listens to water lapping against the rocks*", 11.0),
        ("*practices quacking at different volumes*", 8.0),
    ],

    # =========================================================================
    # FOREST — Trees, twigs, leaves, berries, mushrooms, birds
    # =========================================================================
    "forest": [
        ("*waddles through crunchy fallen leaves*", 10.0),
        ("*pecks at a mushroom growing on a log*", 8.0),
        ("*looks up at the towering trees in awe*", 9.0),
        ("*finds a stick and drags it around*", 12.0),
        ("*startles at a squirrel running past*", 5.0),
        ("*hides behind a tree trunk and peeks out*", 8.0),
        ("*sniffs at some wild berries*", 7.0),
        ("*gets tangled in a low-hanging vine*", 6.0),
        ("*listens to birdsong and tilts head*", 10.0),
        ("*waddles through a patch of ferns*", 8.0),
        ("*investigates a hollow log*", 9.0),
        ("*watches a spider spinning a web*", 11.0),
        ("*tries to climb a root and slides back*", 6.0),
        ("*finds a feather from another bird*", 7.0),
        ("*sits in a sunbeam breaking through the canopy*", 15.0),
        ("*kicks at a pinecone*", 5.0),
        ("*follows a trail of ants with great interest*", 10.0),
        ("*discovers an interesting rock under some moss*", 8.0),
        ("*ruffles feathers as a breeze rustles the trees*", 7.0),
        ("*watches leaves fall and tries to catch one*", 9.0),
        ("*pecks at tree bark looking for bugs*", 10.0),
        ("*naps in a pile of soft leaves*", 18.0),
        ("*waddles across a fallen log like a bridge*", 8.0),
        ("*startles at an owl hooting*", 5.0),
        ("*finds a patch of clover and nibbles*", 10.0),
        ("*watches a woodpecker drumming on a tree*", 9.0),
        ("*splashes in a tiny forest puddle*", 7.0),
        ("*explores a gap between tree roots*", 8.0),
        ("*gets confused by an echo of own quack*", 6.0),
        ("*discovers a cluster of wild mushrooms*", 8.0),
        ("*follows a deer trail deeper into the woods*", 12.0),
        ("*sits among the ferns and blends in... mostly*", 10.0),
        ("*examines a cobweb glistening with dew*", 9.0),
        ("*rolls in a patch of soft moss*", 8.0),
        ("*listens to the wind whistling through branches*", 11.0),
        ("*finds a hollow in a tree and peeks inside*", 7.0),
        ("*discovers a tiny stream and follows it*", 12.0),
        ("*picks up an acorn and carries it around*", 9.0),
        ("*watches a caterpillar inch along a branch*", 10.0),
        ("*makes a nest-like pile of leaves and sits in it*", 14.0),
        ("*hops over exposed tree roots*", 6.0),
        ("*spots a rabbit and freezes, watching*", 10.0),
        ("*shuffles through a pile of twigs*", 7.0),
        ("*finds a clearing and does a happy waddle*", 8.0),
        ("*pecks at a bracket fungus on a stump*", 7.0),
        ("*chases a butterfly through the undergrowth*", 9.0),
        ("*sits on a tree stump like a tiny throne*", 12.0),
        ("*watches dappled sunlight dance on the forest floor*", 11.0),
        ("*discovers old bird's nest in a bush*", 8.0),
        ("*nibbles on some wild sorrel leaves*", 7.0),
    ],

    # =========================================================================
    # MEADOW — Flowers, grass, seeds, insects, butterflies
    # =========================================================================
    "meadow": [
        ("*rolls in a patch of wildflowers*", 10.0),
        ("*chases a butterfly across the meadow*", 9.0),
        ("*sniffs at a daisy and sneezes*", 5.0),
        ("*lies flat in the tall grass and disappears*", 14.0),
        ("*watches bees buzzing between flowers*", 10.0),
        ("*picks up a dandelion seed puff and blows it*", 6.0),
        ("*waddles through a field of clover*", 10.0),
        ("*finds a patch of warm grass and sunbathes*", 18.0),
        ("*chases a grasshopper through the meadow*", 8.0),
        ("*gets pollen on beak from sniffing flowers*", 6.0),
        ("*stretches out flat in the sunshine*", 15.0),
        ("*watches clouds and imagines bread shapes*", 12.0),
        ("*discovers a ladybug and watches it climb a stem*", 9.0),
        ("*runs through the tall grass making mini trails*", 10.0),
        ("*finds a nice spot and flops down*", 14.0),
        ("*pecks at seeds scattered in the grass*", 8.0),
        ("*watches a kite being flown in the distance*", 10.0),
        ("*practices camouflage in a flower patch*", 12.0),
        ("*chases own shadow across the meadow*", 7.0),
        ("*collects tiny wildflower petals*", 9.0),
        ("*watches a field mouse dart through the grass*", 8.0),
        ("*does a big stretch in the open space*", 6.0),
        ("*flaps wings and makes dandelion seeds fly everywhere*", 7.0),
        ("*finds a warm flat rock and sits on it*", 14.0),
        ("*listens to crickets chirping*", 10.0),
        ("*follows a trail of wildflowers like a path*", 9.0),
        ("*discovers a hidden rabbit hole*", 7.0),
        ("*pecks curiously at a mushroom ring*", 8.0),
        ("*stands very still pretending to be a flower*", 10.0),
        ("*watches a hawk circling high above and crouches*", 8.0),
        ("*wades through buttercups up to chest height*", 10.0),
        ("*spotted a cricket and pounces... misses*", 6.0),
        ("*does a victory waddle through the flowers*", 8.0),
        ("*nibbles on sweet clover*", 9.0),
        ("*plays peekaboo with a field vole*", 8.0),
        ("*watches seeds blowing on the breeze*", 10.0),
        ("*makes a little bed in the grass and naps*", 16.0),
        ("*finds a feather caught in a thistle*", 7.0),
        ("*investigates a strange buzzing in the grass*", 8.0),
        ("*discovers poppy flowers and admires the color*", 9.0),
        ("*races a bumblebee to the next flower... loses*", 7.0),
        ("*collects grass blades and makes a tiny pile*", 10.0),
        ("*watches butterflies dance in the warm air*", 12.0),
        ("*finds an ant hill and watches the busy ants*", 11.0),
        ("*takes a dust bath in a dry patch*", 8.0),
        ("*quacks at a scarecrow in the distance*", 7.0),
        ("*gets distracted by absolutely everything*", 10.0),
        ("*sits among the wildflowers looking very picturesque*", 12.0),
        ("*tries to eat a buttercup... decides against it*", 6.0),
        ("*runs in circles through the meadow for pure joy*", 8.0),
    ],

    # =========================================================================
    # RIVERSIDE — Pebbles, shells, clay, driftwood, flowing water
    # =========================================================================
    "riverside": [
        ("*wades in the shallow river current*", 10.0),
        ("*watches sticks float downstream*", 9.0),
        ("*pecks at smooth river pebbles*", 7.0),
        ("*sits on a rock in the middle of the stream*", 12.0),
        ("*tries to swim upstream... gets pushed back*", 8.0),
        ("*digs in the sandy riverbank*", 9.0),
        ("*watches crayfish hiding under rocks*", 10.0),
        ("*finds a pretty shell and picks it up*", 7.0),
        ("*splashes in the rushing water*", 8.0),
        ("*discovers a piece of driftwood and stands on it*", 9.0),
        ("*watches fish jumping in the current*", 10.0),
        ("*pecks at clay along the bank*", 8.0),
        ("*floats downstream a little then paddles back*", 12.0),
        ("*finds a quiet eddy and rests in it*", 14.0),
        ("*collects smooth pebbles from the riverbed*", 9.0),
        ("*watches a kingfisher dive into the water*", 8.0),
        ("*plays with river foam bubbles*", 7.0),
        ("*walks along stepping stones carefully*", 10.0),
        ("*dips feet in the cold river and shivers*", 6.0),
        ("*investigates what's under a river rock*", 8.0),
        ("*watches dragonflies zip over the water*", 9.0),
        ("*finds a sandy shallow and makes a little pool*", 10.0),
        ("*listens to the river gurgling over rocks*", 11.0),
        ("*tries to catch a leaf floating past*", 6.0),
        ("*wades through pebbles making clacking sounds*", 8.0),
        ("*discovers water-smoothed glass among the stones*", 7.0),
        ("*practices diving in a deep pool*", 10.0),
        ("*sits on the bank watching the river flow*", 14.0),
        ("*follows the river current with eyes*", 9.0),
        ("*pecks at a water snail on a rock*", 7.0),
        ("*shakes off after wading through rapids*", 5.0),
        ("*explores under a small waterfall*", 10.0),
        ("*collects driftwood pieces into a tiny pile*", 9.0),
        ("*watches water striders dance on the surface*", 10.0),
        ("*digs a channel in the mud connecting two puddles*", 12.0),
        ("*basks on a warm river rock*", 15.0),
        ("*chases minnows in the shallows*", 8.0),
        ("*investigates interesting marks in the wet mud*", 7.0),
        ("*splashes through a shallow crossing*", 6.0),
        ("*finds a bend in the river and explores it*", 10.0),
        ("*watches the sunset reflected in the river*", 12.0),
        ("*stacks tiny pebbles into a little tower*", 10.0),
        ("*dips bill into the flowing water and drinks*", 6.0),
        ("*hops along the mossy riverside rocks*", 8.0),
        ("*discovers an old log Bridge and crosses it nervously*", 10.0),
        ("*watches bubbles rise from the river bottom*", 8.0),
        ("*plays in the spray from a small waterfall*", 9.0),
        ("*naps on a warm sandbar*", 16.0),
        ("*examines fresh animal tracks in the mud*", 8.0),
        ("*paddles against the current for exercise*", 10.0),
    ],

    # =========================================================================
    # GARDEN — Vegetables, flowers, string, fabric, vegetable plots
    # =========================================================================
    "garden": [
        ("*pecks at a tomato growing on a vine*", 8.0),
        ("*waddles between rows of vegetables*", 10.0),
        ("*investigates the garden hose suspiciously*", 7.0),
        ("*finds a worm in the freshly turned soil*", 6.0),
        ("*sits next to a garden gnome and mimics its pose*", 12.0),
        ("*nibbles on lettuce leaves*", 9.0),
        ("*watches a snail crawl across a cabbage*", 10.0),
        ("*inspects sunflowers that are taller than cheese*", 8.0),
        ("*digs in the compost heap*", 9.0),
        ("*gets tangled in garden netting*", 7.0),
        ("*discovers a strawberry and pecks at it eagerly*", 6.0),
        ("*sits in the shade of a huge pumpkin*", 12.0),
        ("*watches a robin pull worms from the lawn*", 9.0),
        ("*waddles along the garden path*", 8.0),
        ("*naps under a rhubarb leaf umbrella*", 16.0),
        ("*examines the watering can with great curiosity*", 8.0),
        ("*plays with a garden sprinkler*", 10.0),
        ("*pecks at fallen apples under a tree*", 7.0),
        ("*hides among the bean poles*", 10.0),
        ("*discovers a slug and isn't sure what to think*", 8.0),
        ("*walks along the top of a garden wall*", 9.0),
        ("*splashes in a bird bath in the garden*", 8.0),
        ("*watches herbs swaying in the breeze*", 9.0),
        ("*finds string on the ground and pulls it*", 7.0),
        ("*investigates a flower pot and tips it over*", 6.0),
        ("*sits between rows of carrots looking content*", 12.0),
        ("*watches a bee enter a bee hotel*", 8.0),
        ("*peeks inside the garden shed*", 7.0),
        ("*waddles through the herb garden — smells nice!*", 9.0),
        ("*discovers a patch of mint and nibbles*", 8.0),
        ("*plays in a pile of freshly pulled weeds*", 7.0),
        ("*naps in a wheelbarrow*", 14.0),
        ("*chases a cabbage white butterfly*", 8.0),
        ("*pecks at seeds in a bird feeder*", 9.0),
        ("*explores the greenhouse and steams up*", 10.0),
        ("*finds a terracotta pot saucer to splash in*", 8.0),
        ("*admires the roses from a safe distance (thorns!)*", 9.0),
        ("*kicks a small garden stone around*", 7.0),
        ("*watches a toad hop across the path*", 8.0),
        ("*finds fabric scraps near the compost and plays*", 9.0),
        ("*sits on a bag of potting soil*", 10.0),
        ("*pecks at a scarecrow's button nose*", 6.0),
        ("*waddles through the lavender patch and smells lovely*", 10.0),
        ("*investigates wind chimes hanging from a post*", 8.0),
        ("*discovers a tiny frog hiding in the lettuce*", 7.0),
        ("*lounges in a warm patch between the raised beds*", 14.0),
        ("*watches rain collect in a bucket*", 9.0),
        ("*finds a caterpillar on a leaf and watches it munch*", 10.0),
        ("*pecks at gravel on the garden path*", 7.0),
        ("*stands proudly in the vegetable patch like a scarecrow*", 10.0),
    ],

    # =========================================================================
    # MOUNTAINS — Rocks, crystals, moss, pine, altitude, eagles
    # =========================================================================
    "mountains": [
        ("*scrambles up a rocky slope*", 10.0),
        ("*stands on a ledge and surveys the view below*", 12.0),
        ("*pecks at lichen growing on a boulder*", 8.0),
        ("*shivers in the mountain breeze*", 6.0),
        ("*discovers a shiny crystal in a rock crack*", 8.0),
        ("*slides down a smooth rock surface — wheee!*", 7.0),
        ("*huddles behind a rock for shelter from the wind*", 10.0),
        ("*watches an eagle soar overhead nervously*", 9.0),
        ("*investigates a tiny mountain stream*", 8.0),
        ("*finds moss growing between rocks and feels it*", 7.0),
        ("*quacks and hears the echo bounce off cliffs*", 8.0),
        ("*climbs higher and looks back proudly*", 10.0),
        ("*discovers a mountain goat trail and follows it*", 12.0),
        ("*rests in a sheltered rocky outcrop*", 14.0),
        ("*pecks at pine nuts under a twisted pine tree*", 9.0),
        ("*watches clouds drift below the mountain peak*", 11.0),
        ("*finds a geode and taps it curiously*", 8.0),
        ("*naps in a warm sunny spot between rocks*", 16.0),
        ("*explores a small mountain cave entrance*", 10.0),
        ("*collects interesting pebbles from the trail*", 9.0),
        ("*watches a marmot pop up from its burrow*", 8.0),
        ("*sits on a flat rock and enjoys the vista*", 14.0),
        ("*gets buffeted by a sudden gust of wind*", 5.0),
        ("*finds a snow patch and touches it with beak*", 7.0),
        ("*walks along a narrow ridge carefully*", 10.0),
        ("*discovers wild mountain herbs and sniffs them*", 8.0),
        ("*watches a waterfall cascade down the mountain*", 12.0),
        ("*picks at berries growing on a mountain bush*", 9.0),
        ("*stacks stones into a tiny cairn*", 10.0),
        ("*yodels... wait, ducks can't yodel... QUACK!*", 6.0),
        ("*watches the mist swirl through the peaks*", 11.0),
        ("*scrambles over loose scree and stumbles*", 7.0),
        ("*finds a protected grove of alpine flowers*", 9.0),
        ("*balances on a pointy rock like a mountain climber*", 8.0),
        ("*watches snow melt trickle down the mountainside*", 10.0),
        ("*explores a rocky overhang for shelter*", 9.0),
        ("*pecks at quartz crystals poking from stone*", 8.0),
        ("*does a proud pose at the summit*", 7.0),
        ("*watches the sunrise paint the mountain orange*", 12.0),
        ("*finds a pine cone and rolls it downhill*", 7.0),
        ("*discovers fossils in the exposed rock face*", 10.0),
        ("*waddles through a patch of mountain wildflowers*", 9.0),
        ("*listens to the wind howling through a gap*", 8.0),
        ("*spots a mountain stream and splashes in*", 8.0),
        ("*takes shelter under a overhanging rock*", 12.0),
        ("*examines interesting layers in a cliff face*", 9.0),
        ("*watches ravens playing in the thermals*", 10.0),
        ("*collects pine needles for... reasons*", 7.0),
        ("*sits on the highest rock and feels majestic*", 12.0),
        ("*investigates a mysterious mountain cave echo*", 10.0),
    ],

    # =========================================================================
    # BEACH — Sand, shells, seaweed, glass, waves, crabs, seagulls
    # =========================================================================
    "beach": [
        ("*waddles along the shoreline*", 10.0),
        ("*digs in the wet sand with beak*", 8.0),
        ("*watches waves crash and backs away nervously*", 7.0),
        ("*finds a perfect seashell*", 6.0),
        ("*splashes in a rock pool*", 9.0),
        ("*chases a crab sideways... the crab is faster*", 8.0),
        ("*sits on the sand and watches the tide*", 12.0),
        ("*collects sea glass from the tideline*", 9.0),
        ("*pecks at a strand of seaweed*", 7.0),
        ("*makes footprints in the wet sand*", 8.0),
        ("*watches a hermit crab change shells*", 10.0),
        ("*stands at the water's edge as waves wash over feet*", 9.0),
        ("*builds a tiny sand castle... it collapses*", 10.0),
        ("*discovers a starfish in a rock pool*", 8.0),
        ("*runs away from a wave then runs back*", 7.0),
        ("*sunbathes on warm sand*", 18.0),
        ("*finds a piece of driftwood shaped like a boat*", 8.0),
        ("*watches seagulls fighting over chips*", 9.0),
        ("*digs a hole in the sand and sits in it*", 10.0),
        ("*examines a jellyfish washed up on shore carefully*", 8.0),
        ("*races the waves along the beach*", 9.0),
        ("*finds a tide pool full of tiny fish*", 10.0),
        ("*collects shells along the waterline*", 9.0),
        ("*watches a boat on the horizon*", 11.0),
        ("*tries to eat some seaweed... salty!*", 6.0),
        ("*waddles through the dunes*", 8.0),
        ("*plays with a beach ball left behind*", 9.0),
        ("*watches a sandpiper run along the shore*", 8.0),
        ("*discovers a message in a bottle!*", 7.0),
        ("*buries feet in warm sand*", 10.0),
        ("*explores a barnacle-covered rock*", 8.0),
        ("*naps in the shade of a sand dune*", 16.0),
        ("*watches the sunset over the ocean*", 12.0),
        ("*pecks at a coconut washed ashore*", 7.0),
        ("*splashes joyfully in the shallows*", 9.0),
        ("*finds a sand dollar and carries it carefully*", 8.0),
        ("*listens to the sound of waves crashing*", 11.0),
        ("*investigates seaweed-covered rocks*", 8.0),
        ("*does a happy dance on the hot sand*", 6.0),
        ("*watches pelicans dive into the sea*", 10.0),
        ("*writes name in the sand with beak*", 9.0),
        ("*builds a little pebble line along the shore*", 10.0),
        ("*discovers a tiny crab hiding under seaweed*", 7.0),
        ("*paddles in a warm shallow pool*", 10.0),
        ("*gets spooked by a wave and runs up the beach*", 5.0),
        ("*examines interesting patterns in the sand*", 8.0),
        ("*watches a lighthouse in the distance*", 10.0),
        ("*finds a smooth pebble perfect for skipping*", 7.0),
        ("*chases foam left behind by a receding wave*", 7.0),
        ("*sits on a rock and lets the breeze ruffle feathers*", 12.0),
    ],

    # =========================================================================
    # SWAMP — Murky water, fireflies, bog plants, mist, mysterious
    # =========================================================================
    "swamp": [
        ("*wades through murky water cautiously*", 10.0),
        ("*watches fireflies blink in the gloom*", 12.0),
        ("*pecks at a mushroom growing on a rotting stump*", 8.0),
        ("*gets stuck in the mud and wiggles free*", 7.0),
        ("*listens to mysterious croaking sounds*", 9.0),
        ("*explores between cypress tree roots*", 10.0),
        ("*watches mist curl around the trees*", 11.0),
        ("*finds a glowing fungus and stares at it*", 8.0),
        ("*jumps at own reflection in dark water*", 5.0),
        ("*investigates a bubbling patch of swamp*", 8.0),
        ("*discovers an old tree with a face-like pattern*", 9.0),
        ("*pushes through hanging moss curtains*", 7.0),
        ("*sits on a floating log and drifts slowly*", 14.0),
        ("*watches a bullfrog sitting on a lily pad*", 10.0),
        ("*finds bog berries and inspects them carefully*", 8.0),
        ("*gets spooked by a heron appearing from the fog*", 6.0),
        ("*splashes through shallow muddy water*", 8.0),
        ("*discovers strange tracks in the mud*", 9.0),
        ("*watches water bubbles rise from the swamp bed*", 10.0),
        ("*navigates between tufts of marsh grass*", 8.0),
        ("*pecks at a carnivorous plant... carefully*", 7.0),
        ("*finds a dry hummock and rests on it*", 12.0),
        ("*watches a snake slither through the water and freezes*", 8.0),
        ("*listens to eerie sounds in the distance*", 10.0),
        ("*examines a turtle sunning on a log*", 9.0),
        ("*squelches through the softest mud*", 7.0),
        ("*discovers a hidden pool of clear water*", 8.0),
        ("*watches dragonflies hover over the swamp*", 10.0),
        ("*naps on a tuft of dry swamp grass*", 14.0),
        ("*investigates a hollow tree stump full of water*", 8.0),
        ("*follows wisps of mist through the trees*", 10.0),
        ("*finds an interesting bone and inspects it*", 7.0),
        ("*hops between dry patches to avoid the mud*", 8.0),
        ("*watches an alligator-shaped log... is it a log?*", 9.0),
        ("*collects unusual swamp pebbles*", 8.0),
        ("*spots rare orchids growing on a tree*", 9.0),
        ("*gets briefly lost in the fog then finds the path*", 10.0),
        ("*watches pitcher plants collecting flies*", 10.0),
        ("*discovers a tiny island of moss*", 7.0),
        ("*listens to the chorus of frogs at dusk*", 12.0),
        ("*explores an old wooden boardwalk*", 9.0),
        ("*finds something shiny in the muck!*", 7.0),
        ("*watches an egret fishing in the shallows*", 10.0),
        ("*carefully crosses a patch of quicksand-like mud*", 8.0),
        ("*sits on a root and watches fireflies dance*", 14.0),
        ("*pecks at cattails by the water's edge*", 7.0),
        ("*watches a water moccasin from a very safe distance*", 9.0),
        ("*discovers a crystal-clear spring bubbling up*", 8.0),
        ("*makes squelching noises in the mud on purpose*", 6.0),
        ("*navigates through a curtain of Spanish moss*", 9.0),
    ],

    # =========================================================================
    # URBAN — City park, bread crumbs, coins, benches, humans
    # =========================================================================
    "urban": [
        ("*waddles across a park bench*", 8.0),
        ("*pecks at bread crumbs on the path*", 7.0),
        ("*watches humans walking their dogs*", 10.0),
        ("*finds a lost coin on the pavement!*", 6.0),
        ("*sits by the park fountain*", 12.0),
        ("*chases a pigeon away from the bread*", 7.0),
        ("*investigates a discarded crisp packet*", 8.0),
        ("*waddles across a pedestrian crossing*", 9.0),
        ("*sits on a park bench like a tiny person*", 12.0),
        ("*watches a busker playing music and bobs head*", 10.0),
        ("*finds chips on the ground and celebrates*", 7.0),
        ("*gets confused by its reflection in a shop window*", 8.0),
        ("*watches children on the playground swings*", 10.0),
        ("*explores under a park bridge*", 9.0),
        ("*splashes in the park fountain*", 10.0),
        ("*pecks at a dropped ice cream... score!*", 7.0),
        ("*watches a street performer and quacks along*", 9.0),
        ("*naps on a warm manhole cover*", 14.0),
        ("*waddles through the farmer's market*", 10.0),
        ("*finds a bottle cap and plays with it*", 7.0),
        ("*watches cars go by from the park*", 9.0),
        ("*explores a drain grate with great interest*", 8.0),
        ("*steals a bit of sandwich from an unattended lunch*", 6.0),
        ("*sits in a planter box among the flowers*", 10.0),
        ("*watches a cyclist zoom past and ruffles feathers*", 6.0),
        ("*discovers a puddle and splashes in it*", 8.0),
        ("*follows a human hoping for food*", 10.0),
        ("*inspects a statue in the park*", 9.0),
        ("*waddles through the park gate like it owns the place*", 8.0),
        ("*pecks at a shiny gum wrapper*", 6.0),
        ("*listens to church bells in the distance*", 9.0),
        ("*finds a warm heating vent and sits on it*", 14.0),
        ("*watches pigeons with mild disdain*", 8.0),
        ("*explores around a lamppost*", 7.0),
        ("*spots a food truck and waddles toward it hopefully*", 10.0),
        ("*sits in a puddle after the sprinklers ran*", 9.0),
        ("*watches a kite flying over the park*", 10.0),
        ("*discovers a playground and tries the slide*", 8.0),
        ("*naps under a park bench in the shade*", 16.0),
        ("*pecks at moss growing between paving stones*", 7.0),
        ("*watches a dog and stays very still*", 8.0),
        ("*waddles around the park lake importantly*", 10.0),
        ("*finds a ribbon caught on a fence*", 7.0),
        ("*sits on the park steps and people-watches*", 12.0),
        ("*investigates a candy wrapper blowing in the wind*", 6.0),
        ("*splashes in sprinkler spray*", 9.0),
        ("*examines a park sign like it can read*", 8.0),
        ("*takes shelter under an awning*", 10.0),
        ("*watches a train rumble past in the distance*", 9.0),
        ("*sits in a flower bed and looks decorative*", 12.0),
    ],
}
