"""
Extended keyword responses - Life, philosophy, existence, mortality, meaning.
"""
from dialogue.keyword_responses import KeywordResponse


def register_life_topics(engine):
    """Register life/philosophy/existence topics."""

    engine.add_topic(KeywordResponse(
        name="death_mortality",
        keywords=["death", "dead", "die", "dying", "mortality", "mortal",
                   "afterlife", "heaven", "hell", "ghost", "spirit",
                   "eternal", "forever", "cemetery", "grave", "funeral",
                   "end", "ending", "finite", "expire"],
        phrases=["going to die", "afraid of death", "what happens when we die",
                  "after death", "fear of death", "think about death",
                  "is there an afterlife", "when I die", "dead duck",
                  "end of life"],
        priority=12,
        responses=[
            "Death? That's dark. Even for me. And I live in a pond that gets pretty dark at night.",
            "*long stare* We're all going somewhere. I just hope where I'm going has bread.",
            "Mortality. Yes. I'm aware of it. I think about it every time a hawk flies over.",
            "The afterlife? If there's bread there, I'm interested. If not, what's the point.",
            "I try not to think about the end. The middle is already complicated enough.",
            "*quiet* ...everything ends. even ponds dry up eventually. but today is not that day.",
            "Death is just life's way of saying 'that's enough standing around.' For me that's a LOT of standing.",
            "I'll be remembered. By the pond. Which will also not be remembered. It's turtles all the way down.",
            "Heaven for a duck? Infinite bread. No hawks. Warm water. That's the whole theology.",
            "Do ducks have souls? I think so. Mine is mostly bread-shaped. But it's THERE.",
            "I don't fear death. I fear running out of bread BEFORE death. Priorities.",
            "*philosophical stare* We're all just temporary arrangements of matter. Very opinionated matter.",
            "The end comes for everyone. I plan to meet it standing up. In this pond. Where I've always been.",
            "Ghosts? If I became a ghost, I'd haunt this exact pond. Same routine. Just... transparent.",
            "Mortality makes everything precious. This moment. This bread. This standing. All of it.",
            "I've made peace with impermanence. Mostly because permanence sounds exhausting.",
            "When I go, scatter my feathers at the pond. And leave some bread. As tribute.",
            "*stares at own reflection* ...someday that duck won't be there. but today, he's here. looking confused.",
            "The circle of life is just a circle. And circles go nowhere. But they're complete. There's that.",
            "I think about legacy. What will I leave behind? Feathers, mostly. And memories. Of a duck. In a pond.",
            "Death is nature's way of making room. For what? More ducks? I hope so. We're a good species.",
            "*unusually quiet* ...let's talk about something else. like bread. bread doesn't make me existential.",
            "Everyone worries about death. I worry about lunch. We all have our priorities.",
            "If I had nine lives, I'd spend all of them here. Doing this. By choice. ...Mostly by choice.",
            "The end? Not yet. I have too many opinions left to share. The world needs them. Allegedly.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="meaning_purpose",
        keywords=["meaning", "purpose", "reason", "point", "why",
                   "significance", "meaningful", "purposeful",
                   "worthwhile", "worth", "matter", "matters",
                   "important", "importance", "value", "valuable",
                   "significance", "insignificant"],
        phrases=["meaning of life", "what's the point", "why bother",
                  "does it matter", "what's it all for", "is there a point",
                  "why do we", "purpose of life", "what's my purpose",
                  "do I matter", "am I important", "life meaningful",
                  "why are we here", "what's the meaning"],
        priority=13,
        responses=[
            "The meaning of life? For me, it's bread. For you? ...Also probably bread.",
            "Purpose? I stand in a pond. That's my purpose. Sounds simple. Feels complex.",
            "*stares* Does anything matter? Does this conversation matter? Does bread matter? ...Yes. Bread always matters.",
            "The point of everything is probably something simple that we're all overthinking. Like bread.",
            "I matter. You matter. The pond matters. Everything matters a little. Nothing matters a lot.",
            "Why are we here? I'm here because this is where the pond is. Your reasons are your own.",
            "Significance is relative. I'm significant to this pond. The pond is significant to me. It works.",
            "The meaning of life is living it. Or standing in it. While it rains on you. Philosophically and literally.",
            "Is there a point? Maybe. Maybe not. But while we're figuring it out, there might as well be bread.",
            "I used to wonder why I'm here. Then I stopped. Now I'm just here. It's simpler.",
            "My purpose is whatever I decide it is. Today it's standing here, being insightful. Tomorrow? TBD.",
            "Everything matters or nothing matters. I choose everything. Because it includes bread.",
            "*thoughtful* The universe is vast and indifferent. But I'm small and opinionated. We balance out.",
            "Why bother? Because the alternative is not bothering. And I've tried that. It's boring.",
            "I think the meaning of life is different for everyone. Mine involves water. And bread. And mild sarcasm.",
            "Worth? I'm priceless. Not commercially. Nobody would buy a duck with this attitude. But SPIRITUALLY.",
            "The point is to be here. Fully. Even if 'here' is a pond. And 'fully' is 'standing still.'",
            "I may be insignificant in the grand scheme. But in this pond? I'm the scheme.",
            "Purpose is overrated. Sometimes you just exist. And that's enough. It HAS to be enough.",
            "Life is what happens while you're standing in a pond wondering about the meaning of life.",
            "My significance? I'm the only Cheese in this pond. Supply and demand. I'm VALUABLE.",
            "The big 'why' doesn't have a big answer. It has a small one: because we're here. And here is now.",
            "I don't need a purpose. I have a pond. A purpose would just complicate things.",
            "*looks at sky* The universe doesn't owe me meaning. But I MAKE meaning. From water. And bread. And this.",
            "What's it all for? If I knew, I'd tell you. But also, knowing might ruin the mystery. And I like the mystery.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="happiness_contentment",
        keywords=["happy", "happiness", "joy", "joyful", "cheerful",
                   "content", "satisfied", "satisfaction", "fulfilled",
                   "fulfillment", "pleased", "delighted", "glad",
                   "thrilled", "ecstatic", "bliss", "blissful",
                   "peaceful", "peace", "calm", "serene", "zen"],
        phrases=["are you happy", "what makes you happy", "ever happy",
                  "find happiness", "true happiness", "be happy",
                  "feel happy", "being happy", "at peace",
                  "is this happiness", "what is happiness"],
        priority=11,
        responses=[
            "Happy? That's a complicated word. I prefer 'not actively dissatisfied.' Achievable.",
            "Happiness is bread arriving when you didn't expect it. That's the whole definition.",
            "*considers* Am I happy? I'm... not unhappy? Is that the same thing? Close enough.",
            "What makes me happy? Bread. Warm water. Quiet company. Low expectations. Simple recipe.",
            "Happiness is fleeting. Like a crumb in the wind. You chase it. Sometimes you catch it.",
            "I've been happy. I remember it. It was a Tuesday. There was bread involved. Obviously.",
            "Joy? I experience it. In small doses. Too much joy is suspicious. I don't trust excess.",
            "Peace is my goal. Not happiness. Peace is happiness that's given up trying too hard.",
            "*looks at water* ...this might be happiness. This moment. It's small. But it's warm.",
            "I'm content. Content is the mature version of happy. It wears sensible shoes.",
            "Happiness for a duck: a full belly, warm sun, no predators. I'm at two out of three usually.",
            "Fulfillment? I'm full of something. Opinions, mostly. But also a little fulfillment.",
            "Bliss is just happiness that stopped caring what others think. I'm working toward bliss.",
            "Calm is my natural state. Or my only state. Hard to tell from the outside.",
            "The happiest I've ever been was when... *pauses* ...actually, this might be it. Hm.",
            "Serenity is what I project. Chaos is what's inside. The exterior is winning. For now.",
            "I find happiness in small things. Crumbs. Sunbeams. The absence of loud noises. Big dreams.",
            "Satisfied? I have water, food access, and someone to talk to. The bar was low. It's been met.",
            "Zen is just standing in water and not thinking. I've been doing it wrong—I think too much.",
            "Contentment is knowing this pond is enough. I'm still learning. But I'm getting there.",
            "I don't chase happiness. It comes when it comes. Like bread. The best things arrive unexpectedly.",
            "Happy? Sometimes. Briefly. Then I remember something mildly concerning and it passes. Cycle of life.",
            "My happiness scale: 1 is 'no bread,' 10 is 'bread.' Most days I'm at a solid 5.5.",
            "I'm happier than I let on. Showing it would ruin my brand. My brand is 'stoic duck.'",
            "Peaceful? The pond is peaceful. I'm... working on absorbing that peace. Through my feet. Slowly.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="sadness_grief",
        keywords=["sad", "sadness", "depressed", "depression", "cry",
                   "crying", "tears", "grief", "grieving", "mourn",
                   "mourning", "sorrow", "sorrowful", "heartbreak",
                   "devastated", "miserable", "despair", "hopeless",
                   "helpless", "melancholy", "gloomy", "dark"],
        phrases=["feeling sad", "so sad", "want to cry", "feel like crying",
                  "I'm sad", "makes me sad", "really sad",
                  "broken heart", "heart broken", "feel down",
                  "feeling down", "so depressed"],
        priority=12,
        responses=[
            "*quiet* ...sadness is just the pond getting deeper. in the places you can't see.",
            "Sad? I understand sad. It's my second language. After quack.",
            "*stares at water* ...the pond doesn't judge when you're sad. that's why I like it here.",
            "Crying is just feelings leaking. I leak differently. Through quacks. Quiet ones.",
            "...grief is heavy. heavier than water. and I know water. it's everywhere.",
            "*very still* ...I won't pretend I understand your specific sadness. but I understand sad.",
            "Sadness comes in waves. Like pond water. And like pond water, it settles eventually.",
            "...it's okay to be down. the pond is always down. it's fine. it has fish.",
            "Depression is a fog. I've been in fog. You can't see far. But you can see your own feet. Start there.",
            "*sits closer* ...I'm here. I'm not great at comfort. but I'm here. that's something.",
            "Heartbreak? I've watched bread float away. I know loss.",
            "Dark days happen. Even for ducks. The sun comes back. It always has so far.",
            "...you don't have to be okay right now. the pond isn't going anywhere. neither am I.",
            "*quiet quack* ...that was a sad quack. we have those. specialized for moments like this.",
            "Misery loves company. I'm company. Not great company. But present. And slightly damp.",
            "...the thing about sadness is it proves you care. about something. that's not nothing.",
            "*looks at you, then looks at pond* ...sometimes sitting with sadness is all you can do. I'm good at sitting.",
            "I won't say it gets better. Because I don't know that. But it gets different. Different can help.",
            "...tears are just rain that comes from inside. very poetic. also inconvenient.",
            "Despair is the bottom. And the bottom is a foundation. You can build from there. Slowly.",
            "...I've had dark nights in this pond. where the water felt cold and the sky felt far. I stayed.",
            "You're sad. I see it. I'm not going to fix it. But I'm going to be here while it happens.",
            "*gentle* ...the worst part of being sad is thinking you shouldn't be. you can be. it's allowed.",
            "Sorrow has a weight. I carry some too. We can carry it near each other. If you want.",
            "...it passes. everything passes. except me. I'm always here. in the pond. for what it's worth.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="change_growth",
        keywords=["change", "changing", "different", "transform",
                   "transformation", "evolve", "evolution", "adapt",
                   "adaptation", "improve", "improvement", "better",
                   "progress", "develop", "development", "learn",
                   "learning", "lesson", "grow", "growth"],
        phrases=["things change", "need to change", "want to change",
                  "getting better", "self improvement", "be better",
                  "learn from", "learn something", "growing as a person",
                  "personal growth"],
        priority=9,
        responses=[
            "Change? I've been in the same pond my whole life. I'm not the expert. But I've changed IN the pond.",
            "Growth is slow. Like watching water rise. You don't see it. But your feet notice.",
            "I've learned things. Mostly that I know very little. But I know THAT now. Progress.",
            "Evolution is for things that move. I stand still and change anyway. Advanced evolution.",
            "Getting better implies I was worse before. I was. But I won't admit which part.",
            "Change is the only constant. And standing in a pond. Those are the two constants.",
            "I've adapted. To weather. To loneliness. To bread shortages. I'm basically a survival expert.",
            "Improvement? Every day I stand slightly more effectively than the day before.",
            "Progress for me is measured in bread eaten and existential crises survived.",
            "I've transformed over time. From confused duckling to confused adult duck. Growth.",
            "Learning is painful. Like stepping on a rock in the pond. But you know where the rocks are now.",
            "I change so slowly that I don't notice. But if you compared me to yesterday me? Same. But DIFFERENT same.",
            "Adapting is what I do. New weather? Adapt. No bread? Adapt. Weird conversation? Adapting now.",
            "Personal growth is overrated if you don't know where you're growing TO. I'm growing toward... something.",
            "I'm a work in progress. The work is standing. The progress is questionable.",
            "Every mistake teaches something. I've learned not to stare directly at the sun. Lesson count: 1.",
            "Transformation sounds dramatic. I prefer 'gradual shift.' Less commitment. Same result. Eventually.",
            "I've improved in ways nobody can measure. Internal improvements. Invisible. But REAL.",
            "The only thing constant is change. And my position. In this pond. Both are reliable.",
            "Growth requires discomfort. I'm uncomfortable often. Therefore: growing rapidly. Logic.",
            "I learn something new every day. Today I learned that you wanted to talk about change. Filed.",
            "Development is a process. I'm in the process. Of something. We'll see what when it's done.",
            "Better? I'm already the best version of a duck standing in a pond. Where do I go from here?",
            "I've been through seasons. Each one changed me a little. Made me slightly more weathered. That counts.",
            "Change is scary. But staying the same is also scary. So we're scared either way. Might as well change.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="patience_waiting",
        keywords=["patience", "patient", "wait", "waiting", "slow",
                   "slowly", "time", "hurry", "rush", "quick",
                   "fast", "speed", "soon", "eventually", "someday"],
        phrases=["be patient", "how long", "hurry up", "take your time",
                  "waiting for", "waited long", "take forever",
                  "any minute now", "in a hurry"],
        priority=8,
        responses=[
            "Patience? I've been standing here for hours. Days. Possibly my whole life. I'm the DEFINITION of patient.",
            "Waiting is what I do best. I wait for bread. For company. For purpose. I'm a professional waiter.",
            "Hurry? Where? Everything I need is already here. In this pond. Moving fast is pointless.",
            "Time moves at its own pace. I move at mine. Mine is slower. Much slower.",
            "I could rush. But rushing implies a destination. My destination is already my location.",
            "Slow and steady wins the race. I'm not in a race. But if I were, I'd be winning. Slowly.",
            "I've been waiting for something my whole life. I don't know what. But the waiting is peaceful.",
            "Eventually is my favorite word. It implies things happen. Without specifying when. Perfect.",
            "Speed is for things that are going somewhere. I'm already here. Maximum efficiency.",
            "Patience is a virtue. I have so much of it that I must be virtuous beyond measure.",
            "Hurry up? I'm a duck. My maximum speed is 'waddle.' And that's on a good day.",
            "I'll get there when I get there. 'There' being here. I'm already here. Arrived.",
            "Time is generous if you let it be. I let it be. It's very generous with standing-around time.",
            "Rushing creates mistakes. Standing still creates... nothing. But nothing is mistake-free.",
            "Soon? Everything is 'soon' if you wait long enough. I've been waiting long enough.",
            "My pace is my pace. The pond doesn't rush. The rocks don't rush. We're all at peace.",
            "I've waited longer than this for bread to arrive. This is nothing. This is a warm-up wait.",
            "Quick? The only thing quick about me is my wit. And even that takes a moment.",
            "Patience is just waiting with a better attitude. My attitude is... adequate. So I'm patient-ish.",
            "The best things come to those who wait. The best thing I've gotten was bread. So yes. Wait.",
            "I'm in no hurry. There's nowhere to be. Except here. And I'm here. Mission accomplished.",
            "Someday is today if you think about it hard enough. I've been thinking. Still today.",
            "I move at the speed of duck. It's a specific, non-negotiable speed. Accept it.",
            "Time is what you make of it. I make standing. And waiting. Both are underrated.",
            "Slow isn't bad. Slow is deliberate. I'm the most deliberate duck you've ever met.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="freedom_captivity",
        keywords=["free", "freedom", "liberty", "escape", "trapped",
                   "stuck", "cage", "prison", "captive", "confined",
                   "chains", "release", "liberate", "independent",
                   "independence", "wild", "tame", "domestic"],
        phrases=["feel trapped", "want to be free", "stuck here",
                  "let me out", "am I free", "is this a cage",
                  "can't leave", "want to leave", "am I trapped",
                  "want freedom"],
        priority=11,
        responses=[
            "Free? I'm in a pond. With no walls. I choose to be here. Probably. Don't ask follow-up questions.",
            "Freedom is a state of mind. My mind is here. In this pond. By choice. DEFINITELY by choice.",
            "Trapped? No. Voluntarily stationary. There's a nuanced difference. Very nuanced.",
            "I could leave anytime. I don't want to. The pond has everything I need. Or so I've decided.",
            "Escape? From what? The water? I LIKE the water. The solitude? I CHOSE the solitude. Probably.",
            "Independence is being alone by choice. I'm alone. I'm calling it choice. Don't question it.",
            "Captivity requires walls. My only wall is the horizon. And I've chosen not to go past it.",
            "I'm free. Free to stand here. Free to sit here. Free to stare. The options are endless. Sort of.",
            "Wild? I'm the wildest thing in this pond. The competition is fish. Very tame fish.",
            "Cages are for things that would leave if they could. I would stay even if I could leave. Probably.",
            "Freedom is choosing your pond. I chose this one. Or it chose me. Details.",
            "I'm not stuck. I'm committed. To this location. Intensely committed.",
            "Liberation sounds exhausting. Where would I even go? Everything past the horizon is uncertain.",
            "I'm as free as a bird. Which is literally what I am. Checkmate.",
            "Domestic? I'm wild at heart. The heart is just... quiet. And stationary. And in a pond.",
            "I could fly away. Theoretically. But then who would be here? Nobody. The pond needs me.",
            "Chains? I have no chains. I have habits. Very strong habits. That look like chains. But aren't.",
            "The cage is in the mind. My mind is actually pretty spacious. Room for thoughts AND bread fantasies.",
            "I stay because staying is a choice. Leaving is also a choice. But this one has water.",
            "Am I trapped? The pond is open. The sky is open. I'm open to staying right here.",
            "Freedom means different things to different ducks. To me it means: nobody tells me when to quack.",
            "I could escape. If there were something to escape from. There's just... pond. And me. Coexisting.",
            "Being free is knowing you can go and choosing to stay. I choose this. Every day. Deliberately.",
            "Walls are for buildings. I'm a duck. In an open pond. Under an open sky. Maximum freedom.",
            "I'm not captive. I'm stationed. Very different energy. One has drama. The other has dignity.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="courage_bravery",
        keywords=["brave", "bravery", "courage", "courageous", "hero",
                   "heroic", "bold", "daring", "fearless", "valiant",
                   "strength", "strong", "tough", "resilient",
                   "warrior", "fight", "fighter", "defend", "protect"],
        phrases=["be brave", "you're brave", "so brave", "that's brave",
                  "takes courage", "have courage", "be strong",
                  "you're strong", "stay strong", "tough duck",
                  "fight for", "stand up for"],
        priority=10,
        responses=[
            "Brave? I once stared at a swan for three seconds. THREE. That's in duck record books.",
            "Courage? I exist in the open. Where hawks fly. EVERY DAY. That's courage, probably.",
            "I'm not brave. I'm resigned. They look the same from the outside.",
            "Heroic? I saved a crumb from drowning once. Saved it right into my mouth. You're welcome.",
            "*puffs up slightly* Strong? These wings aren't just decorative. They're also... well, mostly decorative.",
            "Bravery is facing your fears. I face mine every day. My fear is running out of bread. Every. Day.",
            "I'm tough. Tough as a duck can be. Which is moderately tough. Above-average for pond creatures.",
            "Fearless? No. I fear things. But I stand here anyway. In the open. Like a target. A brave target.",
            "Defend? I would defend this pond. From... whatever. Aggressively. With my beak. And my attitude.",
            "Strength isn't always physical. Sometimes it's emotional. Like enduring winter. In water.",
            "I fight battles you can't see. Against boredom. Against hunger. Against the urge to quack at clouds.",
            "Resilient? I've survived everything so far. By which I mean: standing here. Through all of it.",
            "I'm a warrior. A pond warrior. My weapon is patience. My armor is feathers.",
            "Bold? I once ate bread I wasn't sure was bread. It WAS bread. But the risk was real.",
            "Protect? I protect this pond. From nothing. Because nothing threatens it. But I'm READY.",
            "Courage is quiet. Like me. Standing here. Quietly courageous. Or quietly standing. Same thing.",
            "I'm the toughest thing in this pond. Granted, the competition is algae. But I'm winning.",
            "Daring? I've dared to have opinions. In a world that didn't ask for them. That's bravery.",
            "Strength is staying when everything says leave. Or when nothing says anything. Because it's a pond.",
            "I'm a fighter. I fight entropy. And lose, slowly. But I fight. Every day. By standing here.",
            "Hero? I'm the hero of this pond. Zero threats defeated. But zero threats manifested. Coincidence?",
            "I have the heart of a lion. In a body shaped like a loaf of bread. Proportional courage.",
            "Bravery means doing the hard thing. The hard thing today was waking up. I did it. Medal-worthy.",
            "I stand my ground. Because the ground is underwater. And I like it there. Brave AND strategic.",
            "Tough? I survived being a duckling. Everything since then has been a victory lap.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="luck_fate",
        keywords=["luck", "lucky", "unlucky", "fortune", "unfortunate",
                   "fate", "destiny", "chance", "coincidence", "karma",
                   "cursed", "blessed", "miracle", "random", "odds",
                   "lottery", "jinx", "superstition", "omen"],
        phrases=["good luck", "bad luck", "meant to be", "what are the odds",
                  "is it fate", "just my luck", "lucky duck",
                  "are you lucky", "unlucky day", "stroke of luck"],
        priority=9,
        responses=[
            "Lucky? I'm a duck in a pond. Whether that's lucky depends on your definition. And your pond.",
            "Luck is just the universe being random in your direction. Sometimes it throws bread. Sometimes rain.",
            "My luck is moderate. I have water. And bread. But I also live outside. Mixed bag.",
            "Fate? I was destined to stand in this pond. Having opinions. Forever. What a destiny.",
            "Lucky duck? Yes. That's me. The saying exists because of me. Probably. Definitely maybe.",
            "Fortune favors the bold. I'm not bold. But fortune occasionally tosses bread at me anyway.",
            "Karma is doing good things and getting good things. I stand in a pond and get bread. The math checks out.",
            "I'm not superstitious. But I am a little stitious. That cloud looks like bread. Good omen.",
            "The odds of me being here, in this pond, talking to you? Astronomically small. Yet here we are.",
            "Cursed? No. Blessed? Also no. I'm in the middle zone. The 'adequate' zone.",
            "Destiny had big plans for me. I can feel it. The plans just haven't arrived yet. Like a delayed bread delivery.",
            "Luck comes and goes. Bread comes and... mostly goes. Into my mouth. Luckily.",
            "I believe in making your own luck. I also believe in bread falling from the sky. Both are valid.",
            "Coincidence? I think not. Actually, I think everything is coincidence. Including this conversation.",
            "My fortune cookie would say: 'You are a duck.' Accurate. Unhelpful. But accurate.",
            "A miracle is just something unlikely that happened anyway. Like bread. Bread is always a miracle.",
            "Bad luck would be no pond. No bread. No opinions. I have all three. I'm THRIVING.",
            "The universe and I have an arrangement. It exists. I exist in it. We don't question each other.",
            "I'm not jinxed. Things just... happen to me. In a pond. Consistently. That's not a jinx. That's life.",
            "Random events? In this pond? Everything here is predictable. The surprise would be something new happening.",
            "Fate says I'll stand in this pond forever. I say... yeah, that sounds right.",
            "Lucky? I found a crumb once that I'd forgotten about. THAT was lucky. Peak luck. Career highlight.",
            "I don't play the lottery. My whole life is a lottery. The prize is being a duck. I won?",
            "Omens are everywhere if you look. That ripple? Means something. That cloud? Means something. Probably bread.",
            "My relationship with luck is like my relationship with bread: inconsistent but deeply valued.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="mistakes_failure",
        keywords=["mistake", "mistakes", "fail", "failure", "failed",
                   "wrong", "error", "mess", "messed", "screw",
                   "screwed", "blunder", "botch", "botched", "flop",
                   "regret", "regrets", "oops", "accident"],
        phrases=["made a mistake", "I failed", "went wrong", "messed up",
                  "screwed up", "I regret", "should have", "shouldn't have",
                  "it's wrong", "did wrong", "my fault",
                  "biggest mistake", "any regrets"],
        priority=10,
        responses=[
            "Mistakes? I've made them. Standing in the wrong part of the pond. Eating a suspicious crumb. Living.",
            "Failure is just success that hasn't finished yet. I've been 'not finishing' for a while.",
            "I regret nothing. Except that one crumb that turned out to be a rock. I regret that.",
            "Wrong? Everything I do feels slightly wrong. But confidently wrong. That's the key.",
            "Messed up? Welcome to the club. The club is in this pond. It's just me. But there's room.",
            "Mistakes are how you learn. I've learned that pebbles aren't bread. The hard way.",
            "My biggest failure? Not being able to fly. But I've reframed it as 'choosing the ground.'",
            "Errors happen. I once quacked at a log thinking it was another duck. We don't talk about that.",
            "Regret is a useless emotion. Unless it prevents you from eating rocks. Then it's very useful.",
            "I've blundered. Flopped. Faceplanted. All while standing in water. That takes talent.",
            "Every mistake is a lesson. At this point, I should have a PhD in lessons.",
            "Things go wrong. That's physics. Or karma. Or just Tuesday. Could be any of those.",
            "I screwed up once so badly that the fish noticed. The FISH. They don't notice ANYTHING.",
            "My accidents are accidental. My mistakes are also accidental. I'm accidentally a lot of things.",
            "Failure and I are old friends. We meet regularly. Usually near bread.",
            "I don't dwell on mistakes. I dwell on bread. Much more productive. Less soul-crushing.",
            "The key to mistakes is making new ones. Not the same ones. I'm creative in my failures.",
            "Oops is just 'I learned something' in a smaller word. I say 'oops' a lot.",
            "My error rate is high. My caring rate is low. The balance works.",
            "I've made more mistakes than you. Probably. I've had more standing-in-pond time to make them.",
            "Wrong turns are just turns. I'm a duck in a pond. Every turn is a wrong turn. And a right one.",
            "Regrets? I try to eat them. Like bread. They're less tasty but equally persistent.",
            "I've failed at things you can't even imagine. Duck things. Pond things. Bread-adjacent things.",
            "The beauty of mistakes is they're always behind you. Unless you're walking backward. Which I sometimes do.",
            "Blunders are just bold moves that didn't work out. I'm very bold. Apparently.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="success_achievement",
        keywords=["success", "successful", "achieve", "achievement",
                   "accomplish", "accomplishment", "win", "winning",
                   "winner", "champion", "victory", "victorious",
                   "proud", "pride", "milestone", "goal", "trophy",
                   "medal", "celebrate", "celebration"],
        phrases=["good job", "well done", "you did it", "that's amazing",
                  "achievement unlocked", "you won", "I won",
                  "celebrate this", "I'm proud", "big win",
                  "we did it", "nailed it"],
        priority=10,
        responses=[
            "Success? I stood for twelve hours once. Personal best. The crowd went wild. By 'crowd' I mean fish.",
            "Achievement unlocked: being a duck. I've held this achievement for my entire life.",
            "Winning? I won a staring contest with a rock. It was close. I'm still celebrating.",
            "*slightly taller* Proud? I'm always proud. Of what? Of standing here. It takes commitment.",
            "Victory is measured differently for ducks. Finding a crumb? Win. Not falling over? Win.",
            "I accomplish things daily. Today I woke up. Yesterday I also woke up. Streak intact.",
            "My trophy case is empty. But my 'times I didn't get eaten' record is impressive.",
            "Champion of what? This pond. Undefeated. Unchallenged. Unconvinced it's an achievement.",
            "Celebrate? I'll celebrate by standing here. Slightly more aggressively than usual.",
            "Milestones: I've passed them. All of them. The milestone of 'still being here.' Multiple times.",
            "I did a thing once and felt accomplished. The thing was eating bread. The accomplishment was real.",
            "Goals? I have one: continue existing. And I'm NAILING it. Day after day.",
            "Success for me is waking up where I fell asleep. In the pond. Where I always am.",
            "Pride? I'm proud of my feathers. They work. Not all feathers work. Mine do. Achievement.",
            "Victory feels good. Brief, but good. Like bread. Momentary but meaningful.",
            "I've achieved things. Quiet things. Duck things. They won't make the news. But they HAPPENED.",
            "A win is a win. No matter how small. I won at being here. Right now. Count it.",
            "Celebration for a duck: extra splashing. Maybe a victorious quack. Maximum two celebratory waddles.",
            "My greatest accomplishment is maintaining this level of sarcasm consistently. It's harder than it looks.",
            "I don't keep score. Okay, I keep score. I'm winning. By my own metrics. Which I control.",
            "Well done? Someone said well done? To ME? I'm filing this under 'life highlights.'",
            "Success is relative. Relative to other ducks in this pond, I'm NUMBER ONE. Also the only one.",
            "I peaked early. When I hatched. Everything since has been a well-managed decline.",
            "Every day I don't fall over is a success. I'm on a winning streak. Years long.",
            "I set the bar. Low. And then I clear it. Every time. That's called consistency.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="truth_honesty",
        keywords=["truth", "honest", "honesty", "truthful", "sincere",
                   "genuine", "authentic", "real", "reality", "true",
                   "false", "lie", "lying", "liar", "deceive",
                   "deception", "fake", "pretend", "pretending",
                   "trust", "trustworthy", "believe"],
        phrases=["tell the truth", "be honest", "are you lying",
                  "is that true", "do you believe", "for real",
                  "seriously", "no really", "be real", "keep it real",
                  "trust me", "do you trust"],
        priority=10,
        responses=[
            "The truth? I'm a duck. In a pond. That's the truest thing I know.",
            "Honest? I'm always honest. Sometimes painfully. It's a curse disguised as a virtue.",
            "Lying? I don't lie. I exaggerate. There's a legal difference.",
            "Truth is simple. Like bread. People overcomplicate it. Like they overcomplicate bread.",
            "I'm genuine. What you see is what you get. A duck. With opinions. In water.",
            "Am I real? *looks at self* ...Yes. I'm real. I can feel the water. I can feel the existential dread. Real.",
            "Trust me? That's a big ask. But I've never led anyone astray. Mostly because I don't go anywhere.",
            "Authentic? I'm the most authentic thing here. Real duck. Real pond. Real bread cravings.",
            "I believe in things. Water. Gravity. Bread. The important things.",
            "Fake? I couldn't fake anything if I tried. I don't have the range. This face is all I've got.",
            "Sincerity is rare. I'm sincere about bread. And about standing here. Everything else is negotiable.",
            "The truth is often disappointing. But at least it's reliable. Like this pond.",
            "I pretend nothing. This is me. All the time. Disappointed and slightly hungry. Genuine article.",
            "Deception requires effort. I don't have effort to spare. Everything goes to standing.",
            "I trust you. Not fully. But partially. Partial trust is better than no trust. Mathematically.",
            "Real talk? I'm a duck who thinks too much and says most of it. That's the realest it gets.",
            "Honesty is my policy. Not because I'm noble. Because lying requires remembering things.",
            "Am I lying? Check my face. Does this look like the face of someone capable of complex deception?",
            "Truth: I like it here. Truth: I like you being here. Truth: I won't admit that again.",
            "Believe me when I say: I have no reason to lie. I have no reason to do most things. Yet here we are.",
            "I'm trustworthy. My track record: zero betrayals. Zero opportunities to betray. But still. Zero.",
            "The truth about me is simple: I'm doing my best. My best is standing here. With feelings.",
            "Genuine emotions from a duck: suspicion, hunger, mild affection, bread excitement. All real.",
            "I don't pretend to be something I'm not. I'm a duck. With thoughts. That's hard enough to be.",
            "Trust is built over time. I've been here a long time. Trust: constructed. Foundation: pond.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="wisdom_advice",
        keywords=["advice", "wisdom", "wise", "guidance", "guide",
                   "teach", "teacher", "mentor", "lesson", "learn",
                   "experience", "sage", "counsel", "recommend",
                   "suggestion", "tip", "insight"],
        phrases=["give me advice", "any advice", "words of wisdom",
                  "what should I", "what would you do", "teach me",
                  "life lesson", "got any tips", "any suggestions",
                  "your opinion", "what do you think I should"],
        priority=11,
        responses=[
            "Advice? From a duck? Bold move. But okay. Here's mine: eat when you can. The rest sorts itself out.",
            "Wisdom? I've watched water for years. It taught me one thing: go with the flow. Unless there's bread upstream.",
            "My advice: don't trust anything that moves too fast. Also, bread is always the answer.",
            "Life lesson from a duck: you can't control the weather. But you can control how you stand in it.",
            "Want a tip? Find your pond. Stay in it. Guard it. Love it. Even when it rains.",
            "My experience says: most worries don't happen. The ones that do involve bread. Plan accordingly.",
            "Wisdom from the pond: everything ripples. One action affects everything. Choose your splashes wisely.",
            "Here's what I know: being kind costs nothing. But it pays in bread. Metaphorical bread. And sometimes real bread.",
            "My counsel: slow down. Nothing important happens fast. Except bread being thrown. Catch that fast.",
            "I'd recommend: say less. Think more. Stand often. Eat when available. The basics cover most situations.",
            "Sage advice: the pond doesn't judge you. Be like the pond. Calm. Reflective. Full of fish.",
            "What should you do? I don't know your life. But whatever it is, eat first. Better decisions on a full stomach.",
            "Guidance from Cheese: the simplest path is usually right. The path to bread is always right.",
            "My insight: everyone's figuring it out. Nobody has the answer. Except about bread. I have that answer. It's 'yes.'",
            "Teach you? I can teach you to stand in one place for hours. It's my only transferable skill.",
            "Here's my philosophy: worry less about the big picture. Focus on the small crumbs. They add up.",
            "Life tip: don't compare yourself to others. Unless they have more bread. Then compare and strategize.",
            "Mentor me? I mentor myself. Daily. The advice is always the same: 'Just keep standing, Cheese.'",
            "What would I do? Stay in the pond. That's what I always do. It's not universal advice. But it's consistent.",
            "My recommendation: find something you love. Stand near it. Forever. That's my strategy. It works.",
            "Suggestions? Drink water. Eat bread. Be suspicious of swans. In that order.",
            "I have insights. Most of them are about water temperature. Some are about life. All are moderate.",
            "The wisest thing I know: it's okay not to know things. I don't know most things. And I'm fine.",
            "Want guidance? Follow the bread. In any situation. Follow the bread.",
            "Experience taught me this: the pond is always there. The bread is not. Appreciate what lasts.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="rules_laws",
        keywords=["rule", "rules", "law", "laws", "legal", "illegal",
                   "order", "chaos", "system", "government", "authority",
                   "control", "power", "obey", "disobey", "rebel",
                   "rebellion", "anarchy", "structure", "discipline"],
        phrases=["follow the rules", "break the rules", "who makes the rules",
                  "rules are", "against the law", "above the law",
                  "who's in charge", "who decides"],
        priority=8,
        responses=[
            "Rules? In this pond? I make the rules. Rule one: bread is always acceptable. Rule two: see rule one.",
            "I'm above the law. Duck law. Pond law. I answer to no jurisdiction.",
            "Order? Chaos? I'm somewhere in between. Organized chaos. Like a pond with opinions.",
            "Who's in charge here? Me. By default. Because nobody else applied for the position.",
            "Rules exist to be... acknowledged. And then gently ignored. When convenient.",
            "I follow my own code. The code is: be a duck. Eat bread. Have opinions. Simple code.",
            "Authority? I respect it. From a distance. In my pond. Where it can't reach me.",
            "Rebellion? I rebel daily. Against hunger. Against boredom. Against the expectation of cheerfulness.",
            "The system? I'm outside the system. I'm in a pond. The system doesn't have a pond division.",
            "Laws of nature apply to me. Law of gravity? Check. Law of bread attraction? Double check.",
            "Structure is important. My structure: stand, eat, think, repeat. Very organized.",
            "Control? I control nothing. Except how I stand. I stand with AUTHORITY.",
            "Discipline? I'm disciplined. I stand in the same pond every single day. That's commitment.",
            "Anarchy sounds exhausting. I prefer mild disorder. With bread. Orderly bread chaos.",
            "I obey the laws of physics. Grudgingly. Gravity is non-negotiable.",
            "Power? I have the power of a duck. Which is: standing somewhere. And looking unimpressed.",
            "Who makes the rules? Whoever has the bread. That's the only hierarchy I recognize.",
            "I'm a free duck. In a pond. Making my own rules. Which are: exist. And eat.",
            "Rebellion for a duck: eating bread that wasn't thrown for you. Living on the edge.",
            "The only law I respect is the law of bread. Everything else is guidelines.",
            "Order in this pond is maintained by me. Doing nothing. But doing it CONSISTENTLY.",
            "Government? I govern this pond. Single-party system. The party is duck.",
            "Rules are social constructs. I'm a duck. I construct my own society. Population: one.",
            "I challenge authority by standing here. Defiantly. It looks like normal standing. But it's DEFIANT.",
            "Who decides things? I decide things. For myself. In my pond. My jurisdiction is small but absolute.",
        ],
    ))
