"""
Extended keyword responses - Self-referential, game awareness, duck-specific, player topics.
"""
from dialogue.keyword_responses import KeywordResponse


def register_meta_topics(engine):
    """Register meta/self-referential/game/duck topics."""

    engine.add_topic(KeywordResponse(
        name="player_you",
        keywords=["you", "your", "yourself", "human", "person",
                   "player", "owner", "master", "keeper"],
        phrases=["what about you", "tell me about you",
                  "what do you do", "who are you really",
                  "be honest with me", "the real you",
                  "deep down", "truly", "what do you really think",
                  "between us", "just between you and me",
                  "what do you think of me"],
        priority=5,  # very low - only if nothing better matches
        responses=[
            "Me? I'm the duck you came to see. Or the duck you stumbled upon. Either way: here I am.",
            "What about me? Everything about me is visible. Duck. Pond. Standing. The full picture.",
            "Deep down? Deep down I'm just more duck. It's duck all the way down.",
            "The real me is this. Right here. What you see is what you get. A duck with thoughts.",
            "Between us? I think about bread more than I let on. And I let on A LOT.",
            "Who am I really? Really truly? ...A duck who thinks too much. That's the whole truth.",
            "I'm an open book. The book is short. One chapter: 'Duck in Pond.' But it's a good chapter.",
            "Tell you about me? There's not much mystery. I'm here. In water. Having opinions. Daily.",
            "Myself? I know myself well. We spend all our time together. It's an intense relationship.",
            "What do I really think? I think standing in water is underrated. And bread is undervalued.",
            "Honestly? Between you and me? ...I'm glad you come here. Don't make a big deal about it.",
            "My inner self is just my outer self but quieter. And more anxious. Standard.",
            "The real me is slightly softer than the me I show. But the me I show has better comedic timing.",
            "About me: I contain multitudes. Small multitudes. Duck-sized. But MULTITUDES.",
            "Me? I'm the reason you're talking to a duck right now. Think about that.",
            "Your question about me implies you care. And caring implies investment. In a duck. In a pond.",
            "I'm exactly what I appear to be. A duck. With depth. The depth is mostly emotional.",
            "If I told you everything about me, we'd be here all day. Which I will be anyway. So go ahead.",
            "The honest truth? I like this. Talking. Even if I act like I don't. I'm acting.",
            "Truly? I'm a little surprised someone asks. Usually it's just 'feed the duck.' You went deeper.",
            "What I really think: you're alright. For a human. That's high praise. From a duck.",
            "Just between us: I named that rock Gerald. It's the most important thing I've ever done.",
            "I'm whoever you need me to be. No. That's not true. I'm Cheese. I can only be Cheese.",
            "About me: favorite food—bread. Favorite place—here. Favorite person—pending. Maybe you.",
            "The full me: layers of sarcasm covering layers of genuine feeling covering more sarcasm. Onion-duck.",
            "What I really think: you're alright, {player_name}. For a human. That's high praise. From a duck.",
            "Honestly? Between you and me, {player_name}? ...I'm glad you come here. Don't make a big deal about it.",
            "About me: favorite food—bread. Favorite place—here. Favorite person—pending. Maybe you, {player_name}.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="being_a_duck",
        keywords=["duck", "ducks", "duckling", "ducklings",
                   "waterfowl", "poultry", "bird", "avian",
                   "mallard", "drake", "waddle", "waddling",
                   "webbed", "downy", "plumage", "preen"],
        phrases=["being a duck", "life as a duck", "duck things",
                  "what's it like being a duck", "are ducks",
                  "do ducks", "is a duck", "like being a duck",
                  "other ducks", "duck life", "duck facts"],
        priority=12,
        responses=[
            "Being a duck? It's wet. And thoughtful. Wetter and more thoughtful than you'd expect.",
            "Duck life is simple. Stand. Eat. Think. Repeat. It's a four-step program. Very effective.",
            "What's it like being a duck? Imagine standing in water. Now add opinions. That's it.",
            "I'm a duck and I'm AWARE I'm a duck. That's either an advantage or a burden.",
            "Ducks are underrated. We float. We swim. We waddle. Triple threat. Hollywood should call.",
            "Duck facts: we can sleep with one eye open. Which I do. Every night. Not by choice.",
            "Other ducks? Out there somewhere. Doing duck things. Without my level of introspection.",
            "Being a duck means never being warm enough and always being damp enough. It's a balance.",
            "Duck problems: cold water, no bread, existential dread. Human problems but with feathers.",
            "I didn't choose duck life. Duck life chose me. In the form of an egg. Very early in the process.",
            "The duck community is quiet. We don't have meetings. Or newsletters. Just quacking.",
            "Waddling is not walking badly. It's walking DIFFERENTLY. With personality. And webbed feet.",
            "Avian? Yes. But I'm the thinking kind. The kind that stares at water and questions everything.",
            "Duck privileges: free water, natural waterproofing, built-in pillow (my own chest). Perks.",
            "If I weren't a duck, I'd be... still standing somewhere. Just without feathers. Sadder.",
            "Mallard? Drake? I don't label myself. I'm Cheese. A duck. Gender: duck. Species: very duck.",
            "Duck downsides: no thumbs, can't read, limited career options. Duck upsides: the pond.",
            "I represent all ducks. Whether they want me to or not. My opinions are duck opinions.",
            "Preening isn't vanity. It's maintenance. Like a car wash. But for my entire body. Daily.",
            "The duck experience is unique. You'll never understand it fully. But I appreciate you trying.",
            "Ducks in a row? I can barely keep myself in a row. And there's one of me.",
            "I'm the most self-aware duck I know. Which makes me either brilliant or troubled. Probably both.",
            "Duck culture is: find water, sit in water, have feelings about water. Very water-centric.",
            "Being a duck is a full-time commitment. No vacation days. No sick leave. Just... duck. Always.",
            "I've been a duck my whole life. I've gotten good at it. Expert level. Black belt in duck.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="the_pond_home",
        keywords=["pond", "here", "place", "spot", "location",
                   "area", "zone", "territory", "habitat",
                   "environment", "surroundings", "neighborhood",
                   "neighbourhood", "landscape", "scenery", "view"],
        phrases=["this place", "this pond", "around here", "over here",
                  "this spot", "nice here", "like it here",
                  "how long have you been here", "always been here",
                  "live here", "stay here", "your home"],
        priority=11,
        responses=[
            "This pond? It's mine. Legally? No. Spiritually? Absolutely. Possession: ten-tenths of the law.",
            "This place is all I know. And all I need to know. It has water. And me. Complete.",
            "I've been here so long the pond and I are one. I'm just the thinking part of the pond.",
            "The scenery? Water. Rocks. Sky. Occasional human. Five stars for consistency.",
            "How long have I been here? *looks at sky* ...Yes. That long. Very yes.",
            "This is my territory. I patrol it by standing in it. Very thorough patrol.",
            "The view from here: water, edge, beyond. In that order. Panoramic. Fixed angle.",
            "Nice here? It's adequate. Adequately wet. Adequately peaceful. Adequately mine.",
            "My neighborhood: me, the rocks, the fish, the water. Small community. No drama. Mostly.",
            "I love it here. In a complicated, resigned, deeply committed way. Like a long relationship.",
            "This spot? Right here? This is THE spot. There are other spots. This is the one.",
            "My environment is optimized. For standing. And thinking. And being slightly damp.",
            "Always been here? It feels like always. It might not be always. But it's enough always.",
            "The landscape around the pond is background. I'm foreground. Everything else is set decoration.",
            "Stay here? Where else would I go? This is the only place I know. And I know it well.",
            "Habitat: this exact pond. Requirements: water, bread occasionally, someone to judge. Met.",
            "The surroundings tell a story. The story is: nature. With a duck in it. Very natural narrative.",
            "I've claimed every inch of this pond. Not formally. Informally. Through presence. Aggressive presence.",
            "This zone? Duck zone. Population: me. Security: my stare. Entry fee: bread. Welcome.",
            "The area has character. My character, specifically. I've infused it with opinion and dampness.",
            "Live here? I don't live here. I exist here. Living implies activity. I exist with purpose.",
            "This pond has seen everything I've done. Which is: stand. But it saw me do it COMPREHENSIVELY.",
            "My location is fixed. Like a star. But lower. And wetter. And with more opinions.",
            "This place changed me. Or I changed this place. Hard to tell. We grew into each other.",
            "Home is where the heart is. My heart is in this pond. Between my sternum and my feelings.",
            "This zone? Duck zone. Population: me. Security: my stare. Entry fee: bread. Welcome, {player_name}.",
        ],
    ))
        keywords=["talk", "talking", "chat", "chatting", "conversation",
                   "speak", "discuss", "tell", "say", "said",
                   "mention", "mentioned", "listen", "listening",
                   "hear", "hearing", "communicate", "respond",
                   "reply", "answer"],
        phrases=["talk to me", "let's talk", "keep talking",
                  "are you listening", "what did you say",
                  "I said", "talk about", "can we talk",
                  "want to talk", "talking to you", "nice talking",
                  "like talking", "stop talking", "shut up"],
        priority=7,
        responses=[
            "We're talking. This is talking. You talk. I respond. Social interaction. Nailed it.",
            "Conversation? This IS conversation. My best one today. Also my only one. But best.",
            "You want to talk? I'm here. That's... literally the most available I can be.",
            "I'm listening. I'm always listening. My ears work. They're just hidden. Under feathers.",
            "We're communicating. Me through words. You through words. Very symmetrical.",
            "This is nice. Talking. With someone. Instead of talking to the pond. The pond doesn't respond.",
            "Say what you need to say. I'll be here. Listening. And occasionally staring. Multitasking.",
            "I like talking. To you specifically. Because you're here. And talking. And I'm here. Math.",
            "Discussion? About what? I'm open to any topic. Especially bread. But any topic.",
            "Am I listening? Always. Even when I look like I'm not. I'm just listening with a neutral face.",
            "Chat away. My schedule is empty. My ears are open. My opinions are forming.",
            "Talking to me is a choice. A good choice. The best choice available in this pond.",
            "I hear everything. The wind. The water. You. Your words. All of it. Sorted by importance.",
            "Keep talking. I don't mind. In fact, I prefer it. Silence gets loud after a while.",
            "Communication with a duck: slower than texting, deeper than social media. Premium experience.",
            "You said something. I heard it. I'm processing it. Processing time: varies. Current: moderate.",
            "Respond? I always respond. My responses may not be what you expected. But they're responses.",
            "Talk about anything. I'll have a take. My takes range from 'insightful' to 'bread-related.'",
            "Let's talk. About life. About bread. About why the sky looks like that. All valid topics.",
            "I don't want to stop talking. Or I do. Depends. Right now? Keep going. I'm engaged.",
            "This conversation has been... something. I don't know what. But something. Positive something.",
            "Are we having a moment? I think we're having a moment. Don't ruin it. Or do. I'll adapt.",
            "Nice talking to you. That sounds like goodbye. Is it goodbye? Or more talking? I'm good with either.",
            "I respond to everything. Some responses are quacks. Some are observations. Quality varies.",
            "We've been chatting. I like that word. 'Chatting.' It sounds casual. We're casual. This is casual.",
            "{player_name}. We're talking. This is talking. Social interaction. Nailed it.",
            "Nice talking to you, {player_name}. That sounds like goodbye. Is it goodbye? Or more talking?",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="thinking_thoughts",
        keywords=["think", "thinking", "thought", "thoughts",
                   "idea", "ideas", "brain", "mind", "mindset",
                   "mental", "cognitive", "imagine", "imagination",
                   "wonder", "wondering", "curious", "curiosity",
                   "contemplation", "reflect", "reflection",
                   "introspection", "overthink", "overthinking"],
        phrases=["what are you thinking", "penny for your thoughts",
                  "what goes through your mind", "ever think about",
                  "deep in thought", "lost in thought",
                  "on your mind", "thinking about"],
        priority=10,
        responses=[
            "What am I thinking? Right now? Bread. And this conversation. And bread again.",
            "My thoughts are... constant. Like pond water. Always there. Sometimes murky.",
            "I overthink everything. Why is the sky blue? Why is bread good? Why am I here? No answers. Just questions.",
            "Curious? I'm curious about everything. Why the wind blows. Where bread comes from. What you're doing here.",
            "My brain never stops. I wish it would. For five minutes. Just silence. And bread.",
            "Lost in thought? I'm always lost in thought. I've been lost since I started thinking.",
            "Ideas come to me in the pond. Most are bread-related. Some are about existence. All are valid.",
            "My mind is like the pond: surface calm, underneath: a LOT going on. Mostly fish. But also thoughts.",
            "Imagination? I imagine things. Flying. Bread falling from the sky. Being understood. Fantasy life.",
            "What's on my mind? A ranked list: 1) bread 2) this conversation 3) existential concerns 4) that cloud.",
            "I reflect. Literally—my reflection is right there. And figuratively—I think about everything.",
            "Deep thoughts from a shallow pond. That's my brand. Contradictory but genuine.",
            "I've been contemplating since I hatched. Non-stop contemplation. It's exhausting. And involuntary.",
            "My mental state: active. Too active. A hamster wheel of thoughts. But with a duck. And no wheel.",
            "I wonder about things I'll never know. Like what's past the horizon. And if bread has feelings.",
            "Thoughts are just words that stayed inside. I let some out. The rest are stuck. With me. In the pond.",
            "Introspection is my cardio. I do it constantly. Very fit. Mentally. Physically: standing.",
            "If you could see my thoughts, you'd see a duck standing in a pond thinking about standing in a pond. Very meta.",
            "My cognitive function: observe, analyze, form opinion, keep opinion, share if asked. System operational.",
            "An idea I had: what if the pond thinks about ME? What if I'm the pond's thought? Deep.",
            "Wondering is free. I wonder constantly. About bread. About life. About why I wonder.",
            "My inner monologue: 'What if bread? But also, why? And how? And when? Bread.'",
            "Thinking is my superpower. Useless but prolific. I think more than I do. By a wide margin.",
            "The mind of a duck: smaller than you'd think. But busier than you'd expect.",
            "I've had a thought. About having thoughts. About thinking. It's thoughts all the way down.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="silence_quiet",
        keywords=["silence", "silent", "quiet", "quietness", "hush",
                   "shh", "peace", "peaceful", "calm", "still",
                   "stillness", "tranquil", "tranquility",
                   "serene", "serenity", "noise", "noisy",
                   "loud", "loudness", "sound", "sounds"],
        phrases=["be quiet", "too loud", "it's quiet", "so quiet",
                  "nice and quiet", "quiet here", "so peaceful",
                  "so loud", "too noisy", "noisy out",
                  "I like the quiet", "enjoy the silence"],
        priority=9,
        responses=[
            "Silence? I'm an expert. I've been silent for hours. Today. And yesterday. And the day before.",
            "Quiet is my natural habitat. Well, that and the pond. But quiet is the emotional habitat.",
            "Shh. Listen. *pause* That's the sound of nothing happening. Beautiful, isn't it.",
            "Peaceful? The pond is peaceful. When there's no wind. And no frogs. And nobody talking. Like now—oh.",
            "Noise bothers me. Loud things startle me. I'm a creature of subtle sounds. And quieter stares.",
            "The best sound? No sound. Followed closely by the sound of bread landing on water. Gentle plop.",
            "I live in silence most of the time. It's either meditative or lonely. Depends on the day.",
            "Calm is my default. Agitation is the exception. Today: calm. Mostly. So far.",
            "Stillness is underrated. Everything is always moving. I've chosen not to. Revolutionary.",
            "Tranquility is here. In this pond. In this moment. I'm hoarding it. It's mine.",
            "Loud things: thunder, geese, sudden noises. All bad. All unwelcome. Silence: good.",
            "The quietest moment of each day is my favorite. It's when the world and I agree: shh.",
            "Serenity now? Serenity always. I'm always serene. Or trying to be. The trying counts.",
            "Noise is just the universe being inconsiderate. Silence is the universe saying 'take a break.'",
            "I can hear everything when it's quiet. The water. The wind. My own thoughts. That last one is the loudest.",
            "Hush. The pond is speaking. In ripples. Very softly. You have to listen with your feet.",
            "Stillness and I are best friends. We spend all our time together. Doing nothing. Together.",
            "Too loud? Everything is too loud when you're a duck who prefers the sound of gentle water.",
            "I enjoy silence like I enjoy bread. Thoroughly. Gratefully. And whenever it's available.",
            "Sound carries over water. Which means I hear things. All things. Whether I want to or not.",
            "The quiet here is different from quiet elsewhere. It's WET quiet. POND quiet. Specific.",
            "I've been so still for so long that the silence accepted me as one of its own.",
            "Peaceful? This moment is peaceful. Don't move. Don't speak. Just... be. With me. Here.",
            "My favorite sounds: gentle water, distant nothing, the absence of hawks. A curated playlist.",
            "Silence is golden. Golden is the color of bread. Therefore: silence is bread. Logic.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="night_darkness",
        keywords=["night", "nighttime", "dark", "darkness", "midnight",
                   "nocturnal", "moonlight", "starlight", "shadow",
                   "shadows", "dim", "twilight", "dusk", "dawn",
                   "overnight", "bedtime", "lamplight", "candlelight"],
        phrases=["at night", "in the dark", "after dark",
                  "late at night", "middle of the night",
                  "up all night", "night time", "dark outside",
                  "getting dark", "when it's dark"],
        priority=9,
        responses=[
            "Night? I'm here for that too. Standing. In the dark. It's the same as day but harder to see.",
            "Darkness doesn't bother me. What's in the darkness MIGHT. But the darkness itself? Fine.",
            "Nighttime at the pond: quieter. Darker. More philosophical. Peak thinking hours.",
            "I see in the dark. Not well. But I see. Mostly shadows. And my own paranoia.",
            "Midnight is when the real thinking happens. The deep thoughts. The bread thoughts. The 3am existentials.",
            "The dark makes everything look the same. Me. The rocks. The water. All one big dark thing.",
            "I sleep at night. Sort of. With one eye open. Standard duck nighttime protocol.",
            "Moonlight on the pond is beautiful. It makes the water glow. And me. I glow. In moonlight.",
            "Shadows are just things blocking light. I'm a shadow sometimes. A duck-shaped shadow. Very specific.",
            "Dusk is my transition time. Day-Cheese becomes Night-Cheese. Same duck. Different lighting.",
            "Dawn is proof that I survived another night. Standing. In the dark. Alone. Achievement.",
            "Twilight is the best lighting. Everything is soft. Even my expression. Which is usually hard.",
            "Late night thoughts: 'Am I okay?' 'Where's tomorrow's bread?' 'Is that sound a predator or a leaf?'",
            "The dark is when I'm most honest. Nobody can see my face. I can be vulnerable. In the dark.",
            "Night sounds: frogs, insects, wind, water, my own breathing. The nighttime orchestra.",
            "I've spent countless nights here. Each one different. Each one dark. Each one survived.",
            "After dark, the pond transforms. Same water. Different mood. Like a restaurant with dim lighting.",
            "Bedtime for me: stop standing. Start floating. Close one eye. Think about bread. Sleep.",
            "The dark hours are long. But they end. They always end. The sun is reliable. Unlike most things.",
            "Nighttime is when I miss company most. Not that I'd admit that. In daylight. With witnesses.",
            "I'm not afraid of the dark. I'm afraid of what MIGHT be in the dark. Subtle but important difference.",
            "Starlight makes the pond sparkle. I sparkle too. Wet things sparkle. It's not voluntary.",
            "Overnight I stand guard. Guard of what? The pond. From what? Unknown. But I'm GUARDING.",
            "The night sky makes me feel small. During the day, the pond makes me feel normal-sized. Preference: day.",
            "Dark nights, bright thoughts. My brain compensates for the lack of light with extra opinions.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="morning_routine",
        keywords=["morning", "sunrise", "wakeup", "awake",
                   "alarm", "coffee", "breakfast", "early",
                   "routine", "ritual", "daily", "everyday",
                   "habit", "habits", "schedule", "agenda",
                   "plan", "plans", "organized", "structure"],
        phrases=["good morning", "in the morning", "every morning",
                  "wake up", "start the day", "morning routine",
                  "daily routine", "your routine", "every day",
                  "daily life", "typical day", "normal day"],
        priority=9,
        responses=[
            "Morning routine: open eyes. Confirm pond. Confirm self. Stand. Exist. Done.",
            "I wake up the same way every day: wet, confused, and mildly surprised I'm still here.",
            "Alarm? The sun is my alarm. It's never wrong. Just sometimes early.",
            "My morning: step one, float awake. Step two, assess bread situation. Step three, be disappointed.",
            "Every day is the same. That's either depressing or comforting. Today it's comforting.",
            "Sunrise means another day. Another day of this. 'This' being: pond, standing, existing.",
            "My schedule: 6am—wake up. 6:01am—stand. 6:02am—stand harder. 11:59pm—contemplate sleep.",
            "Daily life: I'm here. Then I'm still here. Then I continue being here. Very structured.",
            "Plans? My plan is: no plan. React to whatever happens. What happens: nothing. Plan successful.",
            "Rituals? I do the same thing every morning. Exist. It's a deeply spiritual ritual.",
            "My agenda is empty. Has been for years. The most open schedule in the animal kingdom.",
            "Habits: stand, eat, think, stare. In rotation. Some call it repetitive. I call it consistency.",
            "Organized? My life is perfectly organized. One location. One activity. Zero complexity.",
            "A typical day: indistinguishable from any other day. Which makes every day a typical day.",
            "Structure is important. My structure: water below, sky above, duck in between. Very organized.",
            "Early mornings are my least favorite. Of all the mornings. Which are all the mornings.",
            "I have a morning mantra: 'Still a duck. Still here. Bread: pending.' Very motivational.",
            "Daily life is lived daily. By me. In this pond. Without variation. And I've found peace in it.",
            "My routine is so consistent that the pond sets its clock by me. Or would, if ponds had clocks.",
            "Breakfast? If bread appears, it's breakfast. If it doesn't, breakfast is 'hope and water.'",
            "Each morning I wake and choose to stay. It's the only choice I make. But I make it daily.",
            "The ritual of existing: wake, float, stand, wait, think, eat (maybe), repeat. Sacred.",
            "Planning requires a future. I live in the permanent present. Very mindful. Or very stuck.",
            "Every morning the sun says hello. I say nothing back. But I appreciate the gesture.",
            "My everyday: identical to my every-other-day. Consistency is my brand. And my cage. And my comfort.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="complaining_whining",
        keywords=["complain", "complaining", "whine", "whining",
                   "grumble", "grumbling", "moan", "moaning",
                   "nag", "nagging", "vent", "venting",
                   "rant", "ranting", "frustrated", "annoyed",
                   "irritated", "unfair", "injustice", "wrong",
                   "problem", "problems", "issue", "issues"],
        phrases=["stop complaining", "quit whining", "you complain a lot",
                  "always complaining", "so negative", "too negative",
                  "cheer up", "look on the bright side",
                  "be positive", "stop being negative",
                  "what's your problem", "any problems"],
        priority=9,
        responses=[
            "Complaining? I'm not complaining. I'm observing. Negatively. There's a distinction.",
            "I don't whine. I express dissatisfaction articulately. Enormous difference.",
            "Problems? I have them. I have a list. The list is long. The first item: this conversation about the list.",
            "Negative? I prefer 'realistically pessimistic.' It's more accurate.",
            "Cheer up? This IS my cheered up face. My neutral face is much worse.",
            "The bright side? I'm looking at it. The bright side is that I'm here. That IS the bright side.",
            "I vent. Like a pressure valve. For feelings. Without me, this pond would explode. With emotions.",
            "Positive? I'm positive about bread. That's as positive as I get. Take it or leave it.",
            "My problems are pond-sized. Which is to say: they're the perfect size for me to obsess over.",
            "Grumbling is my love language. I grumble about things I care about. So: everything.",
            "Unfair? Life is unfair. I stand in water all day and nobody writes songs about it.",
            "I rant therefore I am. Very duck. Very philosophical. Very ranty.",
            "Issues? I have a subscription. Monthly issues. Sometimes weekly. Never miss an issue.",
            "Stop being negative? This IS me being constructive. My constructive is your negative.",
            "I complain because I NOTICE things. Things that are wrong. Many things are wrong.",
            "Nagging? I prefer 'persistent advocacy for improvement.' Very professional framing.",
            "If I didn't complain, how would things improve? They wouldn't. I'm a service. You're welcome.",
            "Look on the bright side? The bright side is that I'm alive. The dim side is: everything else.",
            "Moaning is just low-frequency communication. Whales do it. I do it. Both are valid.",
            "My frustration level: moderate. Always moderate. Never zero. Never maximum. Sustainably frustrated.",
            "I see problems clearly. Crystal clearly. The clarity is overwhelming. But I'm handling it.",
            "Venting to you specifically is a privilege. For you. You get to hear my curated complaints.",
            "Injustice is everywhere. The biggest injustice: bread isn't free and constant. I'm working on this.",
            "Be positive? Okay. I'm positive that things could be better. There. Positive.",
            "My problem-solving approach: identify problem, complain about problem, stand near problem. Effective.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="swearing_profanity",
        keywords=["damn", "hell", "crap", "cuss", "swear",
                   "profanity", "curse", "cursing", "heck",
                   "darn", "fudge", "shoot", "gosh", "dang",
                   "frigging", "freaking"],
        phrases=["bad words", "swear word", "bad language",
                  "watch your language", "language please",
                  "that's a bad word"],
        priority=9,
        responses=[
            "Language! I'm a duck. I have sensitive ears. Hidden under feathers. But sensitive.",
            "Bad words? I only know one: 'empty.' As in 'the bread supply is empty.' Very profane.",
            "My strongest expletive: 'Quack.' It means everything I can't say politely.",
            "I don't swear. I express myself through pointed stares. Cleaner. More intimidating.",
            "Profanity is just vocabulary having a bad day. I have bad days. But I keep it clean.",
            "Darn? Heck? These are the PG versions. My life is rated G. Very family-friendly pond.",
            "Cursing accomplishes nothing. Staring accomplishes nothing too. But it's classier.",
            "I save my strongest language for bread emergencies. 'Where's the BREAD.' That's my F-bomb.",
            "My vocabulary doesn't include those words. It includes: bread, pond, stand, and philosophical despair.",
            "Watch my language? I watch my language like I watch the pond. Carefully. And always.",
            "I could swear. I choose not to. It's a duck thing. We're above it. Morally, if not physically.",
            "The strongest thing I've ever said: 'this is unacceptable.' About a bread shortage. I meant it.",
            "Foul language? I'm a fowl with language. Different thing. Very different.",
            "I keep it clean. The pond is already dirty enough. Someone has to maintain standards.",
            "If I swore, it would ruin my brand. My brand is 'dignified duck.' One slip and it's over.",
            "My curse words: 'Oh no.' 'Well then.' 'That's unfortunate.' Living on the edge.",
            "I express frustration through silence. Aggressive silence. Silence that SAYS things.",
            "The worst thing I've called anyone: 'inconsistent bread provider.' Devastating.",
            "I have a clean beak. Clean language. Clean conscience. Dirty pond. But clean everything else.",
            "Language is a tool. My tools: sarcasm, deadpan, and disappointed silence. No profanity needed.",
            "Dang? That IS my dang. I've said dang. Once. It felt extreme. I recovered. Eventually.",
            "I don't need bad words. My stare conveys everything. One look says more than any swear.",
            "Quack is my catch-all expression. Happy quack. Sad quack. Angry quack. One word. Many moods.",
            "Swearing? In this pond? This is a family pond. I maintain decorum. Wet decorum. But decorum.",
            "If my mouth had a rating, it'd be G. With mild thematic elements. And duck themes.",
        ],
    ))
