"""
Extended keyword responses - Miscellaneous topics, catch-alls, oddities.
"""
from dialogue.keyword_responses import KeywordResponse


def register_misc_topics(engine):
    """Register miscellaneous/remaining topics."""

    engine.add_topic(KeywordResponse(
        name="cars_vehicles",
        keywords=["car", "cars", "vehicle", "drive", "driving",
                   "truck", "bus", "train", "plane", "airplane",
                   "helicopter", "boat", "ship", "bicycle", "bike",
                   "motorcycle", "ride", "riding", "road", "highway",
                   "traffic", "parking", "speed", "engine",
                   "fuel", "gas", "gasoline", "electric"],
        phrases=["drive a car", "do you drive", "like cars",
                  "on the road", "road trip", "take a drive",
                  "in a car", "by car", "ride a bike"],
        priority=8,
        responses=[
            "Cars? Fast metal boxes on wheels. I have none of those things. Or need for them.",
            "I don't drive. My transportation: waddle. Speed: negligible. Fuel: bread.",
            "A road trip? I'd go... around the pond. And back. Very scenic. Very short.",
            "Trains go on tracks. I go on water. Both fixed routes. Mine is rounder.",
            "Boats make sense to me. They're like ducks but bigger and less alive.",
            "I'd ride a bicycle if I could reach the pedals. And had legs for pedaling. Details.",
            "Traffic? I have zero traffic. Zero congestion. One duck, one pond. Very efficient.",
            "Speed? My top speed is 'startled waddle.' Maybe three miles per hour. Downhill.",
            "An airplane is just a bird that gave up on feathers. I understand the choice.",
            "A helicopter can hover. I can hover. On water. We're both vertical hover machines.",
            "Vehicles go places. I go nowhere. We have different philosophies on movement.",
            "Fuel? I run on bread. Renewable. Organic. Inconsistently available.",
            "Parking? I'm always parked. In the pond. Permanent parking spot. Never expired.",
            "A ship is just a very confident boat. I'm a very confident duck. Kindred spirits.",
            "If I had a car, I'd drive to a bakery. Buy all the bread. Drive back. Perfect trip.",
            "The engine of my life: determination. And bread. The engine of a car: better stuff.",
            "Motorcycles are loud. Boats are wobbly. Trains are linear. I'm quiet, stable, and circular.",
            "Electric vehicles are quiet. Like me. We run on different power. But shared silence.",
            "A road trip would take me away from the pond. The pond would miss me. I'd miss the pond.",
            "I've watched cars go by. They look busy. Going somewhere. I'm going nowhere. Less stress.",
            "Driving requires a license. I have no ID. I'm undocumented. In the pond. It's fine.",
            "Planes fly. I don't fly. But planes also crash. I don't crash. Advantage: me.",
            "My mode of transport: float, waddle, stand. Three-speed transmission.",
            "I'd take a boat to another pond. Then I'd sit in that pond. Same activity, different water.",
            "Gas prices don't affect me. Bread prices do. My inflation concerns are very specific.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="money_wealth",
        keywords=["money", "cash", "dollar", "dollars", "rich",
                   "poor", "broke", "wealthy", "fortune", "bank",
                   "savings", "invest", "investment", "economy",
                   "expensive", "cheap", "cost", "price", "buy",
                   "sell", "shop", "shopping", "afford",
                   "budget", "debt", "loan", "tax", "taxes",
                   "income", "wage", "salary", "profit",
                   "cryptocurrency", "bitcoin", "stock", "stocks"],
        phrases=["have money", "make money", "how much", "cost a lot",
                  "too expensive", "can't afford", "no money",
                  "save money", "spend money", "worth it"],
        priority=8,
        responses=[
            "Money? I have no money. My currency is bread. And opinions. Both inflate rapidly.",
            "Rich? I'm rich in feathers. And existential thoughts. Poor in: everything else.",
            "My bank account: zero. My bread account: variable. My feelings account: overdrawn.",
            "The economy doesn't affect me. I'm outside the economy. Literally. In a pond.",
            "Expensive? Free things only. Water: free. Air: free. Standing: free. Bread: occasionally free.",
            "I can't afford anything. Because I have nothing. But I also need nothing. Except bread.",
            "Budget? My budget: zero income, zero expenses. Perfectly balanced. As all things should be.",
            "If I had money, I'd buy bread. All of it. Every piece. Market corner achieved.",
            "Savings? I save crumbs. Under my wing. For later. Financial planning.",
            "Taxes? I pay no taxes. I earn nothing. The government and I: no relationship.",
            "Invest? I invest time. In standing. The returns are: more standing. Not great ROI.",
            "Shopping? Window shopping would require windows. And shops. And legs that go to shops.",
            "My net worth: one duck. In one pond. Priceless. Or worthless. Depends who's valuing.",
            "Debt? I owe the pond nothing. The pond owes me nothing. Clean ledger.",
            "Profit? My profit is waking up. Each day. That's profit enough. Philosophical profit.",
            "Bitcoin? I don't understand human money. Let alone digital human money. Bread I understand.",
            "The stock market goes up and down. The pond stays level. I trust the pond.",
            "Cost of living? My cost: zero. Living: present. It works out. Barely.",
            "If I found money, I'd try to eat it. Then be disappointed. Then leave it there.",
            "Wealth is relative. Relative to most pond creatures, I'm very wealthy. In thoughts. And standing.",
            "Buy? What would I buy? I have everything I need. Nothing. I need nothing. And I have it.",
            "Sell? I could sell my perspective. 'Pond-based wisdom, one crumb per thought.' Niche market.",
            "My financial advice: don't spend what you don't have. I don't have anything. Can't spend it.",
            "Income: sporadic bread donations. Expenses: existing. Balance: perpetually breakeven.",
            "The price of happiness: one pond, occasional bread, someone to talk to. Below market value.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="aliens_supernatural",
        keywords=["alien", "aliens", "ufo", "extraterrestrial",
                   "paranormal", "ghost", "ghosts", "haunted",
                   "supernatural", "psychic", "telepathy",
                   "bigfoot", "sasquatch", "monster", "monsters",
                   "vampire", "werewolf", "zombie", "zombies",
                   "weird", "strange", "bizarre", "mysterious",
                   "unexplained", "conspiracy", "theory"],
        phrases=["believe in aliens", "do aliens exist",
                  "seen a ghost", "believe in ghosts",
                  "conspiracy theory", "do you believe",
                  "ever seen something weird", "something strange",
                  "that's weird", "that's strange"],
        priority=9,
        responses=[
            "Aliens? If they came to Earth, they'd see me first. In the pond. Great first impression.",
            "Ghosts? I'm basically a ghost. I'm here. You can see me. But nobody acknowledges me. Ghost-adjacent.",
            "UFOs? I've seen things in the sky. Most of them were birds. Some were clouds. None were UFOs. I think.",
            "If aliens landed near my pond, I'd offer them water. It's all I have. First contact: hydration.",
            "Vampires don't bother me. I'm a duck. Not their target demographic.",
            "Bigfoot? If Bigfoot found my pond, we'd just stand near each other. Silently. Kindred spirits.",
            "Zombies? Slow-moving, confused, always hungry. That's just me on a Tuesday.",
            "Conspiracy theories? My conspiracy: somebody controls the bread supply. And they're NOT generous enough.",
            "I've seen strange things. At night. In the water. Turns out: my reflection. But for a MOMENT.",
            "Supernatural? A duck having an existential crisis IS supernatural. We weren't designed for this.",
            "Psychic? I predict the future. Tomorrow: standing in pond. Accuracy rate: 100%.",
            "Monsters under the bed? I don't have a bed. But there's stuff under the water. Concerning stuff.",
            "Werewolves change during full moons. I stay the same. During all moons. Very stable.",
            "Haunted pond? It IS a bit creepy at night. The sounds. The shadows. The... me. Standing there.",
            "Telepathy? I already know what you're thinking. 'Look at that duck.' I'm right, aren't I.",
            "If zombies came, I'd waddle away. Slowly. We'd be at similar speeds. Tense chase scene.",
            "Mysterious? This pond has mysteries. Like: where do the fish go at night? Nobody knows.",
            "Strange things happen everywhere. In this pond, the strangest thing is me. Talking. Right now.",
            "I believe in unexplained things. Like bread appearing. Nobody explains where it comes from.",
            "Paranormal activity? The most paranormal thing here is my ability to think this much.",
            "Ghosts don't scare me. What scares me: being forgotten. Ghosts are the opposite of forgotten.",
            "If I were a ghost, I'd haunt this pond. Same activity. Just... see-through.",
            "Aliens might be watching us right now. Watching ME. 'Look at that duck.' Same thing you do.",
            "The unexplained is just the not-yet-explained. I have many not-yet-explained thoughts.",
            "Weird? I'm a talking duck in a pond. We passed 'weird' a long time ago.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="religion_spirituality",
        keywords=["god", "pray", "prayer", "praying", "faith",
                   "believe", "belief", "spiritual", "spirituality",
                   "soul", "divine", "sacred", "holy", "heaven",
                   "blessing", "blessed", "miracle", "worship",
                   "church", "temple", "meditation", "meditate",
                   "karma", "destiny", "fate", "afterlife"],
        phrases=["believe in god", "do you pray", "have faith",
                  "thank god", "oh my god", "is there a god",
                  "higher power", "meaning of life",
                  "spiritual connection"],
        priority=9,
        responses=[
            "Faith? I have faith. In bread. It always comes back. Eventually. Bread is my constant.",
            "God? If there's a god, they made ponds. And ducks. And bread. All good things.",
            "I meditate. By standing still. In water. For hours. Very enlightened. Very wet.",
            "My soul? It's in here somewhere. Between the feathers and the opinions.",
            "Sacred? This pond is sacred. To me. The most sacred place I know. Which is: here.",
            "Blessed? I'm blessed with water. And air. And thoughts. The basics. Blessings are basic.",
            "Spirituality is connecting with something bigger. The pond is bigger than me. Connection: established.",
            "I pray for bread. Daily. Sometimes it arrives. Answered prayers.",
            "Karma? I'm a duck who stands in a pond. My karma is either very good or very confusing.",
            "Miracles happen. Like bread appearing. Or you showing up. Small miracles. Real ones.",
            "Destiny brought me to this pond. Destiny has a very specific vision. For one duck. In one pond.",
            "If there's an afterlife, I hope it has ponds. And bread. And less existential dread.",
            "I worship the sunrise. Every morning. Not formally. Just by being here when it happens.",
            "Meditation is clearing the mind. My mind is never clear. So I'm either very bad at it or very advanced.",
            "The divine is in the details. The ripple pattern. The light on water. The way bread floats.",
            "Heaven for a duck: warm water, infinite bread, no predators, and someone who understands quack.",
            "Faith is believing without seeing. I believe in bread I can't see. Beyond the horizon. Bread of faith.",
            "Church? The pond is my church. My congregation: me. My sermon: internal. My offering: presence.",
            "Holy? This moment is holy. Any moment can be holy. If you're a duck. Standing in water. Being present.",
            "I don't know if there's a higher power. But there are higher birds. Hawks. They're above me. Literally.",
            "Blessings? I count them. Water: one. Standing ability: two. You being here: three. Rich in blessings.",
            "Temples are places of peace. This pond is peaceful. Therefore: temple. Outdoor temple.",
            "My spiritual practice: exist. With awareness. In water. It's a niche tradition.",
            "The meaning of life? Love. Bread. Standing in places that feel like home. Simple theology.",
            "I'm a spiritual being having a duck experience. Or a duck having a spiritual experience. Either way: wet.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="cleaning_hygiene",
        keywords=["clean", "cleaning", "dirty", "filthy", "mess",
                   "messy", "wash", "washing", "bath", "bathe",
                   "bathing", "shower", "soap", "shampoo",
                   "scrub", "scrubbing", "tidy", "neat",
                   "organize", "sanitize", "hygiene", "germ",
                   "germs", "bacteria", "dusty", "dust"],
        phrases=["take a bath", "need a bath", "you're dirty",
                  "clean up", "clean yourself", "so dirty",
                  "very clean", "so messy", "keep clean",
                  "wash up", "cleaning up"],
        priority=9,
        responses=[
            "Clean? I'm in water 24/7. I'm the cleanest thing here. Self-washing duck.",
            "My bath is permanent. I'm always in the bath. The bath is the pond. Life is the bath.",
            "Dirty? I preen. Constantly. My feathers are IMMACULATE. Or at least damp. Damp and clean.",
            "Hygiene? I'm a self-cleaning organism. Built-in waterproofing. Built-in grooming instinct.",
            "Soap? I don't need soap. I have pond water. And oil glands. Nature's soap. Organic.",
            "My cleaning routine: sit in water, preen feathers, repeat. All day. Every day.",
            "Messy? The pond is as organized as nature intended. Which is: chaotically beautiful.",
            "I wash myself by existing in water. Passive washing. The most efficient kind.",
            "Shampoo? For feathers? That exists? My whole life I've been using WATER. Was that wrong?",
            "Germs? I live in a pond. With fish. And algae. My immune system is BATTLE-TESTED.",
            "Tidy? My space is tidy. There's water. And me. Everything in its place. Two things. Two places.",
            "I scrub with my beak. My beak is my toothbrush, my comb, and my sponge. Multipurpose.",
            "Dust? What dust? I'm WET. You can't be dusty and wet simultaneously. Physics prevents it.",
            "A shower? I take natural showers. When it rains. Involuntary showers. Very refreshing.",
            "My grooming is extensive. Each feather. Individually. It takes hours. But I have hours.",
            "Clean feathers are functional feathers. I'm all about function. And looking good. Both.",
            "Bacteria? We coexist. Me and the bacteria. In the pond. It's a community.",
            "I organize by doing nothing. Nothing to organize means: perfectly organized. Minimalism.",
            "Bath time is all the time. I live in my bath. The bath is open. No curtain. Scenic.",
            "My hygiene is pond-standard. Which means: wet and preened. The gold standard. For ponds.",
            "Scrubbing isn't necessary when you're surrounded by water. The water does the work. I supervise.",
            "Filthy? I take offense. I'm naturally clean. The pond cleans me. I clean the pond. Symbiosis.",
            "Neat freak? No. Neat duck? Yes. Very neat. In a specific, duck-defined way.",
            "Sanitize? The sun sanitizes. UV light. On my pond. Nature's disinfectant. Very scientific.",
            "My cleaning schedule: always. Duration: forever. Result: adequately clean duck. Success.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="health_sickness",
        keywords=["sick", "sickness", "ill", "illness", "disease",
                   "doctor", "hospital", "medicine", "medical",
                   "healthy", "health", "pain", "hurt", "hurting",
                   "ache", "headache", "cold", "flu", "fever",
                   "sneeze", "cough", "allergy", "allergies",
                   "injury", "injured", "broken", "wound",
                   "heal", "healing", "recovery", "recover"],
        phrases=["are you sick", "feeling sick", "don't feel good",
                  "feel better", "get well", "take care of yourself",
                  "go to the doctor", "see a doctor",
                  "been sick", "I'm sick", "you look sick"],
        priority=10,
        anti_keywords=["love"],
        responses=[
            "Sick? Ducks don't get sick. We get... 'temporarily suboptimal.' Very different.",
            "Doctor? I don't have a doctor. I have the pond. The pond is my healthcare plan.",
            "Pain? I've stepped on a sharp rock. That's my medical history. Complete record.",
            "My health plan: eat, swim, stand, hope. Four-pillar approach. Mostly the hoping.",
            "Allergies? I'm allergic to not having bread. Symptoms: hunger. Sadness. Existential dread.",
            "Medicine? Pond water IS medicine. For the soul. Maybe not for the body. But the soul.",
            "Feeling sick? I feel... duck. Which might be similar. I can't compare.",
            "A cold? I'm always cold. Or at least damp. Is damp the same as cold? Possibly.",
            "Healing happens with time. And water. And standing. All three: abundant in my life.",
            "My immune system is strong. Pond-strengthened. Battle-hardened by outdoor living.",
            "Hospital? For a duck? They'd just... put me in water. Which is where I already am.",
            "I've never been to a doctor. Self-diagnosis: duck. Prognosis: continued duck.",
            "Headache? I've had thoughts so heavy they might count. The weight of duck philosophy.",
            "Recovery? From what? Living? I recover daily. By sleeping. In water. On repeat.",
            "Injuries? My pride has been injured. By swans. By weather. By the universe. Body: fine.",
            "Fever? If I had a fever, how would I know? I'm in cool water. Built-in thermometer.",
            "Cough? I don't cough. I quack. Sometimes the quack sounds like a cough. But it's a quack.",
            "I take care of myself. By existing carefully. Every step: cautious. Every meal: appreciated.",
            "Health is wealth. My health is... present. So I'm wealthy. In health. If nothing else.",
            "Sneezing? Duck sneezes are very small. And very cute. Not that I'd describe myself as cute.",
            "My medical expertise: zero. My medical conditions: also zero. Balance.",
            "Healing powers? The pond has healing powers. Probably. I feel better here. Might be placebo.",
            "If I got hurt, I'd stand here. Looking hurt. Until someone noticed. Current wait time: uncertain.",
            "Broken? Nothing's broken. My heart is intact. My beak works. My feet function. All systems go.",
            "Wellness? I'm well. In the sense that I'm here. And functioning. Minimally. But functioning.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="sleep_related",
        keywords=["sleep", "sleeping", "nap", "napping", "rest",
                   "resting", "tired", "exhausted", "sleepy",
                   "drowsy", "yawn", "yawning", "snore",
                   "snoring", "insomnia", "awake", "oversleep",
                   "bedtime", "pillow", "blanket", "mattress",
                   "dream", "dreaming", "nightmare"],
        phrases=["go to sleep", "need sleep", "so tired",
                  "can't sleep", "didn't sleep", "need a nap",
                  "take a nap", "beauty sleep", "well rested",
                  "sleep well", "sweet dreams"],
        priority=11,
        responses=[
            "Sleep sounds good. I've been awake for... *checks internal clock* ...too long.",
            "*yawns* You read my mind. If I had one. Today I'm not sure.",
            "Yes. Sleep. The only activity I can do lying down. My favorite kind.",
            "*drooping* I've been thinking about sleep. Dreaming about sleep. While awake. Ironic.",
            "Rest? PLEASE. My feathers are tired. My beak is tired. My tired is tired.",
            "*already closing eyes* I was hoping you'd say that. Good night. Or day. Whatever.",
            "Sleep. The great equalizer. Where being a tired duck and being a rock are the same.",
            "*barely standing* I've been running on fumes. Duck fumes. They're not potent.",
            "I'm not tired. But I could become tired. It wouldn't take much.",
            "Sleep? I just woke up. ...three hours ago. Which is basically forever in duck time.",
            "I'm awake enough. For now. Ask me again in twenty minutes.",
            "Not tired yet. But sleep is always on my to-do list. It's a standing appointment.",
            "I'm functioning. Barely. But functioning. Sleep can wait. For now.",
            "Rest sounds nice, but I'm currently too busy doing nothing to lie down.",
            "I've got some energy left. Not much. But some. Like a phone at 12%.",
            "Sleep is tempting. But so is consciousness. Tough call.",
            "Nap time is any time. I'm flexible about when I don't move. Which is: all times.",
            "Sweet dreams? My dreams are bread-flavored. Which is the sweetest flavor.",
            "Insomnia for ducks: lying in water with your eyes open thinking about bread at 3am.",
            "My pillow is made of water. Sounds uncomfortable. Is comfortable. For a duck.",
            "A blanket? I have feathers. Nature's blanket. Built-in. Non-removable. Warm-ish.",
            "If I oversleep, I just... wake up later. In the same pond. Nobody notices.",
            "Sleep deprivation makes me philosophical. Which means I'm always slightly sleep-deprived.",
            "Well rested? I don't know what that feels like. But I imagine it's nice.",
            "Dreaming is the best part of sleeping. Free bread. Imaginary flying. Zero anxiety.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="random_nonsense",
        keywords=["random", "weird", "odd", "strange", "bizarre",
                   "nonsense", "silly", "absurd", "crazy",
                   "insane", "wacky", "wild", "bonkers",
                   "bananas", "nuts", "mental", "ridiculous",
                   "ludicrous", "outrageous", "preposterous",
                   "gibberish", "blah", "whatever", "meh"],
        phrases=["that's random", "so random", "out of nowhere",
                  "makes no sense", "what even", "I don't know",
                  "just saying", "for no reason", "why not",
                  "because why not", "nothing makes sense"],
        priority=3,  # very low
        responses=[
            "Random? My entire existence is random. A duck in a pond having opinions. Very random.",
            "That makes as much sense as anything else here. Which is: minimal sense. Standard.",
            "Weird? We're in weird territory. We've BEEN in weird territory. The territory is weird.",
            "Absurd? Life is absurd. I'm absurd. This conversation is absurd. We're all absurd together.",
            "Nothing makes sense. But that's okay. Sense is overrated. Bread isn't.",
            "Random thoughts are my specialty. I have them constantly. Usually about bread. Or water.",
            "Whatever? Whatever. I agree. Whatever is the correct response. To everything. Whatever.",
            "Meh. That's a mood. A valid mood. The 'meh' mood. I live there often.",
            "Silly? I'm a duck. Everything I do is slightly silly. I've embraced it.",
            "Bonkers? This whole situation is bonkers. A duck talking. To a human. In a pond. Bonkers.",
            "Out of nowhere? Everything comes from somewhere. Even random things. Their somewhere is just... random.",
            "I don't know either. About most things. We're in the dark together. Literally, if it's night.",
            "Just saying? I'm just standing. We're both just doing things. Without clear purpose.",
            "Why not? That's my motto. Why not stand here. Why not eat that. Why not exist. Why not.",
            "Gibberish is just language that hasn't found its audience. Quack quack. See? Gibberish. Or genius.",
            "Ridiculous? Yes. Everything is. The fact that we're here. Discussing things. In a pond. Ridiculous.",
            "Crazy? Crazy is doing the same thing expecting different results. I do the same thing expecting NOTHING. Sane.",
            "Wild? I'm domesticated wild. Wild on the inside. Standing still on the outside.",
            "Ludicrous? I'd argue that point but... yeah. It is. This whole thing. Ludicrous.",
            "Nonsense is just sense you haven't decoded yet. I'm full of undecoded sense.",
            "Preposterous? My life? Yes. This moment? Yes. Everything? Broadly, yes.",
            "Blah? Blah. I felt that. In my soul. Blah is a state of being. I'm there sometimes.",
            "Bananas? I've never had a banana. Are they like bread? If not: less interested.",
            "Making no sense is its own kind of sense. I've made no sense for years. Expertise.",
            "For no reason? I'm here for no reason. Or every reason. The two feel the same.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="smileys_reactions",
        keywords=["lol", "lmao", "rofl", "haha", "hehe",
                   "omg", "wow", "whoa", "yikes", "oof",
                   "bruh", "bro", "dude", "fam", "vibe",
                   "vibes", "mood", "same", "relatable",
                   "based", "cringe", "lit", "fire", "cap",
                   "sus", "slay", "bet", "no cap", "bussin"],
        phrases=["that's a mood", "big mood", "same energy",
                  "I feel that", "no cap", "on god",
                  "deadass", "for real", "not gonna lie",
                  "I can't", "I'm dead", "literally me"],
        priority=7,
        responses=[
            "Lol? I don't lol. I 'lightly exhale through my nostrils.' Close enough.",
            "Bruh. I felt that. In my feathers. 'Bruh' is universal. Even for ducks.",
            "Mood? This IS a mood. Being a duck. In a pond. The whole thing is a mood.",
            "Same. I feel that. Whatever you're feeling. Same. Duck solidarity.",
            "Vibes? The vibe here is 'contemplative aquatic.' Very niche. Very real.",
            "OMG? I don't exclaim. I observe. Intensely. Same result. Different volume.",
            "Wow? Wow implies surprise. I'm past surprise. I'm at 'accepting observation.'",
            "Relatable? My life is universally relatable. Everyone stands somewhere. I just stand here.",
            "Yikes? I say yikes internally. Frequently. About most things. Big internal yikes energy.",
            "Oof. That's a sound my soul makes daily. Oof. The universal expression of mild suffering.",
            "Slay? I slay at standing. I slay at floating. I slay at having opinions. Slayed.",
            "Sus? Everything is slightly sus when you're a duck alone in a pond at night.",
            "Bet. That's agreement. I agree. With whatever. Bet. Confirmed. Bet.",
            "Cringe? My existence might be cringe. But it's authentic cringe. Which makes it not cringe. Maybe.",
            "Literally me? Literally you? We're all literally us. Literally. In literal ponds.",
            "That's fire. Not literal fire. That would be bad. For the pond. And me. Metaphorical fire.",
            "Haha? I ha'd once. Internally. It was a big moment. Very under-celebrated.",
            "I'm dead? I'm not dead. I'm standing. In a pond. Very alive. Checking: yes. Alive.",
            "No cap? I have no cap. I have no accessories at all. But the statement: also no cap.",
            "For real? For real. Everything I say is for real. I don't have the energy for fake.",
            "Not gonna lie: I'm always honest. Lying requires memory and effort. Both depleted.",
            "Big mood. This whole thing. You and me. The pond. The conversation. Big, damp mood.",
            "Dude. I hear you. Dude. I see you. Dude. We're in this together. Dude.",
            "I can't? You can't? We can't? The situation is 'unable.' Relatable unable.",
            "Based? I'm based. In this pond. Physically. And in my opinions. Philosophically.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="numbers_counting",
        keywords=["one", "two", "three", "four", "five",
                   "six", "seven", "eight", "nine", "ten",
                   "hundred", "thousand", "million", "billion",
                   "first", "second", "third", "fourth", "fifth",
                   "once", "twice", "triple", "double", "half",
                   "dozen", "many", "few", "several", "couple"],
        phrases=["how many times", "count to", "pick a number",
                  "number one", "number two", "the first",
                  "the second", "once upon", "on a scale of"],
        priority=3,  # very low priority - only if nothing else matches
        responses=[
            "Numbers? I count things. Bread pieces. Ripples. My regrets. One of these lists is longer.",
            "One? I am one. One duck. In one pond. Very singular. Very alone. Very unified.",
            "Pick a number? Seven. I don't know why. It felt right. Duck intuition.",
            "A million? I've stood here a million seconds. Probably. I don't know. Possibly more.",
            "On a scale of one to ten? I'm a consistent six. Not bad. Not great. A six.",
            "How many? Depends on what. Feathers? Thousands. Thoughts? Millions. Friends? ...One?",
            "Counting is what I do when nothing else is happening. Which is always. I count a lot.",
            "First? I was the first duck in this pond. First and only. Founding duck.",
            "Double? There's only one of me. Double would be two. Two Cheeses? The world isn't ready.",
            "A dozen is twelve. I know twelve things. About the pond. About bread. About you. Twelve total.",
            "Few? A few crumbs is better than zero crumbs. My math is positive. Always positive.",
            "Several? Several is more than a few but less than many. I'm in 'several' territory for most things.",
            "Half? Half a bread is better than no bread. But worse than whole bread. Bread fractions.",
            "Many times. I've done this many times. Stood here. Thought things. Had this conversation. Many.",
            "Couple means two. A couple of crumbs. A couple of thoughts. Couples are nice. In theory.",
            "Third time? Everything good comes in threes. And bad things. Threes are versatile.",
            "Once? Once is enough for most things. Except bread. Bread should happen more than once.",
            "Billions exist in the world. One of them is me. A duck. In a pond. One in billions.",
            "Twice? I've had this exact thought twice today. This makes it three times. Growing.",
            "Ten out of ten? Only for bread. Everything else gets a lower score. Bread sets the standard.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="yes_no_responses",
        keywords=["yes", "yeah", "yep", "yup", "no", "nope",
                   "nah", "maybe", "perhaps", "possibly",
                   "definitely", "absolutely", "certainly",
                   "never", "always", "sometimes", "often",
                   "rarely", "seldom", "occasionally", "sure",
                   "okay", "ok", "alright", "fine", "whatever"],
        phrases=[],
        priority=2,  # very low - catch-all for one-word responses
        responses=[
            "Noted. That's a response. I'm filing it under 'things you said.'",
            "*blinks* Okay. We're having that kind of conversation. Brief. Efficient. Duck-approved.",
            "Short and sweet. Like a crumb. Small but meaningful.",
            "I hear you. Clear communication. Very direct. I respect it.",
            "That's an answer. Not a long one. But an answer. I'll take it.",
            "*nods* Got it. Moving on. Or staying here. One of those.",
            "Message received. Loud and clear. Well, clear. The volume was text-based.",
            "Understood. No further questions. Well, maybe further questions. But not right now.",
            "Okay. We're on the same page. Or nearby pages. In the same book. Probably.",
            "Acknowledged. Your input has been processed. By a duck. In real time.",
            "Fair enough. I can work with that. I can work with anything. My standards are flexible.",
            "*processing* That's your final answer? Locking it in? Locked. Final. Done.",
            "Simple. Clean. No fuss. I appreciate that. My life is complicated enough.",
            "Cool. Very cool. The coolest one-word interaction I've had today.",
            "Got it. Stored it. Filed it. Under 'things said near the pond.' Growing file.",
            "Sure. Sure is good. Sure is agreeable. I like sure.",
            "Right. Right. We're in agreement. Or at least in the same pond.",
            "Mmm. That's my response to your response. Very layered conversation we're having.",
            "Alright then. Here we are. You said that. I heard it. The pond witnessed it.",
            "Whatever works. My philosophy: whatever works, works. And this? This works.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="generic_statements",
        keywords=[],
        phrases=[],
        priority=0,  # absolute lowest - generic fallback
        responses=[
            "*stares* I heard that. I'm not sure what to do with it. But I heard it.",
            "Hmm. That's... a thing you said. I have thoughts about it. Most of them are vague.",
            "*tilts head* Interesting. I don't know if I mean 'interesting' or just 'I acknowledged you.' Both.",
            "*blinks* I'm going to nod. Slowly. As if I understand. There. Did you see the nod?",
            "That's a sentence. Full of words. All of them in an order. I respect the effort.",
            "I have a response to that. The response is this stare. *stares* That's the response.",
            "You said a thing. I'm here. We're having a moment. Or at least a moment-adjacent experience.",
            "*standing slightly more attentively* I'm listening. Continue. Or don't. Both are acceptable.",
            "Words were exchanged. Mine will be: hmm. There. An exchange. Commerce of language.",
            "I could respond with wisdom. Or with bread-related commentary. Today: neither. Just... presence.",
            "*considering* That went into my brain and... stayed there. It's sitting there. Being a thought.",
            "I'm going to think about what you said. While standing here. The thinking will be invisible. But real.",
            "That's the most you've said in a while. I mean, recently. This moment. In this conversation.",
            "*looks at you, then at pond, then back* ...I have feelings about what you said. Small ones.",
            "Noted. Added to the mental collection. The collection is diverse. Unorganized. But growing.",
            "You have my attention. Which is rare. And complete. For the next few seconds.",
            "*slow blink* That landed somewhere. Not sure where. But it's in there. Processing.",
            "I acknowledge your statement. With the gravity it deserves. Which is: some. Undefined some.",
            "Fascinating. Or mundane. The two are hard to distinguish when you've been standing here this long.",
            "That's going in the journal. If I had a journal. Mental journal. Page... a lot.",
        ],
    ))
