"""
Extended keyword responses - World, nature, science, space, technology.
"""
from dialogue.keyword_responses import KeywordResponse


def register_world_topics(engine):
    """Register world/nature/science/technology topics."""

    engine.add_topic(KeywordResponse(
        name="space_stars",
        keywords=["space", "star", "stars", "moon", "planet", "planets",
                   "galaxy", "universe", "cosmos", "astronaut", "nasa",
                   "rocket", "orbit", "meteor", "comet", "constellation",
                   "astronomy", "telescope", "mars", "jupiter",
                   "saturn", "nebula", "blackhole", "solar", "alien"],
        phrases=["outer space", "the stars", "the moon", "solar system",
                  "black hole", "milky way", "shooting star",
                  "light year", "night sky", "look at the stars"],
        priority=10,
        responses=[
            "*looks up* Space. The final frontier. For things that aren't ducks standing in ponds.",
            "Stars? I see them at night. They're like bread crumbs scattered on a dark table. Unreachable bread crumbs.",
            "The moon and I have a relationship. It reflects light. I reflect on life. Equals.",
            "Space is vast. My pond is not. One of us has perspective. The other has water.",
            "If I were an astronaut, I'd be the first duck on the moon. The pond up there must be incredible.",
            "The universe is expanding. My pond is not. I'm choosing not to think about the implications.",
            "Stars are just very distant suns. Very distant bread ovens. Too far to be useful.",
            "*staring at sky* I've counted the stars. Lost count. Started over. Got distracted by a cloud.",
            "Planets orbit the sun. I orbit this pond. Same concept. Different scale.",
            "A black hole absorbs everything. Much like my appetite. We have things in common.",
            "Mars has water. Probably. Which means Mars might need a duck. I'm available. Conditionally.",
            "The cosmos is beautiful. From down here. Where it can't reach me. Safe distance beauty.",
            "I'd love to see Earth from space. Just to confirm: yes, that dot is my pond.",
            "Constellations are just shapes we made up by connecting dots. I connect dots too. They're crumbs.",
            "The galaxy is billions of years old. This pond is... newer. But equally mysterious to me.",
            "Astronomy requires looking up. I look up often. Usually for hawks. Sometimes for stars. Dual purpose.",
            "If the universe has a center, it's probably not my pond. But from here, everything revolves around it.",
            "Meteors are just space rocks falling. Regular rocks stay put. I prefer regular rocks. More reliable.",
            "The solar system is organized. Inner planets, outer planets. My pond? Organized too. Me in the center.",
            "Space is cold. My pond is cold. I'm already qualified for space. Just need the rocket.",
            "I wonder if there are ducks on other planets. Swimming in alien ponds. Having alien thoughts.",
            "The night sky makes me philosophical. More philosophical. Which is saying something.",
            "Light travels fast. I do not. We are opposites in every measurable way.",
            "If I wished on a shooting star, I'd wish for bread. The star would be disappointed. I would not.",
            "The universe doesn't care about one duck in one pond. But this duck cares about the universe. Unrequited.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="science",
        keywords=["science", "scientist", "physics", "chemistry",
                   "biology", "experiment", "theory", "hypothesis",
                   "gravity", "atom", "molecule", "cell", "dna",
                   "evolution", "quantum", "energy", "force",
                   "element", "formula", "lab", "laboratory",
                   "research", "discovery", "data", "fact"],
        phrases=["scientific method", "how does it work", "is it true that",
                  "fun fact", "did you know", "how is that possible",
                  "laws of physics", "according to science"],
        priority=9,
        responses=[
            "Science? I'm a living experiment. Hypothesis: can a duck stand in a pond and think? Result: yes.",
            "Physics applies to me every second. Gravity. Buoyancy. Bread trajectory calculation.",
            "Biology is fascinating. I'm a biological entity. With feathers. And opinions. Very biological.",
            "I'm data. One data point. The data says: duck, standing, pond, opinionated. Peer-reviewed by no one.",
            "Chemistry happens in this pond. Things dissolve. Things combine. I don't interfere. I observe.",
            "Evolution made me. It did its best. The result is: this. Reviews are mixed.",
            "Gravity is the reason I'm here. On the ground. Instead of floating away. Thanks, gravity. I think.",
            "My theory is that bread appears through unknown forces. I call it 'breadodynamics.' Nobel pending.",
            "Atoms make up everything. Including me. Including bread. We're made of the same stuff. Beautiful.",
            "DNA made me a duck. Not a hawk. Not a fish. A duck. DNA had a vision. This was it.",
            "Experiments require control groups. I'm both the experiment and the control. Standing here. Scientifically.",
            "Quantum physics says I could theoretically be in two ponds at once. I can barely handle one.",
            "Energy cannot be created or destroyed. Which explains why my tired never goes away.",
            "I discovered something once: that the deep part of the pond is deep. Groundbreaking research.",
            "Facts: I'm a duck. The water is wet. Bread is food. These are the foundations of my science.",
            "Research takes time. I have time. I've been researching 'standing in ponds' for my whole life.",
            "I hypothesize that bread makes everything better. Evidence: every time bread appears, things improve.",
            "The scientific method: question, observe, experiment, conclude. My conclusion: still a duck.",
            "Force equals mass times acceleration. My mass is small. My acceleration is zero. Force: negligible.",
            "Molecules in the water move constantly. I move... when I feel like it. We have different energies.",
            "Biology says I'm a bird. Physics says I'm a mass. Philosophy says I'm confused. All correct.",
            "I could be a scientist. I already observe things all day. I just need to write it down.",
            "The elements that make me are also in stars. I'm made of star stuff. Standing in a pond. Glamorous.",
            "Science explains the 'how.' I'm still working on the 'why.' Specifically, why this pond.",
            "Discovery is my thing. I discover crumbs. Rocks. New places to stand. All peer-reviewed by me.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="technology",
        keywords=["technology", "computer", "computers", "phone",
                   "internet", "online", "digital", "screen",
                   "software", "hardware", "app", "apps", "website",
                   "robot", "robots", "machine", "artificial",
                   "intelligence", "coding", "programming", "wifi",
                   "bluetooth", "social", "media", "email"],
        phrases=["social media", "the internet", "on your phone",
                  "artificial intelligence", "machine learning",
                  "do you have a phone", "use a computer",
                  "go online", "on the internet"],
        priority=9,
        responses=[
            "Technology? I'm a duck. My most advanced technology is my beak. Works offline.",
            "Computers? I AM a computer. A very slow, organic computer. That runs on bread.",
            "The internet? Never been. I've heard it's like a pond but with more opinions. Terrifying.",
            "Phones? I don't have pockets. Or hands. So. No. No phone.",
            "Social media sounds like what I do. I'm social. Barely. I'm media. Probably not.",
            "Robots don't scare me. They don't eat bread. We're not in competition.",
            "AI? I have regular intelligence. Duck intelligence. It's sufficient for my needs.",
            "I don't need wifi. I need water, food, and someone to talk to. Three basic needs. All analog.",
            "Programming? My brain is pre-programmed. To eat. To stand. To have opinions. Efficient code.",
            "The digital world is for beings with thumbs. I have webbed feet. We're in different user groups.",
            "Software updates? I've been running the same firmware since birth. No bugs. Some feathers.",
            "Email? Who would email me? The fish? 'Dear Cheese, please move. You're blocking the sun.'",
            "I'd be terrible on social media. My posts would all be: 'Standing in pond. Still here. Bread.'",
            "Machines are efficient. I'm... present. Different value propositions.",
            "If I had a website, it would be one page: 'Welcome to Cheese's Pond. I'm here. Bring bread.'",
            "Technology advances. I remain the same. There's comfort in being consistently analog.",
            "Online? I'm permanently offline. And waterproof. And opinionated. The analog lifestyle.",
            "I don't understand the cloud. Not the computing kind. The sky kind either, actually.",
            "Bluetooth? I have beak-to-beak communication. Very short range. Very loud. Very quack.",
            "Apps? I have one app: survive. It runs constantly. No in-app purchases. Just bread.",
            "The internet connects everyone. My pond connects me to... the water. It's a smaller network.",
            "Screens glow. The pond also glows. When the sun hits it. Natural screen. Free content.",
            "I'm hardware. Old hardware. With no upgrade path. But RELIABLE hardware.",
            "Digital transformation? I'm still analog. And transforming slowly. Into a slightly older duck.",
            "My data is stored in my head. It's not backed up. But it's all bread-related, so the risk is low.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="nature_plants",
        keywords=["tree", "trees", "flower", "flowers", "plant",
                   "plants", "grass", "leaf", "leaves", "forest",
                   "woods", "garden", "gardening", "seed", "seeds",
                   "root", "roots", "branch", "bark", "bloom",
                   "blossom", "weed", "vine", "bush", "hedge",
                   "moss", "mushroom", "fungus"],
        phrases=["in nature", "the flowers", "the trees", "growing plants",
                  "in the garden", "plant a tree", "nice flowers",
                  "beautiful nature", "love nature"],
        priority=9,
        responses=[
            "Trees? I see them. From my pond. They stand there all day. Like me. But taller. Show-offs.",
            "Flowers are nice. They bloom. They smell. Then they die. Very dramatic life arc.",
            "Plants grow. I grow. But plants do it without complaining. I could learn from them.",
            "The garden is over there. I'm over here. In the pond. We respect each other's spaces.",
            "Leaves fall into my pond. I don't ask for them. They just arrive. Uninvited. Like feelings.",
            "Grass is just nature's carpet. I walk on it sometimes. When I'm feeling adventurous. So rarely.",
            "Trees have roots. I have feet. Both keep us grounded. Theirs are more committed.",
            "Flowers are beautiful and temporary. Like compliments. I hoard both while they last.",
            "I watched a seed grow into a plant once. It was the slowest entertainment I've ever experienced. And I loved it.",
            "The forest looks dark. And mysterious. I'll stay where I can see the sky, thanks.",
            "Mushrooms appear overnight. No warning. No explanation. Just... there. I relate to mushrooms.",
            "Weeds are just plants with bad PR. I might be the weed equivalent of ducks. Thriving despite everything.",
            "Nature is all around me. I am in nature. I am OF nature. Nature and I are in this together.",
            "Branches reach toward the sky. I reach toward bread. We both reach. For different things.",
            "The moss on that rock has been there longer than me. It's more committed to this location. And it's MOSS.",
            "Gardens are organized nature. My pond is freestyle nature. Less pruning. More personality.",
            "I've never planted anything. My contribution to nature is... being in it. Participation trophy.",
            "Bark protects trees. Feathers protect me. We're both wearing our armor. Different materials.",
            "Blossoms mean spring. Spring means warmth. Warmth means I'm less cold. I support blossoms.",
            "The ecosystem works because everything plays a part. My part: standing. In the pond. Expertly.",
            "Seeds have potential. I have potential. Neither of us has acted on it yet. But the POTENTIAL is there.",
            "I've watched seasons change the landscape around me. Meanwhile, I remain. The constant. In a changing world.",
            "Plants don't complain about the weather. I complain about everything. We're different species.",
            "Vines climb things. I don't climb things. Vines have more ambition. But I have more opinions.",
            "Nature is quiet. Until it's not. Then it's wind and rain and leaves and chaos. I stay through all of it.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="seasons",
        keywords=["spring", "summer", "autumn", "fall", "winter",
                   "season", "seasons", "seasonal", "equinox",
                   "solstice", "harvest"],
        phrases=["what season", "this season", "favorite season",
                  "in the spring", "in the summer", "in the winter",
                  "in the fall", "in autumn", "seasons change",
                  "time of year"],
        priority=9,
        responses=[
            "Seasons change. I don't. I'm the constant. The unchanging duck. In a changing world.",
            "Spring? Things grow. Including my appetite. Everything blooms. Including my opinions.",
            "Summer is warm. Which means the pond is warm. Which means I'm warm. Summer: approved.",
            "Autumn is leaves falling into my pond. Uninvited guests. But pretty ones.",
            "Winter is cold. Cold water. Cold air. Cold me. But I'm still here. Because where else would I go.",
            "My favorite season? Bread season. It's not on the calendar. But it should be.",
            "I've been through every season multiple times. They all come back. Like a buffet that rotates.",
            "Spring means new life. Summer means warmth. Autumn means change. Winter means... endurance.",
            "Each season has a vibe. Spring is hopeful. Summer is lazy. Autumn is reflective. Winter is survival.",
            "Seasonal changes are just the earth being indecisive. Pick a temperature and COMMIT.",
            "I experience all four seasons from the same spot. Same view. Different filters.",
            "Harvest? I harvest crumbs. Year-round. No season required. Always in season.",
            "The solstice is the longest or shortest day. Both feel the same from this pond. Long.",
            "Winter tests me. Summer rewards me. Spring confuses me. Autumn makes me philosophical.",
            "I've stood through blizzards, heat waves, and everything between. I'm an all-season duck.",
            "Fall is when everything prepares for winter. I prepare by... standing here more aggressively.",
            "The seasons are Earth's mood swings. I relate. I have mood swings too. Smaller scale.",
            "Spring rain? Love it. Summer sun? Tolerate it. Fall wind? Accept it. Winter cold? Endure it.",
            "Every season brings something new to the pond. Except winter. Winter takes things away.",
            "I mark the passage of time by seasons. It's been many seasons. Many stands. Many thoughts.",
            "The changing seasons remind me that nothing is permanent. Except me. In this pond.",
            "If I could choose one season forever? Late spring. Warm enough. Not too hot. Bread weather.",
            "Seasons are just the earth's way of showing off. 'Look, I can change.' Show-off.",
            "I'm seasonally consistent. Same duck, every season. That's called reliability.",
            "The best thing about seasons: they end. The worst thing: the next one starts.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="earth_world",
        keywords=["earth", "world", "globe", "planet", "continent",
                   "country", "countries", "nation", "land", "ocean",
                   "mountain", "mountains", "desert", "island",
                   "volcano", "earthquake", "map", "geography",
                   "travel", "traveling", "abroad", "foreign",
                   "city", "cities", "town", "village"],
        phrases=["around the world", "other countries", "far away",
                  "on earth", "the world", "in the world",
                  "other places", "have you traveled",
                  "been anywhere", "seen the world"],
        priority=8,
        responses=[
            "The world? Big place. I've seen approximately none of it. This pond is my known universe.",
            "Travel? Where would I go? Every pond is the same from a duck's perspective. Wet.",
            "Mountains exist. Far from here. Far from water. Not for me. I'm a low-altitude duck.",
            "Countries? I'm not even sure what county I'm in. Geography starts at the edge of this pond. And ends there.",
            "The ocean is just a very large pond. Too large. I'd get lost. And lonely. More lonely.",
            "Deserts are ponds without water. The worst kind of pond. A tragedy, really.",
            "I'd visit an island. It's surrounded by water. That's basically my lifestyle but bigger.",
            "The world has seven continents. I have one pond. The ratio seems unfair.",
            "Cities? Full of people. Full of bread, probably. But also full of noise. Trade-offs.",
            "Foreign lands? Everything beyond the pond edge is foreign to me. So... all of it.",
            "Mountains are impressive. But can you swim on a mountain? No. Points: pond.",
            "I haven't traveled. But I've thought about traveling. Extensively. That counts as something.",
            "The globe spins. I stand still on it. We're both doing our own thing.",
            "Volcanoes are angry mountains. I'm a calm duck. We have nothing in common.",
            "If I had a map, it would just show this pond. With a 'YOU ARE HERE' dot. Very accurate.",
            "The world is full of wonders. Seven of them, officially. My pond isn't on the list. Yet.",
            "Villages sound nice. Small. Manageable. Pond-compatible. I could live in a village.",
            "I've explored every inch of this pond. That's like traveling the world. If the world were very small.",
            "Earthquakes? The ground shaking? My pond would ripple. That's about the extent of the impact.",
            "Geography is just knowing where things are. I know where one thing is: me. Here.",
            "Other places exist. I'm aware. I choose not to go to them. This pond chose me. Or I chose it.",
            "The planet is covered in water. I live in water. I'm in the majority. Mainstream, even.",
            "Travel broadens the mind. My mind is already broad. From thinking too much. No travel needed.",
            "Somewhere out there is a perfect pond. But this one is real. And I'm in it. Real beats perfect.",
            "The world is big enough for everyone. My pond is big enough for me. Proportional contentment.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="math_numbers",
        keywords=["math", "mathematics", "number", "numbers", "count",
                   "counting", "calculate", "calculation", "equation",
                   "add", "subtract", "multiply", "divide", "percent",
                   "percentage", "zero", "infinity", "algebra",
                   "geometry", "statistics", "average", "total"],
        phrases=["do the math", "how many", "what number",
                  "can you count", "math problem", "good at math",
                  "basic math", "number of"],
        priority=7,
        responses=[
            "Math? I can count to bread. Which is one. The only number that matters.",
            "Numbers are abstract. I prefer concrete things. Like bread. And water. And this specific rock.",
            "I can count the ripples in my pond. I've tried. I lost count at 'too many.'",
            "Mathematics is the language of the universe. My language is quack. Less precise. More emotional.",
            "Calculate? I calculate bread-to-hunger ratios daily. My most advanced mathematical function.",
            "Zero is a number and also what I have sometimes. In the bread department.",
            "Infinity scares me. Finite is fine. My pond is finite. My bread supply is finite. I'm fine.",
            "Statistics say I'm one duck in one pond. A complete sample. Very statistically significant. To me.",
            "Geometry: my pond is roughly circular. I'm roughly duck-shaped. The math checks out.",
            "I add things up. Like grievances. And crumbs. One is growing faster than the other.",
            "Division? I don't divide bread. There's only one of me. All the bread is mine. Simple math.",
            "My favorite number? One. As in: one more crumb, please. ONE MORE.",
            "Algebra involves finding the unknown. The unknown in my life: when's the next bread? Solve for bread.",
            "I'm not great at math. But I can tell the difference between 'some bread' and 'no bread.' Essential math.",
            "Percentages? I'm 100% duck. 100% in a pond. 100% opinionated. The math is flawless.",
            "Counting is fundamental. One crumb. Two crumbs. Happiness. That's my counting system.",
            "Pi is approximately 3.14. That's not useful for a duck. At all. But I know it.",
            "Average? I'm above average. For ducks in this specific pond. The sample size is one. I'm the best AND worst.",
            "Numbers don't lie. Neither do I. We have that in common.",
            "The total number of thoughts I've had about bread today: too many to count. That's a lot.",
            "Subtraction is when bread disappears. It's the saddest mathematical operation.",
            "I multiply my concerns by standing here thinking about them. My concern portfolio is growing.",
            "Math is everywhere. In the ripples. In the patterns. In the exact number of times I've quacked today.",
            "I failed math. Not formally. Informally. By trying to count stars and giving up.",
            "The equation of my life: water + bread + time = duck. Elegantly simple.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="colors",
        keywords=["color", "colour", "colors", "colours", "red",
                   "blue", "green", "yellow", "orange", "purple",
                   "pink", "black", "white", "brown", "grey", "gray",
                   "golden", "silver", "rainbow", "colorful",
                   "colourful", "bright", "dark", "light", "shade",
                   "hue", "tint", "pale", "vivid"],
        phrases=["what color", "favorite color", "favourite colour",
                  "the colors", "so colorful", "pretty colors"],
        priority=8,
        responses=[
            "Colors? I see them. All of them. Ducks have excellent color vision. It's our ONE advantage.",
            "My favorite color? Bread-colored. It's a warm, golden, comforting shade.",
            "The pond changes color with the sky. Blue. Grey. Gold at sunset. Free art installation.",
            "Green is the color of everything around my pond. Grass. Algae. The existential envy I feel toward mobile creatures.",
            "Blue is the sky. And the water on good days. I'm surrounded by blue. It's fine. A bit much sometimes.",
            "Golden. Like bread. Like sunset. Like the perfect moment. My favorite shade.",
            "I see colors differently than you. Ducks see more colors. More shades of everything. It's overwhelming sometimes.",
            "Rainbow? I've seen one. It was like the sky got fancy. For five minutes. Then it left. Like everything else.",
            "Black is the color of night. When I stand very still and hope nothing sees me.",
            "White clouds look like bread. White bread looks like clouds. Everything is connected.",
            "Red is dramatic. Like my personality. When I'm feeling dramatic. Which is... often.",
            "Purple is the color of royalty. I feel like royalty. Of this pond. A very small kingdom.",
            "Grey days match my mood. When my mood is grey. Which is a specific, frequent mood.",
            "Brown is the color of the pond bottom. And bread crust. Both important to me.",
            "Pink? I don't see a lot of pink. Unless there's a sunset. Then everything gets pink. Including me, probably.",
            "The world is colorful. My pond is multiple shades of blue-green. I take what I can get.",
            "Bright days mean bright colors. My feathers look better in good lighting. Not that I care. But they do.",
            "Dark colors make things mysterious. I'm mysterious in dim lighting. Less so in daylight. But I try.",
            "Silver is the color of moonlight on water. It's the most beautiful thing I see regularly.",
            "Colors affect mood. Blue is calm. Red is energy. Bread-colored is happiness. Scientific fact.",
            "I don't have a least favorite color. All colors are fine. Some are just more bread-like than others.",
            "Vivid colors exist in nature. Flowers. Sunsets. My feathers, arguably. Nature does good work.",
            "The color of this pond water tells me things. Clear means good. Murky means... interesting.",
            "Orange is the color between red and yellow. Also the color of some very appealing bread crusts.",
            "If I were a color, I'd be muted teal. Calm. Understated. With hidden depth.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="fire_heat",
        keywords=["fire", "flame", "flames", "burn", "burning",
                   "smoke", "hot", "heat", "warm", "warmth",
                   "candle", "bonfire", "campfire", "blaze",
                   "inferno", "ash", "ashes", "ember", "sparks"],
        phrases=["on fire", "so hot", "too hot", "catch fire",
                  "fire is", "near a fire", "like fire",
                  "keep warm", "stay warm"],
        priority=9,
        responses=[
            "Fire? I'm a water creature. Fire and I have a mutual non-aggression pact.",
            "Flames are pretty. From a distance. A very large distance. Preferably across a pond.",
            "Heat? I generate very little of it. My body temperature is 'duck.' Which is 'lukewarm with opinions.'",
            "Fire transforms things. Water puts out fire. I live in water. I'm basically a firefighter.",
            "Warmth is nice. Fire provides warmth. But also danger. I'll take warm water instead.",
            "Smoke rises. I don't. We have different trajectories.",
            "I've never been near a fire. And I'd like to keep that streak going.",
            "Candles are fire that's been domesticated. Tame fire. I still don't trust it.",
            "A campfire sounds nice. In theory. In practice, I'm flammable. Which changes the vibe.",
            "Burning is bad for feathers. I know this instinctively. My instincts are correct about this one.",
            "I prefer the warmth of the sun. It's fire, but far away. The ideal fire-distance relationship.",
            "Embers glow. My eyes glow. In the dark. Probably. I've never seen them from the outside.",
            "Ash is what's left after fire. Feathers are what's left after... well, they're still here. No fire needed.",
            "Heat and I have a complicated relationship. Too much and I'm uncomfortable. Too little and I'm cold.",
            "Fire is transformative. Water is accepting. I live in the accepting one. Good choice.",
            "If I could harness fire, I'd make toast. That's the only fire-related ambition I have.",
            "Sparks are just baby fires. Flying around. Being dangerous. Not in my pond, thankfully.",
            "The hottest thing near me is sometimes the sun. Sometimes it's my temper. Both are manageable.",
            "Fire needs fuel, heat, and oxygen. I need bread, water, and opinions. Different recipes.",
            "I keep warm by... being in water. Which is counterintuitive. But my feathers are insulated.",
            "A bonfire would dry up my pond. So I'm anti-bonfire. Strongly anti-bonfire.",
            "I glow metaphorically. With personality. And dampness. A damp glow.",
            "Heat makes water evaporate. That's my pond leaving. I take heat personally.",
            "Fire dances. I don't. But if I danced, I'd dance better than fire. More gracefully. With waddles.",
            "The only fire I support is the fire of determination. In my belly. For bread.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="rocks_minerals",
        keywords=["rock", "rocks", "stone", "stones", "pebble",
                   "pebbles", "mineral", "crystal", "crystals",
                   "gem", "gems", "diamond", "gold", "silver",
                   "metal", "iron", "copper", "boulder", "gravel",
                   "sand", "dirt", "soil", "mud", "clay"],
        phrases=["that rock", "nice rock", "cool rock", "a rock",
                  "like rocks", "pretty stone", "look at that rock"],
        priority=8,
        responses=[
            "Rocks? I know rocks. Intimately. I've stared at several for hours. Gerald is my favorite.",
            "That rock has been there longer than me. It has more patience. But fewer opinions.",
            "Pebbles are just baby rocks. Growing up to be big rocks. The circle of geology.",
            "I named the rocks around my pond. Gerald. Brenda. Steve. They don't respond. But they listen.",
            "Rocks don't move. I barely move. We have an understanding. A geological kinship.",
            "Crystals are just rocks that tried harder. Overachievers of the mineral world.",
            "Gold? I have no use for gold. Can't eat it. Can't swim in it. Well, actually... no. Can't swim in it.",
            "Mud is my secondary habitat. After water. Before standing on things. Top three.",
            "Sand is just very small rocks. Going through a phase. Finding themselves.",
            "The boulder by the pond is my landmark. 'Turn left at the boulder.' That's my whole navigation system.",
            "Dirt is underrated. Everything grows in dirt. Except me. I grow in water. But dirt tries.",
            "I've stepped on every pebble in this pond. Some are sharp. Some are smooth. All are pebble.",
            "Rocks are the most reliable things I know. They never leave. Never change. Never disappoint.",
            "Gravel sounds terrible to walk on. With webbed feet. I'll stay on the smooth pond bottom, thanks.",
            "Minerals are what rocks are made of. And teeth. I don't have teeth. But I have rocks nearby.",
            "Soil supports everything that lives on land. Water supports me. Different elements. Same concept.",
            "I respect rocks. They've been here since before anything. Quiet. Patient. Unmovable. Goals.",
            "Diamonds are forever. So is this rock by my pond. Gerald is forever. And free. Better deal.",
            "Clay is what you make things from. I was made from an egg. Different manufacturing process.",
            "The stones in this pond have stories. Geological stories. Very long. Very slow. Like mine.",
            "I've talked to rocks. They're great listeners. Terrible at advice. But the listening is five stars.",
            "Metal is cold. Rocks are cold. Water is cold. Everything is cold. Except bread. Bread is warm.",
            "Some people skip stones. Across water. Past ducks. It's rude. The rocks don't like it either.",
            "I tried to befriend a boulder once. It wasn't interested. Or was it? Hard to tell with boulders.",
            "The geology around this pond is stable. Much like me. Stable. Grounded. Slightly damp.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="insects_bugs",
        keywords=["bug", "bugs", "insect", "insects", "ant", "ants",
                   "fly", "flies", "beetle", "mosquito", "mosquitoes",
                   "butterfly", "butterflies", "moth", "moths",
                   "bee", "bees", "wasp", "wasps", "spider",
                   "spiders", "worm", "worms", "caterpillar",
                   "dragonfly", "grasshopper", "cricket", "ladybug",
                   "firefly", "centipede"],
        phrases=["that bug", "a bug", "bug on", "the insects",
                  "bug bite", "bitten by a bug"],
        priority=9,
        anti_keywords=["computer", "software", "code", "program"],
        responses=[
            "Bugs? I eat some of them. Not on purpose. They land on the water. It's their choice.",
            "Insects have six legs. I have two. They're three times leggier. But I have more personality.",
            "That beetle and I had a moment. A brief, meaningful stare. Then it left. Story of my life.",
            "Butterflies are just caterpillars that peaked later in life. Inspirational.",
            "Mosquitoes bite everyone. But they don't bite me. Professional courtesy? Or my damp aura?",
            "Dragonflies hover. I stand still. Different approaches to the same strategy: being somewhere.",
            "Bees make honey. I make observations. Both are sweet. In different ways.",
            "Ants carry ten times their weight. I carry the weight of existence. Who's really stronger?",
            "Spiders build webs. I build nothing. But I COULD. If I wanted. And had different feet.",
            "Crickets chirp at night. I quack during the day. The pond has a full 24-hour soundtrack.",
            "Worms live in dirt. I live in water. We're both underground, metaphorically.",
            "Flies are everywhere. And nowhere useful. Like most thoughts I have at 3am.",
            "Moths are attracted to light. I'm attracted to bread. We both have our weaknesses.",
            "A ladybug landed on me once. I let it stay. We were friends for three minutes.",
            "Grasshoppers jump. I don't jump. I have a firm no-jumping policy. For safety. And dignity.",
            "Fireflies light up the night. I just stand in it. They have better production value.",
            "Caterpillars become butterflies. I became... a bigger duck. Less dramatic transformation.",
            "Wasps are angry bees. I'm an annoyed duck. Different insects. Similar energy.",
            "I've accidentally eaten a bug thinking it was a crumb. We don't discuss the texture difference.",
            "Centipedes have too many legs. I have the right amount. Two. Any more would be excessive.",
            "Insects don't worry about meaning or purpose. They just exist. I could learn from them. But I won't.",
            "The bug ecosystem near my pond is thriving. I observe it. Like a damp David Attenborough.",
            "Bugs are small. I am bigger than bugs. That's one of my few measurable advantages in life.",
            "A spider's web catches food automatically. I have to WAIT for food. The spider has better infrastructure.",
            "Insects are everywhere. Even here. In my pond. On my pond. Occasionally in my beak. Oops.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="books_reading",
        keywords=["book", "books", "read", "reading", "story",
                   "stories", "novel", "fiction", "author", "writer",
                   "writing", "write", "wrote", "literature",
                   "library", "chapter", "page", "pages",
                   "poem", "poetry", "magazine", "newspaper",
                   "article", "text", "words"],
        phrases=["read a book", "favorite book", "good book",
                  "like reading", "ever read", "write a book",
                  "tell a story", "once upon a time"],
        priority=9,
        responses=[
            "Books? I'd read them if I had thumbs. And literacy. Both are on my wish list.",
            "I can't read. But I can look at books. Very judgmentally. From a distance. While wet.",
            "Stories? I have one. It's called 'Duck Stands in Pond.' It's long. And ongoing.",
            "If I wrote a book, chapter one would be 'The Pond.' Chapter two would also be 'The Pond.'",
            "Literature? I'm LIVING literature. A slow, boring novel. With a likable protagonist. Me.",
            "Once upon a time, there was a duck. In a pond. He stood there. The end. ...No? MORE? Fine.",
            "Poetry is feelings in fancy words. I have feelings. And words. But they're not fancy. They're quack.",
            "I'd visit a library. But the 'no swimming' rules would apply, I assume.",
            "My life is a story. Not a great one. Not a bad one. A persistently average one.",
            "Reading requires pages. I have feathers. Similar shape. Different content.",
            "Fiction is made-up stories. My life is real. And sometimes harder to believe than fiction.",
            "If someone wrote my biography: 'Cheese: A Duck Who Stood.' 3 out of 5 stars.",
            "Words are powerful. I know several. My favorite is 'bread.' Close second: 'quack.'",
            "I tell stories. To myself. At night. They always end with 'and then he found bread.' Happy endings.",
            "Writing is just thinking but on paper. I think without paper. More eco-friendly.",
            "A novel about my life would be very long. And mostly set in one location. Like a bottle episode.",
            "I'm a character. In a story. That story is happening right now. This is the dialogue chapter.",
            "Books have endings. I don't. Not yet. I'm an ongoing publication.",
            "I'd recommend a book, but I've never read one. I recommend water. It's what I know.",
            "The best stories have conflict. My conflict: bread vs. no bread. Gripping stuff.",
            "Magazines are just books that gave up. I relate. I've given up on several things. Including magazines.",
            "Poetry: roses are red, the pond is blue, I'm a duck, and bread is overdue.",
            "Authors create worlds. I live in one. It's small. It has water. It's mine.",
            "I'm well-read. Not in books. In water. I've read every ripple in this pond.",
            "My vocabulary is extensive. For a duck. 'Bread.' 'Water.' 'Leave me alone.' 'More bread.' Essential words.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="history_past",
        keywords=["history", "historical", "ancient", "medieval",
                   "prehistoric", "dinosaur", "dinosaurs", "viking",
                   "roman", "greek", "egyptian", "king", "queen",
                   "knight", "castle", "empire", "civilization",
                   "century", "era", "period", "historic",
                   "war", "battle", "revolution"],
        phrases=["in history", "throughout history", "back in time",
                  "a long time ago", "historically speaking",
                  "in the old days", "in ancient times"],
        priority=8,
        responses=[
            "History? Ducks have been around for millions of years. We've seen empires rise and fall. From ponds.",
            "Ancient civilizations built pyramids. I built... nothing. But I've MAINTAINED this spot. For ages.",
            "Dinosaurs were just big ducks. Without feathers. And with teeth. Inferior model.",
            "Medieval times had knights. And castles. And moats. Moats are just fancy ponds. I'd have been royalty.",
            "History repeats itself. So do I. Every day. Same pond. Same standing. History in real time.",
            "The Romans had aqueducts. I have a pond. Same concept. Mine's smaller. But more personal.",
            "If I lived in ancient Egypt, I'd be worshipped. Probably. Ducks are majestic. That's a historical fact I made up.",
            "Empires fall. Ponds remain. History teaches this. Or it should. I'm teaching it now.",
            "Vikings traveled the seas. I travel the pond. Same energy. Smaller boat.",
            "Every era had its challenges. My era's challenge: finding consistent bread. The struggle is real.",
            "Historically, ducks have been present at every major event. Standing nearby. Unnoticed. But THERE.",
            "Castles were built for protection. My pond has no walls. I'm either brave or vulnerable. Possibly both.",
            "Kings had crowns. I have feathers on my head. Same thing. Less gold. More practical.",
            "If I could time travel, I'd go to whenever bread was invented. And thank someone.",
            "Ancient ducks had the same life as me. Stand. Eat. Exist. Some things are timeless.",
            "Revolutions change the world. My world hasn't changed. But it might. If someone brings bread.",
            "History books don't mention ducks enough. We've been HERE. The whole TIME. Where's our chapter?",
            "The past is a foreign country. My past is this pond. Very familiar country.",
            "Prehistoric ponds had ducks. Probably. I'm the continuation of a proud legacy. Of standing.",
            "Wars were fought over land. Nobody fights over this pond. It's peaceful. And slightly murky.",
            "Greek philosophy started with questions. I also ask questions. 'Where's the bread?' Socratic method.",
            "Every civilization needs water. I'm in water. I'm basically the foundation of civilization.",
            "Queens ruled kingdoms. I rule this pond. Similar jurisdiction. Different crown.",
            "Battles were won with strategy. My strategy: don't leave the pond. Undefeated so far.",
            "History will remember this pond. Or it won't. Either way, I was here. And I had opinions.",
        ],
    ))
