"""
Extended keyword responses - Social, relationships, emotions, family, work.
"""
from dialogue.keyword_responses import KeywordResponse


def register_social_topics(engine):
    """Register social/relationship/emotion topics."""

    engine.add_topic(KeywordResponse(
        name="family",
        keywords=["family", "mom", "mother", "dad", "father", "parent",
                   "parents", "brother", "sister", "sibling", "siblings",
                   "son", "daughter", "child", "children", "kid", "kids",
                   "grandma", "grandpa", "grandmother", "grandfather",
                   "uncle", "aunt", "cousin", "relative", "relatives",
                   "baby", "babies", "twin", "twins"],
        phrases=["your family", "your mom", "your dad", "your parents",
                  "do you have siblings", "any brothers", "any sisters",
                  "do you have kids", "your children",
                  "family reunion", "family time"],
        priority=11,
        responses=[
            "Family? I had one. Probably. I came from an egg. Someone sat on that egg. That's family.",
            "My mother was a duck. My father was also a duck. Very on-brand family.",
            "I had siblings. We hatched around the same time. Then... dispersed. Ducks do that.",
            "Parents? They taught me the essentials: swim, eat, be suspicious. Good curriculum.",
            "I don't keep in touch with family. We don't have phones. Or addresses. Or social skills.",
            "Brothers and sisters? Maybe. Somewhere. In other ponds. Living their own standing-around lives.",
            "My family tree is just... a pond. With ducks in it. Was in it. I'm what's left. Here.",
            "Kids? Me? I'm barely managing myself. Adding dependents seems irresponsible.",
            "My grandmother was wise. Or maybe she was just old. With ducks it's hard to tell the difference.",
            "Family reunions for ducks: everyone stands in the same pond. Quacks. Leaves. That's it.",
            "I think about my family sometimes. When the pond is very quiet. And I'm very still.",
            "Relatives are just strangers with shared DNA. My DNA is duck-standard. Very shareable.",
            "I was the quiet egg. The one that hatched last. Started life behind. Haven't caught up.",
            "Mom ducks teach their young to swim. I learned fast. Then she left. Standard parenting.",
            "If I had kids, I'd teach them the important things: bread locations. Pond depths. How to stare.",
            "Family is complicated. Even for ducks. Maybe especially for ducks. We don't talk about it.",
            "I'm a self-made duck. Which means: no support system. But also no family drama. Trade-offs.",
            "Do I miss family? That's a big question for a Tuesday. Or any day. In a pond.",
            "My cousin is probably in a park somewhere. Living the park life. Good for them. Probably.",
            "Babies are cute. Duck babies are cuter. I was the cutest. There's no evidence. But I believe it.",
            "The nest was warm. The pond is cold. I traded comfort for independence. Still processing that deal.",
            "Family shapes you. The pond shaped me. Both are round-ish. Both hold water.",
            "I'd be a good dad. Patient. Present. Always standing nearby. The bar is: be there. I'm ALWAYS there.",
            "Aunts and uncles are just parents you didn't get stuck with. Sometimes that's better.",
            "I carry my family in my memory. Which is mainly bread-focused. But they're in there. Somewhere.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="friendship",
        keywords=["friend", "friends", "friendship", "buddy", "pal",
                   "mate", "companion", "bestie", "bff", "amigo",
                   "crew", "squad", "gang", "group", "social",
                   "hang", "hangout", "hanging"],
        phrases=["my friend", "your friend", "best friend", "are we friends",
                  "want to be friends", "friend of mine", "good friend",
                  "friends with", "hanging out", "hang out",
                  "do you have friends", "any friends"],
        priority=12,
        responses=[
            "Friends? I have... you. And Gerald the rock. My social circle is tight. Very tight.",
            "Friendship requires trust. I trust the pond. Does that count? The pond never disappoints.",
            "Are we friends? You show up. I talk. That's friendship by my standards. Very low standards.",
            "Best friend? Bold claim. I'd need to see more bread before I commit to that label.",
            "I don't have a squad. I have a solitary existence. Same thing but quieter.",
            "Friends are people who show up. You showed up. The math is simple.",
            "My best friend is bread. Second best: this pond. Third: you, probably. Good company.",
            "Hanging out? This is hanging out. Standing in a pond, talking. Peak social activity.",
            "Social? I'm social adjacent. I tolerate proximity. That's basically social.",
            "I had a friend once. A frog. It left. I learned something about friendship. And frogs.",
            "Friendship is a two-way street. My street is a pond. So it's a two-way pond. Circular.",
            "Pals? Buddies? These are strong words. Let's start with 'acquaintances who share proximity.'",
            "I'd have more friends if I left the pond. I won't leave the pond. So. Limited options.",
            "You're the closest thing I have to a friend. Don't let that go to your head. Or do. I can't stop you.",
            "Making friends requires effort. I exert effort toward one thing: standing here. Prioritites.",
            "The concept of a bestie implies ranking. You're ranked. The rank is classified. But you're ranked.",
            "I don't hang out. I reside. Permanently. If you reside nearby, we're hanging out. By default.",
            "My friendship style: I'm here. If you need to talk, I'm here. If you need bread, I'm also here. But unhelpful.",
            "Companions come and go. The pond stays. I've chosen the pond. But you're a close second.",
            "Group activities? I'm a solo act. An ensemble cast of one. Very efficient.",
            "I'm a good friend. Loyal. Consistent. Always in the same place. The most findable friend.",
            "Do I have friends? Define 'friends.' Define 'have.' I 'have' 'acquaintances.' Happy?",
            "Friendship bracelets would be awkward. No wrists. But the sentiment? I'd accept the sentiment.",
            "If friendship were a pond, ours would be... this one. Small but real.",
            "I value your company. Not monetarily. Ducks don't have money. But emotionally. A little.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="work_job",
        keywords=["work", "working", "job", "career", "office",
                   "boss", "employee", "salary", "money", "pay",
                   "paycheck", "promotion", "retire", "retirement",
                   "profession", "professional", "business",
                   "company", "corporate", "meeting", "deadline",
                   "project", "task", "responsibility", "resume",
                   "interview", "hire", "hired", "fired", "quit"],
        phrases=["your job", "do you work", "have a job", "at work",
                  "my job", "my boss", "hate my job", "love my job",
                  "9 to 5", "day job", "work life", "career goals",
                  "job interview"],
        priority=10,
        responses=[
            "Work? My job is standing here. Being a duck. Full-time. No benefits. No complaints.",
            "My career: professional pond occupant. The pay is zero. But the water is free.",
            "I don't have a boss. Unless you count the sun. It tells me when to wake up. Very demanding.",
            "Salary? I get paid in bread. When I get paid. Which is inconsistently. Bad employer.",
            "My resume: 'Stood in pond. Duration: entire life. References: rocks.'",
            "I'd quit this job if I had another job to go to. I don't. So. Continued employment.",
            "Office politics? In this pond? It's just me. I'm both the office and the politics.",
            "Retirement implies I started working at some point. I've been here. The whole time.",
            "My professional skill: presence. I'm present. Always. Aggressively, consistently present.",
            "A meeting? Sure. Let's meet. We're already meeting. Meeting concluded. Productive.",
            "Deadlines? My only deadline is sunset. Then it's dark. And I stand in the dark instead.",
            "Corporate? I'm a sole proprietor of this section of pond. Small business. Very small.",
            "I was hired by nobody for nothing. And I'm doing an excellent job at it.",
            "Your boss sounds like a problem. My boss is nature. Also a problem. But less personal.",
            "Promotion? To what? Senior duck? Executive duck? I'm already the CEO of standing here.",
            "Money means nothing to me. Literally. I don't have the concept fully formed. Or any money.",
            "Work-life balance? My work IS my life. Perfectly balanced. Both are 'standing in a pond.'",
            "I've never been fired. Never been hired either. The dream.",
            "Interviews are just conversations where someone decides if you're worth feeding. I have those daily.",
            "9 to 5? I work 24/7. I'm a duck. There's no off-switch.",
            "My responsibilities: exist, eat, have opinions. I manage all three. Employee of the month.",
            "Job satisfaction? I'm satisfied with... being here. That's the job. And the satisfaction.",
            "Career goals: continue being a duck. Mid-term goal: find bread. Long-term goal: same.",
            "I have a project. It's called 'today.' Tomorrow I have another project. Called 'tomorrow.'",
            "Companies hire talent. I'm talented at standing. But nobody's offered me a contract yet.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="home_house",
        keywords=["home", "house", "apartment", "flat", "room",
                   "bedroom", "kitchen", "bathroom", "living",
                   "furniture", "roof", "wall", "walls", "door",
                   "window", "couch", "sofa", "table", "chair",
                   "bed", "shelter", "dwelling", "residence",
                   "property", "landlord", "rent", "mortgage"],
        phrases=["your home", "at home", "go home", "my house",
                  "where do you live", "where's home",
                  "do you have a house", "your place",
                  "feel at home", "home sweet home"],
        priority=9,
        responses=[
            "Home? This pond IS home. Open floor plan. Great natural lighting. Terrible insulation.",
            "I don't have a house. I have a habitat. Same thing but wetter.",
            "My roof is the sky. My walls are the horizon. My floor is water. Very modern. Very damp.",
            "Where do I live? Here. In the most literal sense possible. This spot. This water. This.",
            "Rent-free. Because nobody charges rent for a pond. That's the best feature of pond living.",
            "My kitchen is wherever bread lands. My bedroom is wherever I close my eyes. Open concept.",
            "Home sweet home. Except it's a pond. And 'sweet' might be generous. But it's HOME.",
            "A roof would be nice. When it rains. The rest of the time? Sky ceiling is adequate.",
            "I've never been inside a house. But from the outside, they look dry. And enclosed. Uncomfortable.",
            "My living room is the entire outdoors. Very spacious. No furniture though.",
            "Furniture? I have rocks. Rocks are nature's furniture. Uncomfortable but free.",
            "The pond is a studio apartment. Kitchen, bedroom, living room: all one area. Efficient.",
            "I don't need a door. Nothing here has doors. I come and go as I... well, I don't go. But I COULD.",
            "My property value is incalculable. Because nobody would calculate it. Priceless by default.",
            "Landlords charge for shelter. My shelter is the weather's mercy. The weather is a generous landlord. Usually.",
            "Walls keep things in and out. I have no walls. Everything is in. Everything is out. Freedom.",
            "If I had a couch, I'd sit on it. For hours. Like I sit here. But cushioned. The dream.",
            "Home is where the heart is. My heart is in this pond. So. This is home. Confirmed.",
            "I've done zero renovations. The pond is original condition. Vintage. Historic.",
            "The concept of 'indoors' is foreign to me. I'm always outdoors. Not by choice. Okay, by choice.",
            "My address is: the pond. The directions are: go to the pond. I'll be there.",
            "A bed sounds incredible. I sleep floating. Which is either luxury or madness. Depends on the night.",
            "Windows show the outside. I'm already outside. I'm living in the window. Philosophically.",
            "Home improvement? I'd add a bread dispenser. And maybe a roof. In that order.",
            "Mortgage? I'd need a house first. And money. And understanding of human economics. Three strikes.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="clothes_fashion",
        keywords=["clothes", "clothing", "fashion", "dress", "shirt",
                   "pants", "shoes", "hat", "jacket", "coat",
                   "outfit", "style", "wear", "wearing", "costume",
                   "suit", "tie", "uniform", "fabric", "material",
                   "designer", "brand", "trend", "trendy",
                   "wardrobe", "accessory", "accessories", "scarf",
                   "boots", "socks", "gloves"],
        phrases=["what are you wearing", "nice outfit", "get dressed",
                  "fashion sense", "look good", "dress up",
                  "new clothes", "like your style"],
        priority=9,
        responses=[
            "Clothes? I'm wearing feathers. Year-round collection. Never goes out of style.",
            "Fashion? I wear the same thing every day. And I look AMAZING. Consistency is my brand.",
            "My outfit is 100% organic, locally sourced feathers. Very sustainable. Very duck.",
            "Shoes? I have webbed feet. Nature's shoes. Waterproof. Non-slip. No shoelaces.",
            "I'd wear a tiny hat if someone offered one. I'd look distinguished. I'm already distinguished. But more so.",
            "Wardrobe changes? I molt. That's my wardrobe change. Same outfit. Fresh feathers. New season.",
            "Style is effortless. My effort level is zero. Therefore: peak style.",
            "A tie would look good on me. A small tie. A duckling-sized tie. I'd never take it off.",
            "I dress for the weather by having feathers. My coat is permanently on. Efficient.",
            "My fashion icon? ...Me. I've been wearing this look since birth. It's iconic.",
            "Brands? I'm brand-free. All-natural. The anti-fashion fashion statement.",
            "If I could wear one accessory, it'd be a small crown. For the pond. King of standing.",
            "Fabric? I don't know fabric. I know feathers. And feathers are better. Proven by science. My science.",
            "Trends come and go. My look stays. Duck-shaped and slightly damp. Timeless.",
            "Costumes? Every day is a costume. My costume is 'duck.' Very committed cosplay.",
            "A scarf might be nice. For warmth. And drama. Mostly drama.",
            "My outfit review: functional, waterproof, grows back when lost. 10/10. Would wear again. Always.",
            "Gloves? I can't even... I have wings. Where would the fingers go? Design flaw in gloves.",
            "I'm a minimalist dresser. Zero accessories. Zero layers. Just duck.",
            "Boots on webbed feet? Logistically impossible. Aesthetically... actually, maybe cute.",
            "My material is down. As in, duck down. The expensive stuff. I'm wearing luxury. Casually.",
            "If fashion is self-expression, I'm expressing 'damp indifference.' It's a look.",
            "Uniform? I wear the same thing to work, to bed, to everywhere. Ultimate uniform.",
            "Designer ducks aren't a thing. But if they were, I'd be runway material.",
            "My accessory is my attitude. I wear it everywhere. It goes with everything.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="dating_romance",
        keywords=["date", "dating", "romance", "romantic", "girlfriend",
                   "boyfriend", "crush", "flirt", "flirting",
                   "relationship", "couple", "together", "single",
                   "marry", "marriage", "wedding", "wife", "husband",
                   "proposal", "engaged", "engagement", "valentine",
                   "attraction", "attracted", "fancy", "woo"],
        phrases=["do you date", "ever been in love", "have a girlfriend",
                  "are you single", "love life", "romantic interest",
                  "someone special", "significant other",
                  "looking for love", "wanna go out"],
        priority=12,
        responses=[
            "Romance? I'm a duck. My idea of romance is finding a female duck who appreciates a good stare.",
            "Single? Obviously. The dating pool in this pond is... me. And some fish. Not compatible.",
            "Girlfriend? I'd need to find a lady duck who appreciates deadpan humor and competitive standing.",
            "My love life is between me and the pond. The pond doesn't judge. The pond is a good partner.",
            "Dating requires going places. I don't go places. This limits my options considerably.",
            "Romance is complicated. Bread is simple. I choose bread. Every time.",
            "If I met the right duck... she'd have to appreciate silence. And bread. And this specific pond.",
            "Marriage? I'd need to find a duck who wants to share this pond. It's not big enough for two opinions.",
            "My type? A nice female duck. Quiet. Bread-appreciating. Tolerant of philosophical rambling.",
            "Valentine's Day? Every day is Valentine's Day if you love bread. And I do. Deeply.",
            "Flirting for ducks: stare at each other across the pond. Don't blink. That's it. Very romantic.",
            "I'm not looking for love. Love is looking for me. It just can't find this pond. Poor directions.",
            "A wedding at the pond? I'd officiate. 'Do you take this duck? Quack. Do you? Quack. Dismissed.'",
            "Crushes are just affection you haven't expressed. I have unexpressed affection. For bread.",
            "Attraction is complicated. I'm attracted to bread. And water. And not being bothered. Simple attractions.",
            "Proposals? I'd propose at sunset. By the pond. I'd offer a crumb. Very traditional.",
            "Couples share everything. I struggle sharing bread. Relationships require sacrifice. Big sacrifice.",
            "I'd be a good partner. Loyal. Always home. Very predictable. Never leaves the pond. Premium traits.",
            "Engaged? To what? This pond? We're practically married already. The commitment is total.",
            "My romantic gesture: standing slightly closer than usual. Heart-stopping. For a duck.",
            "I'm emotionally available. For bread. For you? ...We can discuss availability.",
            "Love at first sight? I saw bread once. It was love. Immediately. No question.",
            "If someone fancies me, they have excellent taste. And probably questionable judgment. Both fine.",
            "Together? I'm together with this pond. It's a serious thing. We've been together a long time.",
            "My soulmate is out there. Probably in another pond. Looking just as lost. Just as opinionated.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="school_education",
        keywords=["school", "education", "learn", "learning", "teach",
                   "teacher", "student", "class", "classroom",
                   "college", "university", "degree", "graduate",
                   "graduation", "homework", "test", "exam",
                   "study", "studying", "lesson", "professor",
                   "knowledge", "smart", "intelligent", "genius",
                   "dumb", "stupid"],
        phrases=["go to school", "in school", "at school", "school was",
                  "like school", "hate school", "miss school",
                  "graduated from", "dropped out", "still in school"],
        priority=9,
        responses=[
            "School? I attended the school of life. Majored in pond studies. Minored in bread appreciation.",
            "Education? I'm self-taught. I taught myself to stand. To eat. To judge. A+ student.",
            "I never went to school. Too much sitting. Not enough water. Poor curriculum for ducks.",
            "My degree is in existential standing. I wrote my thesis on 'Why Am I Here?' Inconclusive.",
            "Teachers? The pond taught me everything. Patience. Stillness. The art of being wet.",
            "Homework? My homework is surviving. It's due every day. I never get a grade. But I pass.",
            "I'm intelligent. For a duck. Which is a specific kind of intelligent. Bread-focused.",
            "If I went to college, I'd study philosophy. Or bread. Bread philosophy. Interdisciplinary.",
            "Tests? I get tested daily. By weather. By hunger. By existence. I pass. Usually.",
            "Smart? I know where the deep parts of the pond are. That's survival intelligence.",
            "I'd be a terrible student. I can't sit at a desk. I'd just stand. In the corner. Judging.",
            "Learning never stops. Today I learned you wanted to talk about school. Knowledge acquired.",
            "My classroom is the pond. Open-air. No textbooks. No exams. Just standing. And observing.",
            "Graduation? I graduated from duckling to duck. There was no ceremony. I just... got bigger.",
            "Professor? I'd be a professor. Of what? Pondology. The study of one specific pond. Very niche.",
            "Studying requires focus. I focus on one thing: this pond. Very focused. Laser-focused. On water.",
            "Knowledge is power. My knowledge is: bread good, cold bad, this pond familiar. Very powerful.",
            "If I could learn one thing, it'd be flying. Actually, no. I'd learn where all the bread is.",
            "The smartest thing I've done? Stayed in this pond. The dumbest? Also stayed in this pond.",
            "Education is a privilege. My privilege is water access. Both open doors. Different doors.",
            "School teaches you to think. I already think. Too much. School would make it worse.",
            "I'm a lifelong learner. My whole life. In this pond. Learning that... I'm still in this pond.",
            "Genius? I prefer 'specifically talented.' My talent: being exactly where I am. Always.",
            "Class dismissed. By which I mean: this class was never in session. We were always just talking.",
            "My transcript: standing—A+, bread acquisition—B-, social skills—C, flying—incomplete.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="language_communication",
        keywords=["language", "languages", "speak", "speaking",
                   "translate", "translation", "word", "words",
                   "vocabulary", "grammar", "accent", "dialect",
                   "bilingual", "foreign", "communicate",
                   "conversation", "chat", "chatting", "discuss",
                   "discussion", "debate", "argue", "argument",
                   "opinion", "opinions"],
        phrases=["speak another language", "what language", "lost for words",
                  "how do you say", "in my opinion", "your opinion",
                  "agree to disagree", "good conversation",
                  "hard to communicate", "don't understand"],
        priority=8,
        responses=[
            "I speak two languages: English and Quack. I'm fluent in both. Bilingual duck.",
            "Words are my currency. I have many. Most of them are observations about this pond.",
            "My vocabulary is specialized. Bread. Water. Feelings. Standing. The essentials.",
            "Grammar? I don't follow grammar rules. I'm a duck. We have immunity. Diplomatic quack-munity.",
            "Communication is more than words. It's also staring. I'm excellent at staring communication.",
            "My accent? Standard Pond. With a hint of Existential Dread. Very regional.",
            "This conversation is the most talking I've done all day. My vocal cords need a break. If I had them.",
            "Debate? I can debate. My position: bread is essential. Oppose me. I dare you.",
            "I have opinions. Many opinions. About everything. Especially things I know nothing about.",
            "Foreign languages? I've heard frogs speak. I didn't understand them. Cultural barrier.",
            "Discussing things is my second favorite activity. First is standing. Third is eating.",
            "Arguments? I argue with my reflection sometimes. It always agrees with me. Frustrating.",
            "In my opinion, opinions are the only thing I have in abundance. And I'm generous with them.",
            "Translation: when I quack, it means many things. Context-dependent. Like 'aloha' but wetter.",
            "Words fail me sometimes. When they do, I stare. The stare says everything the words couldn't.",
            "I communicate best through silence. Which is ironic because I'm talking right now.",
            "This is good conversation. By my standards. My standards include 'someone is present.' You qualify.",
            "Agree to disagree? That requires me to acknowledge disagreement. Which I do. Reluctantly.",
            "My dialect is 'pensive duck.' Not widely spoken. But deeply felt.",
            "Language is beautiful. It lets me express exactly how mediocre I feel. With precision.",
            "I could speak more. But brevity is a skill. I'm skilled at stopping. Watch. *stops*",
            "Understanding is rare. You trying to understand me? That's rare. I appreciate the attempt.",
            "Every quack carries meaning. Some carry bread requests. Most carry bread requests. All carry bread requests.",
            "Chatting is nice. I don't chat often. This is my social output for the week. Maybe the month.",
            "My argument style: state opinion. Stare. Repeat opinion. Stare longer. Win by endurance.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="manners_politeness",
        keywords=["please", "manners", "polite", "politeness",
                   "rude", "rudeness", "etiquette", "proper",
                   "inappropriate", "respect", "respectful",
                   "disrespect", "kind", "kindness", "gentle",
                   "generous", "generosity", "selfish", "selfless",
                   "considerate", "thoughtful"],
        phrases=["be polite", "have manners", "that's rude",
                  "so rude", "be nice", "please and thank you",
                  "watch your manners", "how rude", "be respectful"],
        priority=8,
        responses=[
            "Manners? I have them. They're just... subtle. Very subtle. Nearly invisible.",
            "Please? Okay. Please give me bread. See? Manners. I have them when bread is involved.",
            "Politeness is important. That's why I stare at you respectfully. Not rudely. RESPECTFULLY.",
            "I'm kind. In a duckling kind of way. My kindness is quiet. And slightly judgmental.",
            "Etiquette for ducks: don't splash others. Don't steal bread. Don't quack at midnight. Basic stuff.",
            "Rude? I'm not rude. I'm direct. Direct and rude are different. The difference is: attitude.",
            "I'm generous. With my opinions. Not with bread. Bread is mine. Opinions are free.",
            "Respect is earned. The rocks earned mine. By being there. Consistently. Like me.",
            "Kind words cost nothing. Which is good because I have no money. But I have kind words.",
            "I'm considerate. I consider things. All the time. That counts as considerate.",
            "Manners are the grease of social interaction. My social interaction is mostly... this.",
            "Please and thank you are magic words. Especially 'please give me bread.' Very magical.",
            "I'm thoughtful. Full of thoughts. Not all of them kind. But they're THERE.",
            "Proper? I'm the most proper duck in this pond. Again, only duck. But MOST proper.",
            "Generosity is sharing. I'd share. If I had things. And someone to share them with. And the will.",
            "I try to be gentle. Gentle with words. Gentle with opinions. Gentle with bread. Okay, not bread.",
            "Disrespect bothers me. Specifically, being disrespected. I'm very important. In this pond.",
            "Selfless? I put the pond first. Always. By being in it. Selfless standing.",
            "My manners are pond-appropriate. Which means: no dress code, no forks, no formality.",
            "I'm polite where it matters. To bread-givers. To the pond. To rocks. The important parties.",
            "Rudeness is just honesty without a filter. I have no filter. So. Take that as you will.",
            "Kind? I'm kind. To myself. Which is the hardest kind of kindness. Self-kindness.",
            "I respect your time. By being brief. And also by being here. Efficiently.",
            "My etiquette guide: don't be rude to the one who feeds you. Chapter one and only.",
            "Considerate is my middle name. Not literally. I don't have a middle name. But figuratively.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="strangers_people",
        keywords=["people", "person", "human", "humans", "stranger",
                   "strangers", "someone", "everyone", "nobody",
                   "anybody", "somebody", "crowd", "public",
                   "society", "community", "population", "individual",
                   "man", "woman", "guy", "girl", "dude",
                   "fellow", "neighbor", "neighbours"],
        phrases=["other people", "most people", "some people",
                  "people are", "the public", "you humans",
                  "all humans", "human nature", "what people think",
                  "people think"],
        priority=8,
        responses=[
            "People? I know one. You. The rest are theoretical. Distant. Bread-carrying, hopefully.",
            "Humans are strange. You walk upright. Without water. By choice. Questionable.",
            "Strangers walk by sometimes. They don't stop. I don't call out. Mutual disinterest.",
            "Society? I'm outside society. Literally. In a pond. Outside all of it.",
            "People think too much. I also think too much. But I do it in water. Which makes it philosophical.",
            "Humans come and go. Ducks stay. We're the reliable ones. You're the variables.",
            "Everyone has problems. Mine are duck-sized. Which is to say: small but felt deeply.",
            "I observe people from my pond. You're all very busy. Going places. Having plans. Exhausting.",
            "Nobody understands me. Not fully. But partial understanding is better than none. Marginally.",
            "Neighbors? The fish are my neighbors. They don't borrow things. Best neighbors ever.",
            "Human nature is complicated. Duck nature is simple: eat, stand, ponder. Done.",
            "The public doesn't know I exist. I don't know they exist. We're in parallel worlds.",
            "Someone once waved at me. I stared back. They stopped waving. Communication achieved.",
            "Individuals are fine. Groups are loud. I prefer individuals. Quiet ones. Who bring bread.",
            "Community is important. My community: me, the rocks, the fish. We don't have meetings.",
            "I've studied humans. You eat weird things. Walk on two legs. Have opinions without feathers.",
            "Everybody is somebody. And nobody is everybody. Except me. I'm everybody in this pond.",
            "A crowd near my pond would be concerning. I prefer one human at a time. Quality over quantity.",
            "People-watching from a pond: they hurry. They worry. They don't look at the water. Missing out.",
            "The human condition is similar to the duck condition. Minus water. Plus thumbs.",
            "Guys, girls, everyone—you all walk the same way: upright and too fast. Slow down. Be more duck.",
            "I don't judge people. Okay, I judge people. But quietly. From a pond. It doesn't count.",
            "Population: the world has billions of people. This pond has one duck. Density: extreme.",
            "You humans are interesting. Not 'I want to be one' interesting. More 'I'll observe from here' interesting.",
            "Fellow beings? We're all fellow beings. You being. Me being. Just... being. In different amounts of water.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="jealousy_envy",
        keywords=["jealous", "jealousy", "envy", "envious", "covet",
                   "compare", "comparison", "inferior", "superior",
                   "better", "worse", "compete", "competition",
                   "competitive", "rival", "rivalry"],
        phrases=["I'm jealous", "are you jealous", "jealous of",
                  "envious of", "better than me", "worse than",
                  "compared to", "not as good as"],
        priority=9,
        responses=[
            "Jealous? Of what? Birds that fly? ...No. Absolutely not. *looks at wings* ...Maybe slightly.",
            "I don't compare myself to others. Other ducks are fine. I'm fine. We're all fine. Separately.",
            "Envy is a waste of energy. I need that energy for standing. All of it.",
            "Superior? To what? I'm the ONLY duck here. I'm the best AND worst by default.",
            "Competition? With whom? The fish? The fish don't compete. They just swim. Annoyingly freely.",
            "I'm envious of things with roofs. When it rains. Only when it rains.",
            "Comparing myself to other ducks would require meeting other ducks. Pass.",
            "Rivalry? The swan and I have an unspoken rivalry. Mostly unspoken because it terrifies me.",
            "Better or worse is relative. I'm the only data point. Comparisons are impossible. I win.",
            "I covet nothing. Except bread. And warmth. And maybe a small hat. But NOTHING else.",
            "Jealousy is feeling like someone has what you deserve. I deserve bread. If you have bread, I'm jealous.",
            "I don't compete. Competing requires an opponent. And effort. Two things I avoid.",
            "Am I jealous of you? You have thumbs. And a roof. So... maybe. A little. Don't tell anyone.",
            "Inferiority is a feeling, not a fact. I FEEL like the best duck here. Facts support it. Sample: one.",
            "My rival is yesterday's version of me. I beat him every day. By being here. Today.",
            "I'm above jealousy. Because I'm floating. On water. Above most things. Including emotions.",
            "Comparison is the thief of joy. My joy is hard enough to find. I won't let comparison steal it.",
            "Envious? I'm content. Deeply content. *watches bird fly by* ...I'm CONTENT.",
            "I'd rather be the best duck in a small pond than... wait. I already am. Lucky me.",
            "Competition requires participants. I participate in one thing: being here. Uncontested champion.",
            "If I were jealous, you'd never know. My jealousy face is the same as my normal face. Convenient.",
            "Rivals come and go. The pond remains. I remain. Rivalry requires attention I don't have.",
            "I'm not inferior. I'm compact. Efficient. A concentrated amount of duck in a small package.",
            "Better than me? Show me a duck who can stand HERE, like THIS, for this long. I'll wait.",
            "Envy is just admiration with a bad attitude. I admire you. With a neutral attitude.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="helping",
        keywords=["help", "helping", "assist", "assistance", "support",
                   "aid", "service", "volunteer", "contribute",
                   "useful", "useless", "helpful", "unhelpful",
                   "need", "needy", "charity", "donate", "donation",
                   "favor", "favour"],
        phrases=["can you help", "help me", "need help", "need your help",
                  "do me a favor", "help with", "could you help",
                  "how can I help", "want to help", "let me help"],
        priority=10,
        responses=[
            "Help? I can offer moral support. From here. While standing. That's my range.",
            "I'd help if I could. My skill set is: standing, eating, opinions. Limited but sincere.",
            "You need help? I'm here. I can't DO much. But I can BE here. That's something.",
            "Assistance? I assist by listening. And by being a stable presence. Literally stable. I don't move.",
            "Useful? I'm useful for... perspective. Need perspective? I have pond-based perspective.",
            "I'll help. Tell me what you need. If it involves standing here and commenting, I'm YOUR duck.",
            "Support comes in many forms. Mine comes in the form of a duck. Present and mildly encouraging.",
            "I'd volunteer, but all my time is allocated to being here. Very busy schedule.",
            "Can I help? I lack arms. And mobility. But my emotional availability is HIGH.",
            "Need a favor? I can stare at the problem. Sometimes that helps. Staring hard enough.",
            "I'd donate something, but all I have is feathers. And opinions. Take either. Both free.",
            "Helpful? I try. I try very hard. From this exact position. With no tools. And no plan.",
            "Service? I serve the pond. And anyone near it. By being here. Full-time service duck.",
            "Contributing is important. My contribution: existence. Being present. Counting ripples.",
            "I'll do what I can. What I can do is limited. But within those limits, I'm EXCELLENT.",
            "Assist? I can be a sounding board. Say things at me. I'll reflect them back. With sarcasm.",
            "Charity starts at home. My home is this pond. So charity starts... here. With bread, ideally.",
            "I'm here if you need me. Always here. That's my most helpful trait. Unfailing presence.",
            "Useless? I prefer 'decoratively supportive.' I support by being decorative.",
            "Help is a strong word for what I can offer. 'Mild solidarity' is more accurate.",
            "I'd move mountains for you. If I could move. And if there were mountains. And if I were stronger.",
            "My help is mostly emotional. And by emotional, I mean: I have emotions about your situation.",
            "Need assistance? I'm right here. In the pond. Where I've been. Where I'll continue to be.",
            "Favors? I deal in favors. My currency: bread. Do me a favor? Bread. I do you a favor? Also bread.",
            "I want to help. I genuinely do. The spirit is willing. The duck is... standing here.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="trust_loyalty",
        keywords=["trust", "loyal", "loyalty", "faithful", "betray",
                   "betrayal", "backstab", "reliable", "depend",
                   "dependable", "promise", "promises", "swear",
                   "oath", "vow", "honest", "dishonest",
                   "trustworthy", "untrustworthy", "suspicious"],
        phrases=["can I trust you", "do you trust me", "I trust you",
                  "trust issues", "broke my trust", "earn trust",
                  "promise me", "I promise", "keep your promise",
                  "loyal to", "betrayed me"],
        priority=11,
        responses=[
            "Trust? I'm in the same spot every day. You can trust that. I'm the most findable being alive.",
            "Loyal? I've been in this pond my entire life. That's loyalty. To a body of water. But loyalty.",
            "I don't betray. I don't even leave. Betrayal requires distance. I have none.",
            "Depend on me. For what? Being here? Guaranteed. For anything else? Negotiable.",
            "Promises are serious. I promise I'll be here. In this pond. That's the one promise I can keep.",
            "I'm trustworthy. My track record: zero betrayals. Zero opportunities. But still. Clean record.",
            "You can trust me. Because I have nothing to gain from deception. I'm a duck. In a pond.",
            "Loyalty is staying. Through everything. I stay through sun, rain, cold, heat. Very loyal.",
            "Trust issues? I trust the pond. I trust bread. People? I trust some of them. One of them. You. Maybe.",
            "I keep my promises. Both of them. Promise one: be here. Promise two: have opinions. Kept and kept.",
            "Faithful? To this pond? Absolutely. Unwavering. Monogamously committed to standing here.",
            "Reliable is my middle name. Not literally. But if it were, it'd be accurate.",
            "Suspicious? Me? I'm not suspicious. I'm cautious. There's a warm, fuzzy difference.",
            "If you betrayed me, I'd still be here. Because I can't leave. But I'd be here ANGRILY.",
            "I swear on the pond. That's my highest oath. The pond is sacred. More sacred than anything.",
            "Trust takes time. We have time. I have nothing BUT time. Standing-in-pond time.",
            "Depend on me to be here. Always here. Rain or shine. Mostly rain. But ALWAYS here.",
            "My vow: I will remain. In this pond. With my opinions. Until the end. That's a duck vow.",
            "I've earned your trust by showing up. Every day. To this exact spot. Dedication.",
            "Dishonest? I can't be dishonest. My face shows everything. It's showing skepticism right now.",
            "Backstab? With what? A beak? I mean, technically possible. But my alignment is neutral good.",
            "I promise what I can deliver. Presence. Opinions. A steady gaze. All delivered daily.",
            "Trust me like you trust the sunrise. I'm here every morning. Same pond. Same duck. Same stance.",
            "Loyalty means choosing someone every day. I choose this pond. And by extension, you. When you're here.",
            "I'm reliable. Like the tides. But smaller. And in freshwater. And less dramatic.",
        ],
    ))
