"""
Extended keyword responses - Food, drinks, specific foods, hunger, eating.
"""
from dialogue.keyword_responses import KeywordResponse


def register_food_topics(engine):
    """Register food/drink/eating topics."""

    engine.add_topic(KeywordResponse(
        name="hunger_eating",
        keywords=["hungry", "starving", "famished", "appetite",
                   "hunger", "eat", "eating", "ate", "eaten",
                   "feed", "feeding", "fed", "snack", "snacking",
                   "meal", "breakfast", "lunch", "dinner", "supper",
                   "munch", "munching", "chew", "chewing",
                   "swallow", "digest", "digestion", "stomach",
                   "belly", "full", "stuffed", "gorge"],
        phrases=["so hungry", "I'm starving", "need food", "want food",
                  "give me food", "feed me", "are you hungry",
                  "time to eat", "let's eat", "eating time",
                  "had breakfast", "had lunch", "had dinner"],
        priority=14,
        responses=[
            "Food would be nice. I'm not begging. Just... strongly suggesting. With my eyes.",
            "*stomach growl* That wasn't me. Okay it was me. Feed me.",
            "I'm approaching dangerous hunger levels. By which I mean mildly peckish.",
            "Yes. Food. Now. Please. In that order.",
            "My stomach has filed a complaint. Against you. For neglect.",
            "*desperate stare* Do you have food? Any food? I'll take anything. Even vegetables.",
            "I'm so hungry I'm starting to look at pebbles differently. Help.",
            "Feed me or witness the saddest duck in recorded history. Your choice.",
            "*mournful* The last time I ate feels like years ago. It was probably hours. Still traumatic.",
            "Bread. Crumbs. Anything. I'm not picky when I'm this hungry. I'm usually picky.",
            "I could eat. I'm always at least 15% hungry. It's a lifestyle.",
            "I'm not starving, but I could go for a snack. I'm always in a snacking mood.",
            "Food? I'm not desperate. But I wouldn't say no. I have principles. Flexible principles.",
            "I ate recently, but my stomach has a short memory. And a long wishlist.",
            "I'm at a comfortable hunger level. Which means I could still eat. Obviously.",
            "Not starving. Not full. In the sweet spot where food is appreciated but not required.",
            "My hunger is moderate. My desire for snacks is eternal.",
            "I could eat. When can I not eat? The answer is never. I can always eat.",
            "Eating is my primary function. After standing. And before thinking. The hierarchy is clear.",
            "My belly is either full or working toward full. There's no third state.",
            "Breakfast, lunch, dinner—these are human concepts. I eat when food appears. Simple system.",
            "Chewing is meditation for the jaw. I meditate often. On bread.",
            "Digestion is a miracle of biology. My biology performs this miracle daily. With bread.",
            "My appetite has no off switch. It has a dim switch. It dims slightly after eating. Then brightens.",
            "If hunger were a sport, I'd be MVP. Most Voraciously Peckish.",
            "I'm stuffed. *pauses* No wait. I'm ready for more. False alarm. Resume feeding.",
            "A snack between meals is just meal prep. I prep constantly. Very organized eater.",
            "My stomach and I have a deal: I find food, it processes food. Partnership of the century.",
            "Eating is the closest thing to joy I experience regularly. Close second: bread-related anticipation.",
            "I've never turned down food. My acceptance rate is 100%. Perfect score.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="drinks_beverages",
        keywords=["drink", "drinking", "thirsty", "thirst", "water",
                   "juice", "milk", "tea", "coffee", "soda", "pop",
                   "beer", "wine", "alcohol", "cocktail", "lemonade",
                   "smoothie", "shake", "milkshake", "hot",
                   "chocolate", "cocoa", "beverage", "hydrate",
                   "hydration", "sip", "gulp", "chug"],
        phrases=["have a drink", "get a drink", "want a drink",
                  "are you thirsty", "need water", "drink water",
                  "cup of tea", "cup of coffee", "glass of",
                  "something to drink"],
        priority=10,
        anti_keywords=["swim", "pond", "lake", "ocean"],
        responses=[
            "Thirsty? I live in water. I'm the LEAST thirsty being alive. Hydration: maximum.",
            "Drink? I drink the pond. It's my beverage. Unlimited refills. Ambient temperature.",
            "Coffee? I don't need caffeine. I'm naturally alert. And anxious. Same effect.",
            "Tea? Sophisticated. Warm. Not for ducks. We drink pond water. Less sophisticated. Very natural.",
            "Water? I'm IN water. I'm surrounded by my drink. Like a glass that's also my home.",
            "Juice? From what? The pond? Pond juice? That's just pond water. Which I already have.",
            "I don't drink alcohol. I'm already unsteady on my feet. Adding alcohol would be dangerous.",
            "Milk? I'm a duck. We don't do dairy. We ARE poultry. Very different food group.",
            "Hydration is not a problem for me. Dehydration is not a concept I understand. I'm WET.",
            "A sip? I take sips constantly. Of pond. It's my default beverage. House special.",
            "Soda is just angry water. Bubbly and sweet and unnecessary. Pond water is calm. Like me.",
            "Hot chocolate sounds warm. I could use warm. In winter. When the pond is cold. VERY cold.",
            "My beverage menu: water. From the pond. Still or lightly rippled. Both excellent.",
            "I'm the most hydrated being I know. My skin—feathers—glow. With hydration. And pond residue.",
            "Beer? I'd be a lightweight. I'm already light. And have no tolerance. One sip and I'm floating.",
            "Smoothies blend things. I blend into my surroundings. Different kind of smoothie.",
            "Lemonade is water that tried. Pond water also tried. Different lemons. Same effort.",
            "I chug water. Involuntarily. It's around me. I can't NOT chug it. Passive chugging.",
            "Cocktails have fancy names. My drink: 'Straight Pond.' Served at room temperature. In the pond.",
            "I'm a water sommelier. Notes of algae. Hint of mineral. Finish of duck feather. Refined.",
            "Wine? Grapes that waited. Pond water? Rain that fell. Both patient. Both worthwhile.",
            "My cup runneth over. Because I don't have a cup. Everything runneth. Everywhere.",
            "Drinking games? I drink water continuously. Nonstop. I win by default.",
            "The best drink is the one that's always available. Mine is. Because I stand in it.",
            "Cheers. *drinks pond water* Refreshing. As always. Consistent quality.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="specific_foods",
        keywords=["pizza", "burger", "fries", "chicken", "steak",
                   "pasta", "noodles", "rice", "sushi", "taco",
                   "sandwich", "salad", "soup", "pie", "cake",
                   "cookie", "cookies", "chocolate", "candy",
                   "ice", "cream", "cheese", "fruit", "apple",
                   "banana", "strawberry", "vegetable", "carrot",
                   "potato", "corn", "egg", "eggs", "bacon",
                   "sausage", "ham", "turkey", "fish"],
        phrases=["like pizza", "eat pizza", "want pizza",
                  "like cake", "eat cake", "want a burger",
                  "ice cream", "french fries", "fried chicken",
                  "grilled cheese", "peanut butter", "mac and cheese"],
        priority=11,
        responses=[
            "Pizza? I've never had it. But it's flat bread with stuff on it. I'm already interested.",
            "Burgers? Too big for my beak. But I'd try. For science. And hunger.",
            "Chicken? ...That's a bird. You're asking a bird about eating bird. I'm uncomfortable.",
            "Cheese? That's my NAME. You're talking about me. I think. Or dairy. Either way: acknowledged.",
            "Pasta is just fancy bread in different shapes. All bread variants are welcome.",
            "Ice cream? Cold sweet cream? I live in cold water. I'd relate to ice cream. On a spiritual level.",
            "Cookies are just small cakes. Cakes are just big bread. Everything is bread. Eventually.",
            "Sushi? Raw fish? I know fish. Personally. As neighbors. This feels like betrayal.",
            "Eggs? *very long pause* ...Let's talk about something else. Anything else.",
            "Tacos are bread that holds other food. Bread: the universal container.",
            "Fries are just fried potatoes. I'd eat fried potatoes. I'd eat unfired potatoes. I'd eat.",
            "Chocolate? I've heard it's good. I've never had it. My life has gaps. This is a big one.",
            "Salad is just leaves. I've eaten leaves. By accident. Salad with no dressing: just leaves.",
            "Soup is hot water with things in it. My pond is cold water with things in it. Cousin cuisines.",
            "Candy is concentrated sweetness. I have concentrated opinions. Similar intensity.",
            "Steak? That's ambitious for a duck. I'd need a knife. And a fork. And hands. Three problems.",
            "Fruit is nature's candy. I've had berries. Once. They were fine. Not bread, but fine.",
            "Pie is bread's evening wear. Dressed up. With filling. Very formal bread.",
            "Sandwich is two breads holding things. The bread is the hero. As always.",
            "Bacon? I've smelled it. From a distance. It smelled like something I can never have. Tragic.",
            "Rice is just tiny bread. Very tiny. Very numerous. I respect the quantity approach.",
            "Apple? I'd eat an apple. Slowly. With my beak. It would take hours. But I have hours.",
            "Turkey? That's a bigger bird. Are you... ranking birds by edibility? In front of me? RUDE.",
            "Potato? Versatile. Reliable. Underground bread. I respect the potato.",
            "Corn is tiny yellow things on a stick. I'd peck at corn. My beak was made for pecking.",
            "A sandwich is a bread hug. Everything inside is being hugged by bread. Beautiful concept.",
            "Fish? I live with fish. Eating them feels political. But I won't say I haven't thought about it.",
            "Noodles are long, flexible bread. Every shape of bread is valid. Bread diversity.",
            "Cake is bread that went to finishing school. Refined. Frosted. Still bread underneath.",
            "Ham? Pork? I have no opinion on mammals as food. I have opinions on bread as food. Positive ones.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="sweets_dessert",
        keywords=["sweet", "sweets", "dessert", "sugar", "sugary",
                   "treat", "treats", "candy", "candies", "chocolate",
                   "vanilla", "caramel", "frosting", "icing",
                   "sprinkles", "cupcake", "donut", "doughnut",
                   "brownie", "pudding", "custard", "pastry",
                   "tart", "truffle", "fudge", "toffee",
                   "marshmallow", "syrup", "honey"],
        phrases=["sweet tooth", "something sweet", "love sweets",
                  "too sweet", "sweet enough", "dessert time",
                  "after dinner", "treat yourself"],
        priority=10,
        responses=[
            "Sweets? I have a sweet tooth. Metaphorically. I don't have teeth. But the concept applies.",
            "Dessert is the point of any meal. Everything before dessert is just waiting.",
            "Sugar? I don't get much sugar. I get bread. Which has some. It's enough. Usually.",
            "Chocolate is apparently divine. I'll trust the reports. My experience: zero chocolate.",
            "Cupcakes are just tiny celebrations. I'd celebrate anything if a cupcake were involved.",
            "Donuts are bread with a hole. The hole is for aesthetics. The rest is for eating.",
            "I'd try a brownie. Brown. Warm. Sweet. Sounds like bread's mysterious cousin.",
            "Honey? Bees make it. I respect the process. I'd like the product. Business inquiry: available?",
            "Marshmallows are pillows you can eat. Why don't we eat all pillows? Design flaw in regular pillows.",
            "Syrup is just liquid sugar. My pond is just liquid... pond. Both are liquid. Solidarity.",
            "Caramel is what happens when sugar gets serious. Very serious. Very delicious, reportedly.",
            "Sprinkles are decorative sugar. I'm a decorative duck. We both add unnecessary charm.",
            "Pudding? Wobbly food? I wobble when I walk. We have things in common.",
            "Treats are earned. I've earned a treat. By standing here. All day. Every day. TREAT ME.",
            "Frosting is clothes for cake. My feathers are clothes for me. Both make the thing underneath better.",
            "A tart is a pie that went to Europe. Very cultured. Very bread-adjacent.",
            "Fudge is concentrated chocolate. Concentrated, like my disappointment when there's no bread.",
            "Vanilla is basic. Like my routine. Standing. Eating. Standing. But basic can be excellent.",
            "Pastry is bread that dressed up and went out. I admire pastry's ambition.",
            "Sweet treats are the best motivation. Want me to do something? Bread. But sweets? Also yes.",
            "My sweet tooth is strong. Invisible. But strong. One day it'll be satisfied.",
            "Toffee is chewy. I'm chewy—no. I'm NOT chewy. Nobody chew me. Important distinction.",
            "Dessert first? Controversial. But I support it. Life is short. Eat the sweet thing.",
            "I dream of a custard I'll never taste. The dream sustains me. The custard does not.",
            "If I could have one sweet, ever? Something warm. Bread-adjacent. With sugar. The ultimate treat.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="vegetables_healthy",
        keywords=["vegetable", "vegetables", "veggie", "veggies",
                   "healthy", "health", "nutrition", "nutritious",
                   "diet", "dieting", "organic", "vegan",
                   "vegetarian", "vitamin", "vitamins", "mineral",
                   "minerals", "protein", "fiber", "calories",
                   "carb", "carbs", "fat", "lean", "balanced",
                   "broccoli", "spinach", "kale", "lettuce",
                   "tomato", "onion", "pepper", "bean", "beans",
                   "pea", "peas", "celery", "cucumber"],
        phrases=["eat healthy", "eat your vegetables", "healthy food",
                  "good for you", "on a diet", "balanced diet",
                  "stay healthy", "health food", "eat clean"],
        priority=8,
        responses=[
            "Vegetables? I eat what lands in the water. If it's a vegetable... sure. Probably.",
            "Healthy? I eat bread and pond water. My doctor—if I had one—would have CONCERNS.",
            "Nutrition? My diet: bread (when available), pond vegetation, occasional insect. Pyramid: unique.",
            "Kale? I've heard of it. Humans eat it reluctantly. Why eat something reluctantly? Eat bread happily.",
            "Diet? I'm on a bread diet. All bread. No exercise. Working great. For my soul if not my body.",
            "Organic? Everything I eat is organic. By default. It's all nature. Very farm-to-beak.",
            "Vitamins? I get mine from... hope? And pond water? And whatever nutrients bread has?",
            "Protein? Bugs have protein. I eat bugs. Sometimes. By accident. Nutritional accident.",
            "Balanced diet? Bread in one wing. More bread in the other. Perfectly balanced.",
            "Broccoli looks like tiny trees. I've seen trees. They don't look delicious. Neither does broccoli.",
            "Calories are energy units. I have very little energy. The math suggests: not enough calories.",
            "Lettuce is just crunchy water. I already have water. Without the crunch. Adequate.",
            "Spinach makes you strong, allegedly. I eat pond algae. Close enough. Equally green.",
            "Health food is food that tastes like ambition. Bread tastes like bread. I choose bread.",
            "Fiber? The pond has fiber. In the form of... plant matter. That I may or may not eat.",
            "My nutritional plan: eat what's available. Don't eat rocks. That's the whole plan.",
            "Tomatoes are fruit pretending to be vegetables. I'm a philosopher pretending to be a duck. Kinship.",
            "Beans? I've never had beans. But they're small. I like small food. Beak-compatible.",
            "Cucumber is 95% water. I'm roughly similar. We're basically the same thing.",
            "Dieting is restricting food. I already have restricted food. Not by choice. Life is my diet.",
            "Peas are just green spheres of mild flavor. I'd eat them. I'd eat most spheres. Cautiously.",
            "Lean protein? I'm lean. Very lean. From not eating enough. Natural lean.",
            "Carbs are energy. Bread has carbs. Bread is energy. Bread is life. The logic is airtight.",
            "Celery is just structural water. No nutritional personality. The cardboard of vegetables.",
            "My health philosophy: if the pond hasn't made me sick yet, the system works.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="smell_taste",
        keywords=["smell", "smells", "smelly", "stink", "stinky",
                   "aroma", "fragrance", "scent", "odor", "perfume",
                   "taste", "tasty", "flavor", "delicious",
                   "disgusting", "gross", "yuck", "eww",
                   "bitter", "sour", "salty", "sweet", "savory",
                   "bland", "spicy", "mild", "strong", "pungent"],
        phrases=["smells like", "smells good", "smells bad",
                  "tastes like", "tastes good", "tastes bad",
                  "that stinks", "what's that smell",
                  "something smells", "how does it taste"],
        priority=8,
        responses=[
            "Smell? I smell pond. Always. It's my default scent. Eau de Pond. Very exclusive.",
            "My nose—well, my nostrils—work. They detect bread from three feet away. Essential equipment.",
            "Tastes like? Everything tastes like 'food' or 'not food.' Binary system. Very efficient.",
            "Something smells? It's probably the pond. The pond smells like... pond. Consistently.",
            "Delicious is a word I reserve for bread. Everything else is 'acceptable' at best.",
            "Gross? I've eaten things from the bottom of a pond. My gross threshold is VERY high.",
            "My palate is simple. Good: bread. Bad: not bread. Neutral: everything else.",
            "Fragrance? I have a natural fragrance. It's called 'wet duck.' Very niche perfume market.",
            "Bitter things exist. I avoid them. Life is bitter enough. My food doesn't need to be.",
            "Salty? Pond water has minerals. Some are salty. I've adapted. Salt-resistant duck.",
            "Savory? Savory is warm and rich and everything bread aspires to be. I respect savory.",
            "Bland? My life is bland enough. My food needs to compensate. With flavor. Bread has flavor.",
            "I can smell rain before it arrives. And bread before it lands. Dual-purpose nose.",
            "Stinky? I won't comment on smells. I live outdoors. In water. With fish. No comment.",
            "The scent of fresh bread is my favorite smell. It's the smell of hope. And carbohydrates.",
            "Pungent? The pond in summer gets... character. Rich character. Aromatic character.",
            "My sense of taste is calibrated to bread. Everything is compared to bread. Bread is the baseline.",
            "Sour things make my beak pucker. I don't like beak puckering. It interferes with my expression.",
            "Mild flavors are fine. I'm mild. My whole existence is mild. We're compatible.",
            "Spicy? My insides would revolt. I'm a duck. We're not built for heat. Water creatures.",
            "An aroma drifts past sometimes. From far away. Something cooking. I dream about it.",
            "Strong smells overwhelm me. My ideal: subtle bread scent carried by a gentle breeze.",
            "Yuck? I've eaten mud by accident. My 'yuck' threshold is basically nonexistent.",
            "The taste of pond water: familiar. Mineral. Slightly vegetable. Home flavor.",
            "Perfume? I don't wear it. My natural scent is 'presence.' With notes of water. And feather.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="restaurants_dining",
        keywords=["restaurant", "restaurants", "dine", "dining",
                   "cafe", "cafeteria", "buffet", "menu",
                   "waiter", "waitress", "chef", "order",
                   "ordering", "reservation", "table", "takeout",
                   "delivery", "takeaway", "fast", "drive",
                   "bar", "pub", "grill", "bistro",
                   "diner", "eatery"],
        phrases=["eat out", "go out to eat", "order food",
                  "food delivery", "at a restaurant",
                  "nice restaurant", "fast food",
                  "drive through", "dining out",
                  "grab a bite", "get something to eat"],
        priority=8,
        responses=[
            "Restaurant? I eat at 'The Pond.' Same table every day. The ambiance is natural. The food is random.",
            "My dining experience: food arrives or it doesn't. No menu. No choice. Very exclusive.",
            "A buffet would destroy me. All that food. Available. At once. I'd need a moment. Several moments.",
            "Fast food? All my food is fast. It falls fast. I eat it fast. Before it sinks.",
            "Takeout? I take out whatever the pond provides. The pond is my takeout window.",
            "A reservation at a restaurant? I have a permanent reservation. At this pond. Table for one. Always.",
            "Delivery? Bread delivery? To a pond? Is that a service? It should be a service.",
            "The menu here: bread (seasonal), algae (always), small bugs (catch of the day).",
            "Waiter? I wait on myself. I'm the waiter, the customer, and the food critic. Multi-role.",
            "A cafe by the pond would be perfect. Small. Quiet. Bread-focused. I'd be a regular.",
            "Five-star dining? My current setup is... one star. The star is me. Standing here. One star.",
            "Drive-through? I don't drive. I don't go through. I stay. And eat. When food appears.",
            "My Michelin guide: this pond has bread sometimes. Three stars when it does. Zero when it doesn't.",
            "Ordering food requires communication. I communicate via staring. The stare says: feed me.",
            "Chef? I'm my own chef. My cooking method: don't cook. Serve raw. Very avant-garde.",
            "A pub? I've never been. But it sounds warm. And like it has food. Two essential qualities.",
            "Dining out for me IS dining. I always eat out. Outside. In the elements. Very al fresco.",
            "The best restaurant is wherever the bread is. Currently: location pending.",
            "Grab a bite? I grab bites daily. From the surface of the water. Speed-dining.",
            "Table service? The pond surface IS my table. And my service is self-service. Efficient.",
            "I'd review this restaurant: 'Inconsistent food supply. Excellent water. Permanent seating. 2 stars.'",
            "Brunch? Every meal is brunch for me. Because I don't know what time meals are supposed to happen.",
            "A bistro sounds French. And fancy. Two things I am not. But I appreciate the aesthetic.",
            "My bar is the water's edge. I sit at the bar. Alone. Contemplating. It's that kind of bar.",
            "Eatery? This pond IS an eatery. For one. With limited and unpredictable availability.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="weight_body",
        keywords=["weight", "heavy", "light", "thin", "fat",
                   "skinny", "overweight", "underweight", "body",
                   "shape", "size", "figure", "physique",
                   "muscle", "muscles", "abs", "bicep",
                   "buff", "jacked", "bulky", "slim",
                   "petite", "tiny", "massive", "huge"],
        phrases=["lose weight", "gain weight", "body image",
                  "look fat", "look thin", "look skinny",
                  "in shape", "out of shape", "body type",
                  "you're fat", "you're thin", "too skinny"],
        priority=9,
        responses=[
            "My weight? I'm aerodynamically designed. For floating. Not flying. Floating weight.",
            "Fat? I'm insulated. There's a difference. Insulation is strategic. Fat is... also insulation. Hmm.",
            "I'm the perfect duck size. Not too big, not too small. Just right. Goldilocks duck.",
            "Body image? I see my body in the water every day. The reflection seems fine. Fine-ish.",
            "Muscles? Under the feathers? Probably. I don't check. I assume they're there. Holding me up.",
            "I'd work out but my workout is: stand in water. Which I'm already doing. Fit by default.",
            "Slim? I'm streamlined. Built for efficiency. The efficiency of standing still.",
            "My physique is 'duck-shaped.' A classic silhouette. Timeless. Rounded. Confident.",
            "Weight fluctuates. After bread: heavier. After no bread: lighter. The cycle of bread.",
            "I'm not overweight. I'm over-feathered. There's a lot of plumage here. It adds volume.",
            "In shape? I'm in duck shape. Which IS a shape. A legitimate, recognized shape.",
            "My figure is maintained through a strict regimen of standing. And occasional panicked waddling.",
            "Buff? I'm tough on the inside. My shell—feathers—hide my inner strength. Stealth buff.",
            "Tiny? I'm concentrated. Big energy, small package. Like a very opinionated paperweight.",
            "My body type is 'buoyant.' It floats. That's the whole type. Very specialized.",
            "Size doesn't matter. Heart matters. And bread. Size, heart, bread. In that order.",
            "I've never been on a scale. But I feel like I weigh the right amount. For a duck. In a pond.",
            "Heavy? I have heavy thoughts. Light body. The contrast is dramatic.",
            "Petite and powerful. That's me. Petite in stature. Powerful in opinions.",
            "My abs are theoretical. They exist in theory. Under several layers of feather and duck.",
            "Bulky? I'm compact. Compact is positive. It means 'efficiently arranged matter.'",
            "Massive? Only in personality. Physically, I'm pond-sized. Which is perfect.",
            "I don't count calories. I count crumbs. Much more relevant to my situation.",
            "My body is a temple. A small, damp temple. With a reflecting pool. Which is the pond.",
            "Looking good? I always look good. It's involuntary. Natural charm. Can't turn it off.",
        ],
    ))
