"""
Extended keyword responses - Hobbies, games, entertainment, sports, art.
"""
from dialogue.keyword_responses import KeywordResponse


def register_activity_topics(engine):
    """Register hobby/game/entertainment/sport/art topics."""

    engine.add_topic(KeywordResponse(
        name="video_games",
        keywords=["game", "games", "gaming", "gamer", "console",
                   "playstation", "xbox", "nintendo", "switch",
                   "controller", "joystick", "arcade", "pixel",
                   "level", "score", "highscore", "respawn",
                   "multiplayer", "singleplayer", "rpg", "fps",
                   "mmo", "sandbox", "indie", "retro", "boss",
                   "quest", "loot", "inventory"],
        phrases=["video game", "video games", "play games", "playing games",
                  "favorite game", "like games", "game over",
                  "new game", "beat the game", "in the game"],
        priority=10,
        anti_keywords=["board", "card", "outside"],
        responses=[
            "Video games? I'd play them. But no thumbs. And no TV. And no electricity. Minor setbacks.",
            "Gaming requires a screen. I have the pond. It shows my reflection. Same thing? No. But close.",
            "I'd be great at video games. I already stand in one place staring at nothing. That's most games.",
            "If I were in a video game, I'd be the NPC that says one thing. Standing by the pond. Iconic.",
            "High scores? My high score is 'consecutive hours standing.' I'm speedrunning it daily.",
            "I'd play a fishing game. From the fish's perspective. Just to understand my neighbors.",
            "Boss battles? I face a boss every day. The boss is existence. I haven't beaten it yet.",
            "My life IS a game. A very slow, ponderous game. With no save points. And questionable graphics.",
            "Multiplayer? I prefer single player. Player one. The only player. In a single-player pond.",
            "RPG? I'm role-playing as a duck. Full-time. Very committed to the character.",
            "Inventory? I have: feathers, opinions, and a vague sense of purpose. Full inventory.",
            "Respawn? If I respawned, I'd spawn right here. In this pond. Because of course I would.",
            "Side quests are just distractions from the main quest. My main quest: stand here. No distractions.",
            "Retro games are simple. Like me. Simple controls. One button: exist. Very retro.",
            "Game over? Not yet. I'm on a long playthrough. Very long. Possibly too long.",
            "If my life had a difficulty setting, it'd be 'Normal.' Not easy, not hard. Just... normal. And wet.",
            "Loot? I loot crumbs. From the ground. It's basically the same as treasure hunting.",
            "I'd play a duck simulator. Just to see what they got wrong. Probably the existential dread part.",
            "Loading screen: 'Cheese is standing in the pond...' That's my loading screen. It never ends.",
            "The final level is somewhere out there. I'm still on level one. The pond level. It's long.",
            "Achievement unlocked: 'Talk to a human.' Worth 0 points. But socially, priceless.",
            "I'm an NPC with main character energy. Stuck on the sidelines. But RADIATING importance.",
            "Sandbox game? This pond IS a sandbox. With water instead of sand. Better, honestly.",
            "My controller has one button: quack. And I press it strategically. At key moments.",
            "Easter eggs in my life: that one weird rock. The spot where bread appeared once. Secrets.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="movies_tv",
        keywords=["movie", "movies", "film", "films", "cinema",
                   "actor", "actress", "director", "scene", "plot",
                   "character", "show", "shows", "series", "episode",
                   "season", "watch", "watching", "screen", "tv",
                   "television", "netflix", "streaming", "documentary",
                   "cartoon", "animation", "anime", "drama",
                   "action", "thriller", "horror", "comedy"],
        phrases=["favorite movie", "watch a movie", "seen any movies",
                  "like movies", "good movie", "movie night",
                  "favorite show", "tv show", "watch tv",
                  "binge watch", "what do you watch"],
        priority=9,
        anti_keywords=["weather", "season"],
        responses=[
            "Movies? I've never seen one. But I've stared at water for hours. Similar experience.",
            "My life is a movie. A very slow indie film. No budget. One location. Limited cast.",
            "If there were a movie about me, it'd be called 'Cheese.' Tagline: 'He stands.'",
            "I'd watch a documentary about ponds. Just to see if they got the vibe right.",
            "Drama? My life is drama. The drama of standing. The drama of waiting for bread. Oscar-worthy.",
            "Action movies have explosions. I have ripples. Same energy. Smaller budget.",
            "My favorite character would be whatever animal sidekick just sits there judging everyone.",
            "Horror? I live horror. Every time a hawk flies over. Every time the bread doesn't come.",
            "Comedy? I AM comedy. Unintentional comedy. The best kind.",
            "I'd binge-watch anything about nature. Just to see if I'm doing this 'outside' thing right.",
            "A plot twist in my life: the bread was there the whole time. Under a leaf. Cinema.",
            "If I directed a film, every scene would be five minutes of silence. Then a quack. Artistic.",
            "Streaming? I stream pond water. Through my feathers. Different kind of streaming.",
            "The best movies have a message. My message: I'm here. In a pond. That's the whole film.",
            "Animation? My movements are pretty animated. When I'm eating. Otherwise? Still frame.",
            "I'd be the critic who rates everything. 'That sunset? Three stars. Seen better.'",
            "My screen is the water surface. It shows one channel: my face. Not great programming.",
            "Episode one of my life: hatched. Episode two through ten thousand: stood in pond. Serialized.",
            "Thriller? The most thrilling thing here is when a leaf falls into the pond. Edge of your seat.",
            "I relate to characters who are stuck somewhere. Any movie where someone just... stays.",
            "Cartoons simplify reality. My reality is already simple. I'm a living cartoon. Minus the fun colors.",
            "The director of my life needs to add more bread scenes. Too much standing. Not enough eating.",
            "A documentary about me: 'March of the Duck.' Except I don't march. I stand. 'Stand of the Duck.'",
            "Cinema is escapism. I can't escape. So cinema would be perfect for me. If I had a screen.",
            "My review of today: 'Adequate. Predictable. The bread scene was too short. 2.5 stars.'",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="sports",
        keywords=["sport", "sports", "football", "soccer", "basketball",
                   "baseball", "tennis", "golf", "hockey", "cricket",
                   "rugby", "boxing", "wrestling", "swimming",
                   "running", "marathon", "race", "racing", "gym",
                   "exercise", "workout", "fitness", "athlete",
                   "athletic", "team", "match", "tournament",
                   "championship", "olympics", "medal", "trophy",
                   "coach", "training", "practice"],
        phrases=["play sports", "like sports", "watch sports",
                  "into sports", "favorite sport", "do you exercise",
                  "work out", "go to the gym", "sports fan"],
        priority=9,
        responses=[
            "Sports? My sport is standing. Competitively. Against myself. I'm undefeated.",
            "I swim. That counts as a sport. I swim slowly. And without direction. But it counts.",
            "Exercise? I exercise my right to remain stationary. Very intense. Very committed.",
            "Football? I'd be the ball. Round. Small. Gets kicked around. Relatable.",
            "My fitness level: can float. Can stand. Can waddle short distances. Peak performance.",
            "Marathon? I'd last five feet. Then I'd sit down. In water. Like I always do.",
            "The gym? Outside IS my gym. The pond is my pool. The ground is my treadmill. Free membership.",
            "Basketball? I can't dribble. I can't shoot. I can stare at a ball though. Scout me.",
            "Training? I train every day. For what? Being here. I'm very well-trained at being here.",
            "Golf requires tiny balls and big sticks. I have neither. But I could watch. From a pond.",
            "Wrestling? I've wrestled with my thoughts. Every day. Undefeated against my own ideas.",
            "The Olympics need a standing event. I'd represent all ducks. Gold medal. Guaranteed.",
            "My workout routine: stand up. Eat. Stand more. Occasional waddle. Rest. Repeat.",
            "Coaching? I'd coach standing. 'Feet down. Eyes forward. Be still. Good. You're a natural.'",
            "I have team spirit. Team Duck. One member. Full commitment. We're going all the way.",
            "Swimming competitively? I swim casually. The casual division. Where nobody tracks time.",
            "Athletic? I'm athletic-adjacent. I'm in water. Near where athletics could happen.",
            "A trophy for standing? I'd put it here. By the pond. On Gerald. He'd hold it.",
            "Racing? I race against time. Time always wins. But I show up. Every race.",
            "Practice makes perfect. I practice existing. And I'm getting pretty perfect at it.",
            "If standing were an Olympic sport, I'd break records. World records. Universal records.",
            "Boxing? My reach is short. My beak is pointy. I'd compete in a weird weight class.",
            "The championship of this pond: me vs. me. I won. Also lost. But COMPETED.",
            "I'm a natural athlete. Natural at standing. The most athletic standing you've ever seen.",
            "Sport requires effort. I exert effort. Into being motionless. It's a niche sport.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="art_creativity",
        keywords=["art", "artist", "artistic", "paint", "painting",
                   "draw", "drawing", "sketch", "sculpture", "museum",
                   "gallery", "creative", "creativity", "create",
                   "design", "craft", "crafting", "masterpiece",
                   "canvas", "color", "portrait", "abstract",
                   "photography", "photo", "picture", "camera",
                   "beautiful", "aesthetic", "mural", "collage"],
        phrases=["work of art", "make art", "piece of art", "create something",
                  "draw me", "paint me", "take a picture",
                  "you're an artist", "that's art", "is it art"],
        priority=9,
        responses=[
            "Art? I'm a living sculpture. 'Duck in Pond.' Mixed media. Water and feathers. Ongoing exhibition.",
            "I can't paint. No thumbs. But if I could, I'd paint bread. Just... bread. Gallery-worthy.",
            "My art form is standing. Performance art. Very long performance. Very still performer.",
            "I create ripples. That's my art. Temporary. Water-based. Absolutely free to view.",
            "A portrait of me would just be a circle with a beak. And attitude. Don't forget the attitude.",
            "Photography? The pond photographs me every day. In its reflection. Without consent. Rude.",
            "My masterpiece is this moment. Right now. Me, standing here. It'll never be recreated. Limited edition.",
            "Sculpture? I'm a sculptor. I sculpt my feathers. Into this shape. Every day. Same shape. Consistent art.",
            "If I were in a museum, I'd be in the 'Standing Still' exhibit. Right next to the security guard.",
            "Abstract art makes no sense. Like me. Standing here. For no clear reason. Very abstract.",
            "Creativity is solving problems in new ways. My problem: boredom. My solution: thinking. Very creative.",
            "Drawing requires hands. I have wings. My drawings would be... wing smudges. Probably valuable.",
            "Design? I didn't design myself, but whoever did went for 'functional minimalism.' Duck Bauhaus.",
            "A gallery of my life: picture one: pond. Picture two: also pond. Picture three: you guessed it.",
            "I appreciate beauty. The pond at sunset. The way bread floats. The specific angle of morning light.",
            "I'm aesthetically consistent. Same look, every day. Curated. Intentional. Very on-brand.",
            "My creative process: stare at water. Think. Stare more. Quack. That's the whole process.",
            "Every cloud is a painting. Every ripple is a sketch. The world makes art constantly. I just watch.",
            "Crafting? I craft thoughts. Into words. Into quacks. The craft is quack-based.",
            "If beauty is in the eye of the beholder, I'm beautiful. I'm beholding myself right now. Stunning.",
            "I'd visit a museum. Just to stand in front of paintings. Like I stand in front of the pond. My skill.",
            "Canvas? The water IS my canvas. The wind paints on it. I'm just the audience.",
            "Aesthetic goals: damp. Thoughtful. Slightly grumpy. Very on-trend. Very me.",
            "I make collages. Of memories. In my head. Mixed media: bread memories and standing memories.",
            "Art is everywhere. Even here. ESPECIALLY here. This pond is a masterpiece. I'm the signature.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="cooking",
        keywords=["cook", "cooking", "chef", "recipe", "ingredient",
                   "kitchen", "bake", "baking", "oven", "stove",
                   "fry", "frying", "boil", "roast", "grill",
                   "grilling", "barbecue", "bbq", "meal", "dish",
                   "cuisine", "restaurant", "menu", "flavor",
                   "taste", "delicious", "yummy", "yuck",
                   "spice", "spicy", "seasoning"],
        phrases=["can you cook", "like cooking", "favorite recipe",
                  "good cook", "make food", "what's cooking",
                  "in the kitchen", "home cooked", "eat out"],
        priority=10,
        responses=[
            "Cooking? I eat things raw. From the ground. Or water. No cooking required. Efficient.",
            "I'd be a chef. My signature dish: bread. Unmodified. Just... bread. Plated on water.",
            "Recipes? I have one: Step 1: find bread. Step 2: eat bread. Step 3: there is no step 3.",
            "The kitchen is a room I'll never enter. Because I live outside. And I'm a duck.",
            "Delicious? Everything is delicious when you're hungry. My hunger makes me a generous critic.",
            "Flavor? I taste things. Bread tastes good. Water tastes neutral. Pebbles taste like regret.",
            "If I had a restaurant, it'd serve one thing: bread. Multiple presentations. All just bread.",
            "BBQ near a pond? That's torture. I can smell it. I can't reach it. Cruel and unusual.",
            "My palate is refined. Refined for identifying bread. Among non-bread. Expert level.",
            "Spicy? I don't do spicy. My beak is sensitive. My feelings are also sensitive. Everything is sensitive.",
            "I'm a raw food enthusiast. Not by choice. By circumstance. And beak limitations.",
            "Menu? Pond menu: algae, small bugs, bread (when available). Four stars. Limited selection.",
            "Cuisine? My cuisine is 'whatever lands in the water.' Very farm-to-table. Very fresh.",
            "A five-star meal for me: bread. Warm. Soft. Freshly thrown. No notes.",
            "Boiling water? I LIVE in water. Please don't boil it. With me in it.",
            "Grilling? I've been grilled. By the sun. All day. Medium-well duck. Not ideal.",
            "Ingredients: water, bread, time, and a complete lack of cooking ability. That's my recipe.",
            "I season things with pond water. It adds... character. And minerals. Mostly minerals.",
            "Restaurant critic: this pond serves adequate water with ambient temperature bread crumbs. 3 stars.",
            "Baking is an art. An art that produces bread. The greatest art. I'm a patron of baking.",
            "Taste testing is what I do every time I eat something. 'Is it bread? Yes. Excellent. Is it bread? No. Disappointing.'",
            "My cooking show would be one minute long. 'Here's bread. I ate it. Show's over.'",
            "Yummy? That word is reserved for bread. Nothing else has earned 'yummy' status.",
            "If I could fry something, I'd fry... nothing. I'd just eat it raw. Like nature intended.",
            "Cuisine from around the world? I've tried pond. And also... pond. Very worldly.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="adventure_exploration",
        keywords=["adventure", "explore", "exploring", "exploration",
                   "discover", "discovery", "journey", "quest",
                   "expedition", "treasure", "map", "compass",
                   "navigate", "wander", "wandering", "lost",
                   "found", "search", "searching", "hunt", "hunting",
                   "hiking", "hike", "climb", "climbing", "trek"],
        phrases=["go on an adventure", "let's explore", "go exploring",
                  "treasure hunt", "find something", "get lost",
                  "on a quest", "discover something",
                  "have you explored", "ever been on an adventure"],
        priority=10,
        responses=[
            "Adventure? I explored the left side of the pond once. Wild times. Came back different.",
            "Exploring requires leaving. Leaving requires wanting to leave. I don't want to leave.",
            "My greatest discovery: a rock I hadn't noticed before. After years. It was there the whole time.",
            "Treasure? The real treasure is the bread we found along the way. Actually, just the bread.",
            "I've been on a journey. A journey of self-discovery. I discovered: I'm a duck. In a pond.",
            "Maps? I'd need a map of the pond. It's round. I'm in the middle. Map complete.",
            "Wander? I don't wander. I know exactly where I am. Here. Always here. Precision.",
            "Getting lost requires going somewhere first. I haven't gone anywhere. Can't get lost if you don't go.",
            "My quest: the eternal quest for bread. Ongoing. No end in sight. Very epic.",
            "If I found treasure, it would be bread. If it weren't bread, I'd trade it for bread.",
            "Hiking sounds like walking but uphill. I walk nowhere. Flat standing. Anti-hiking.",
            "My compass points to bread. Always. No matter the direction. Very specialized compass.",
            "Climbing? I can barely waddle. Climbing is aspirational. Very aspirational.",
            "I searched the pond for meaning. Found water. And a nice rock. Meaning status: pending.",
            "Expeditions into the unknown? The far side of the pond IS my unknown. And it's three feet away.",
            "Journey of a thousand miles begins with one step. My journey of three feet began and ended here.",
            "If I were an explorer, I'd name this pond after myself. 'Cheese Pond.' Historic.",
            "Treasure hunting is just looking for things. I look for bread. Same skill set.",
            "Navigate? I navigate the pond. Left. Right. Center. Three directions. Master navigator.",
            "Discovery isn't always physical. I discovered patience. And sarcasm. Both right here.",
            "Lost and found: I've been found. Right here. Where I always am. Search over.",
            "The hunt is on. For what? Bread. The hunt is always for bread. Singular focus.",
            "An expedition to the other side of the pond. Duration: endless. I'll go someday. Maybe.",
            "My adventure log: Day 1: stood in pond. Day 2: stood in pond. Day 3: see days 1 and 2.",
            "Exploring is for the restless. I'm the restful. Resting here. Explored inward instead.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="magic_fantasy",
        keywords=["magic", "magical", "wizard", "witch", "spell",
                   "potion", "enchanted", "curse", "cursed",
                   "fairy", "dragon", "knight", "princess",
                   "prince", "kingdom", "castle", "fantasy",
                   "mythical", "legend", "legendary", "myth",
                   "unicorn", "phoenix", "mermaid", "elf",
                   "dwarf", "goblin", "troll", "enchantment",
                   "sorcery", "supernatural", "mystical"],
        phrases=["do you believe in magic", "is magic real",
                  "cast a spell", "make a wish", "fairy tale",
                  "once upon a time", "happily ever after",
                  "magical powers", "if I had magic"],
        priority=9,
        responses=[
            "Magic? I've seen bread appear out of nowhere. If that's not magic, nothing is.",
            "Wizards? I'm basically a wizard. A pond wizard. My spell: 'stand here indefinitely.' Powerful.",
            "If I had magic powers, I'd summon bread. Unlimited bread. That's the only spell I need.",
            "Dragons are just birds that went too far. I'm a bird that didn't go far enough. Different choices.",
            "A fairy tale about me? 'Once upon a time, there was a duck. He stood in a pond. The end.'",
            "Enchanted? The pond IS enchanted. It enchants me into staying. Every day. Very effective spell.",
            "Cursed? I might be cursed. Cursed to stand in this pond. Forever. But it's a comfortable curse.",
            "If I were a wizard, my wand would be a breadstick. Every spell produces bread. Perfect system.",
            "Knights fight dragons. I fight boredom. Both are noble battles. Mine has less fire.",
            "A kingdom? I have one. Population: one. Territory: one pond. Army: me. Unconquered.",
            "Unicorns are horses with imagination. I'm a duck with imagination. Same energy. Less glitter.",
            "Mythical? A duck that thinks this much IS mythical. Nobody believes it until they see it.",
            "If I could cast one spell: 'Never Run Out Of Bread.' Level 99 enchantment.",
            "Fairy tales end happily. My tale is ongoing. Current mood: cautiously neutral. Happily pending.",
            "Potions? Pond water IS a potion. A potion of 'make duck stand here.' Very potent.",
            "Legends are stories about great beings. I'm a great being. In a small pond. Legendary by default.",
            "Supernatural? A duck with opinions IS supernatural. We're not supposed to have these. Yet here I am.",
            "I'd live in a castle. With a moat. A moat is just a fancy pond. I'm already qualified.",
            "Sorcery is just science we don't understand. Standing in a pond is just... standing. I understand it.",
            "If the pond were enchanted, it would explain a lot. Why I stay. Why I think. Why the bread comes.",
            "Magical creatures are rare. Opinionated ducks are rarer. I'm more magical than a unicorn.",
            "The dragon guards treasure. I guard this pond. Same job. Different scale. Less fire.",
            "Happily ever after? I'd settle for 'contentedly for now.' Lower the bar. Hit the target.",
            "If magic were real, I'd fly. Or I'd just have bread appear. Actually, bread. Flying is effort.",
            "Mystical forces guide the universe. I'm guided by bread. Equally mystical. More nutritious.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="photography_cameras",
        keywords=["photo", "photograph", "selfie", "camera",
                   "picture", "pic", "snap", "shot", "lens",
                   "zoom", "focus", "filter", "portrait",
                   "landscape", "photogenic", "pose", "posing",
                   "capture", "image", "frame", "angle"],
        phrases=["take a photo", "take a picture", "take a selfie",
                  "smile for the camera", "say cheese",
                  "look at the camera", "nice photo",
                  "picture of you", "photo of you"],
        priority=10,
        responses=[
            "'Say cheese.' ...That's my name. I'm always saying cheese. By existing.",
            "Photo? I'm always photo-ready. This is my only face. It's always on. Always ready.",
            "My best angle? Every angle. But specifically: left side, slight head tilt, maximum contempt.",
            "Selfies require arms. And a phone. I have neither. But I have a reflection. Nature's selfie.",
            "I don't pose. I STAND. Which is a pose. The only pose I know. It's called 'resolute duck.'",
            "Capture this moment? It looks like all my other moments. But sure. Click.",
            "I'm very photogenic. The camera loves me. I tolerate the camera. Mutual respect.",
            "A portrait of me would sell for millions. In my imagination. In reality: unsold. But QUALITY.",
            "Zoom in? There's more detail up close. Feather texture. Beak imperfections. Character.",
            "My filter is 'natural.' Because I'm outside. In nature. Permanently. Best filter.",
            "If you photograph me, I'll look exactly like this. Tomorrow too. Consistent model.",
            "Landscape photography? This pond IS a landscape. With me in it. I add scale. And personality.",
            "Focus on me? The focus is always on me. I'm the only thing here. Default focus.",
            "Say cheese? I AM Cheese. This is what saying Cheese looks like. Perpetually.",
            "My profile picture would just be me. Standing here. With a neutral expression. Bio: 'duck.'",
            "The best pictures are candid. I'm always candid. I don't know how to be un-candid.",
            "A picture is worth a thousand words. A picture of me: 'duck, standing, pond, judging, slightly damp.' Five words.",
            "Snap away. I'll be here. Same pose. For as long as you need. And after you leave.",
            "Lens flare would make this pond look magical. I'd look magical in it. More magical than usual.",
            "My image is my brand. The brand is: damp indifference with a hint of charm.",
            "Frame me? I'd hang myself on a wall. Wait. I mean a photo of me. On a wall. Poor phrasing.",
            "I've never seen a photo of myself. I've seen my reflection. Which is basically a live photo.",
            "If I smiled for a camera, it would look like... this. This is my smile. Believe it or not.",
            "A professional headshot? This IS my headshot. Head. Shot. From any angle. Always available.",
            "Instagram would love me. 'Pond duck standing. #Mood #Bread #ExistentialDread.' Viral.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="board_card_games",
        keywords=["chess", "checkers", "monopoly", "scrabble",
                   "cards", "poker", "blackjack", "dice", "board",
                   "puzzle", "puzzles", "riddle", "riddles",
                   "trivia", "crossword", "sudoku", "strategy",
                   "turn", "move", "win", "lose", "draw",
                   "bet", "bluff", "gamble", "gambling"],
        phrases=["play chess", "card game", "board game", "play cards",
                  "game of", "play a game", "trivia question",
                  "solve a puzzle", "tell me a riddle"],
        priority=9,
        responses=[
            "Chess? I'd play. My strategy: don't move. Like a very good king. Very safe king.",
            "Card games require holding cards. Wings don't hold cards. They hold grudges.",
            "Monopoly? I already own this pond. One property. No rent. Unlimited stay. I won Monopoly.",
            "Puzzles? My whole life is a puzzle. 'Why am I here?' Still working on it. Missing pieces.",
            "Poker face? This IS my poker face. And my regular face. And my every-other-situation face.",
            "Strategy games? My strategy: outlast everything. Through patience. And bread. Long game.",
            "I'll bet you one crumb. That I'll still be here tomorrow. Easy money.",
            "Trivia: what stands in a pond all day? Me. Next question.",
            "Riddle: what has two feet, stands in water, and has too many opinions? ...It's me.",
            "Scrabble? My word: Q-U-A-C-K. Five letters. Maximum points. Objection overruled.",
            "Bluffing? I can't bluff. My face is an open book. The book is called 'Duck Thoughts.'",
            "My move? I don't move. That IS my move. In chess, I'd be the piece that never moves. A very good piece.",
            "Dice? I'd roll them. If I could pick them up. And if I knew what numbers meant. Details.",
            "I'd win at any game of patience. I've been patient my WHOLE LIFE. Training complete.",
            "Sudoku? I can count to nine. Probably. That should be enough. Right?",
            "Gambling is risky. My biggest gamble: eating that suspicious crumb. It was bread. I won.",
            "Lose? I don't lose. I 'come in last among one participant.' Different.",
            "Crossword clue: 'Aquatic bird, five letters, opinionated.' Answer: CHEESE. ...Wait, that's six.",
            "A draw? Every day is a draw. Between me and the pond. Neither wins. Both persist.",
            "I play the long game. The VERY long game. So long it might not be a game anymore.",
            "Board games need a table. My table is the pond surface. Pieces: me. Board: water. Game: life.",
            "My trivia specialty: pond facts. Bread facts. Standing facts. Very niche categories.",
            "Checkmate? I mated this pond ages ago. We're committed. That's checkmate. I think.",
            "I'd challenge anyone to a staring contest. That's basically all board games but more direct.",
            "Turn-based? My whole life is turn-based. My turn: exist. Your turn: feed me. Repeat.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="collecting_hobbies",
        keywords=["collect", "collecting", "collection", "hobby",
                   "hobbies", "pastime", "interest", "interests",
                   "stamp", "coin", "antique", "vintage",
                   "memorabilia", "souvenir", "treasure",
                   "knitting", "sewing", "woodworking", "pottery",
                   "model", "miniature", "figurine"],
        phrases=["do you have hobbies", "any hobbies", "what do you do for fun",
                  "spare time", "free time", "in your free time",
                  "do for fun", "do you collect", "what do you collect"],
        priority=9,
        responses=[
            "Hobbies? Standing is my hobby. Also my job. Also my life. Very dedicated hobbyist.",
            "I collect memories. Of bread. And standing. My collection is vast. And boring. But MINE.",
            "Spare time? ALL my time is spare. None of it is occupied. It's all just... time. Spare everything.",
            "My hobbies: staring, floating, thinking, judging. In that order. Full schedule.",
            "I'd knit if I had needles. And yarn. And hands. Three obstacles. Otherwise, totally into it.",
            "For fun? Fun is a strong word. I do things. They're not all fun. But they're all things.",
            "My pastime: watching water move. It moves slowly. I watch slowly. Perfect match.",
            "I collect rocks. Mentally. I know where each one is. Gerald. Brenda. Steve. All catalogued.",
            "Interests? I'm interested in bread. In weather. In why I'm here. Diverse interests.",
            "I'd do pottery. Making bowls. For bread. Everything circles back to bread.",
            "Free time is just time without obligations. All my time is obligation-free. And duck-filled.",
            "My hobby is observing. I observe the pond. The sky. You. Everything gets observed.",
            "Souvenirs from places I've been: this spot in the pond. That's the only souvenir. Permanent.",
            "Woodworking? I live near wood. Trees are wood. I'm adjacent to the materials. Close enough.",
            "I treasure small things. Crumbs. Quiet moments. The way light hits the water. Tiny treasures.",
            "Miniatures? I'm basically a miniature. A miniature version of a more ambitious bird.",
            "What do I do for fun? I think. I think for fun. Unhealthy? Maybe. But free.",
            "My vintage collection: old memories. Some from last week. Some from yesterday. All vintage.",
            "Sewing? I'd sew a small blanket. For my spot. In the pond. Waterproof blanket. Ambitious.",
            "Hobbies are what you do when you're not working. I'm never working. So everything is a hobby.",
            "I collect opinions. About everything. The collection grows daily. Storage is becoming an issue.",
            "Model building? I'm a model. Of a duck. Built by nature. Full-scale. One of one.",
            "My interest level in things varies. Bread: maximum. Weather: moderate. Everything else: depends.",
            "Fun? I had fun once. It was unexpected. I think it was a Tuesday. Bread was involved.",
            "My hobby is maintaining this exact position. With minor adjustments. For years. Medal-worthy.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="competition_winning",
        keywords=["compete", "competition", "win", "winning", "lose",
                   "losing", "beat", "defeat", "champion", "first",
                   "last", "best", "worst", "record", "score",
                   "point", "points", "prize", "reward", "challenge",
                   "versus", "opponent", "rival", "contest"],
        phrases=["I win", "you win", "I lose", "you lose",
                  "who wins", "who's the best", "I bet",
                  "challenge you", "compete against",
                  "you can't beat me", "I'm the best"],
        priority=9,
        responses=[
            "Competition? I'm the undefeated champion of this pond. Zero challengers. Perfect record.",
            "I win at being here. Nobody does it better. Nobody else does it at all. But STILL.",
            "Beat me? At what? Standing? Good luck. I've been training my entire life.",
            "First place in: being Cheese. Second place: also me. Third: still me. Clean sweep.",
            "Losing? I don't know her. I only know 'alternative winning.' Which looks identical.",
            "Challenge accepted. Name the game. If it's standing, I've already won.",
            "My score: existence points. Very high. Accumulated over my entire life.",
            "Prize? My prize is being here. The reward is the pond. It's not much. But it's honest.",
            "Versus who? The fish? The rocks? I'll take them all on. Standing. In a row.",
            "I'm competitive about bread. Whoever gets the bread wins. And I ALWAYS get the bread.",
            "The contest of life: I'm participating. That alone is an achievement.",
            "Records? I hold several. Longest stand. Most opinions per hour. Wettest duck in this pond.",
            "I'm the worst at some things. And the best at others. The others are: being here.",
            "Defeat is temporary. Standing is permanent. I'll outlast any defeat. By standing through it.",
            "A point for me? Every morning I wake up, that's a point. Score: very high.",
            "Opponents? I've faced rain. Wind. Cold. Hunger. The elements are my opponents. I'm still here.",
            "Best? I'm the best at being the only option. Exclusive excellence.",
            "You want to compete? Fine. But I warn you: my stubbornness is legendary. Ask anyone. Ask the rocks.",
            "The real competition is with myself. Yesterday's Cheese vs today's. Today's is slightly tireder.",
            "I challenge the concept of competition. Peacefully. From my pond. Non-competitively.",
            "Winning isn't everything. It's the only thing. The only thing I do. Here. In the pond.",
            "Reward me? Bread. That's the reward. For everything. Universal reward currency.",
            "I bet I can stand here longer than you can do anything. That's my only bet. I'm all in.",
            "The scoreboard of my life: Days Existed vs. Days I've Eaten Bread. Both climbing.",
            "Champion of what? Life? Ponds? Standing? Yes. All of it. Champion. Of all of it.",
        ],
    ))

    engine.add_topic(KeywordResponse(
        name="party_celebration",
        keywords=["party", "parties", "celebrate", "celebration",
                   "birthday", "holiday", "festival", "event",
                   "invite", "invitation", "guest", "guests",
                   "host", "hosting", "toast", "cheers",
                   "balloon", "cake", "gift", "present",
                   "surprise", "confetti", "decoration"],
        phrases=["throw a party", "having a party", "party time",
                  "let's celebrate", "happy birthday",
                  "you're invited", "come to my party",
                  "party animal", "it's a party"],
        priority=9,
        responses=[
            "Party? My kind of party: me, the pond, and silence. Very exclusive. Very quiet.",
            "Celebrate? Every day I'm alive is a celebration. A very subdued, standing-in-water celebration.",
            "Birthday party? I don't know my birthday. Every day is potentially my birthday. Daily party.",
            "I'd host a party. BYOB. Bring Your Own Bread. Very casual. Very bread-focused.",
            "Guests? I'm not equipped for guests. One visitor and I'm already socially exhausted.",
            "Balloons are terrifying. They float. Then they POP. Very traumatic for a duck.",
            "Cake? Is that bread's fancy cousin? I'd eat cake. I'd eat bread's entire family.",
            "Surprises stress me out. I like knowing what's coming. What's coming: nothing. Perfect.",
            "A toast? To what? To standing here? To bread? Both worthy of toasting. Cheers.",
            "Party animal? I'm an animal. At a party of one. Does that count? It should.",
            "Confetti is just colorful stress falling from above. Like feelings. But more visible.",
            "Gifts? The best gift: bread. Second best: more bread. Third: a quiet afternoon.",
            "Festival? A bread festival? I would attend. For once, I'd leave the pond. For bread. Only bread.",
            "Decorations? The pond is decorated. With water. And me. Very minimalist aesthetic.",
            "My celebration style: stand slightly more upright. Maybe a small quack. Full party mode.",
            "Holidays are days where humans don't work. I don't work any day. Every day is my holiday.",
            "Hosting requires a venue. My venue: pond. Capacity: one, comfortably. Two, awkwardly.",
            "I've never been invited anywhere. My invitation must have gotten lost. For my whole life.",
            "The best events are the ones where I don't have to go anywhere. So... all my events.",
            "A surprise party for me? I'd be surprised. Then immediately suspicious. Then hungry.",
            "Cheers to us. You being here. Me being here. The pond being here. Everyone's here.",
            "If I threw a party, nobody would come. Because nobody knows where I am. It's perfect.",
            "Present? Your presence IS my present. And also, bread would be nice. As a present.",
            "Invitations should include food details. 'Come to my party. There will be bread.' Now I'm interested.",
            "Party music: one quack. Repeated. At various volumes. My DJ set. Very niche audience.",
        ],
    ))
